"""MF-16 G: pre-settle coffee and milk inside the MF-16 boundary-ball vessels.

This keeps the MF-15 narrative and coffee population baseline, but replaces every analytic
cup/cylinder/pitcher boundary with the two assets generated by ``mf16_balls.py``:

* a static mug ball set at the world origin;
* a kinematic jug ball set built directly at ``JUG_POS`` with identity orientation;
* the analytic table plane at z=0 remains as the common support surface.

The visible OBJ and collision NPZ assets share the same local frame and geometry dictionary.
This script verifies that contract and applies one pose constant to both interpretations.  Ball
particles are solver-owned rows appended after entity particles.  The saved settled state slices
every particle-shaped array to the fluid prefix; rebuilding a later scene must recreate its ball
rows from the NPZ assets.

Calibration protocol
--------------------
The density/ST recipe is the MF-15 verified high-column recipe (not the stock
``density_lambda_epsilon=100``): dt=1/240, four substeps, lambda epsilon 0.1, 20 density
iterations, PBSTF compliance 1, velocity damping 0.99.  K_Z is deliberately a command-line
parameter and must be re-measured for the ball walls.  Run several short ``--calibration`` jobs,
select a K_Z whose z99 fill is near the requested band without ejection, then run the full 6 s
job.  Calibration mode never writes the canonical settled file.

Strict acceptance (formal run)
------------------------------
* coffee uses a relaxed 84--86% fill target while milk remains deterministically 4,000--6,000
  particles above the MF-15 baseline, providing the two-stage volume required by H;
* NaN/Inf count is zero throughout;
* escaped fraction is below 1% independently for mug and jug;
* concentration sum drifts by less than 1% and particle count is unchanged;
* coffee and milk z99 fill levels lie in their target bands;
* the final 1 s window has no upward KE/level trend (reported and asserted);
* ``mf16_settled.npz`` contains fluid-only ``pos``, ``vel`` and ``c`` arrays.

No IPBF/paper algorithm is changed here; this is an MF PBD scene/setup calibration only.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from pathlib import Path


WORKSPACE = Path(__file__).resolve().parents[1]  # multiflow/
sys.path.insert(0, str(WORKSPACE / "genesis-world"))

import numpy as np  # noqa: E402

import genesis as gs  # noqa: E402


assert Path(gs.__file__).resolve().is_relative_to(WORKSPACE.resolve()), (
    f"Wrong genesis: {gs.__file__}; expected the multiflow copy under {WORKSPACE}."
)

VIDEOS_DIR = WORKSPACE / "videos"
MUG_NPZ = VIDEOS_DIR / "mf16_balls_mug.npz"
JUG_NPZ = VIDEOS_DIR / "mf16_balls_jug.npz"
MUG_OBJ = WORKSPACE / "assets" / "mug.obj"
JUG_OBJ = WORKSPACE / "assets" / "jug.obj"

PS = 0.008
DT = 1.0 / 240.0
SUBSTEPS = 4
Z_TABLE = 0.0

# The NPZ and OBJ local origin is the outer-bottom centre.  The inner cavity floor is one bottom
# thickness above it; the inner wall height is 0.30 m and the physical rim is at z=0.316 m.
MUG_POS = np.array((0.0, 0.0, 0.0), dtype=np.float32)
JUG_POS = np.array((0.42, 0.0, 0.0), dtype=np.float32)
IDENTITY_QUAT = np.array((1.0, 0.0, 0.0, 0.0), dtype=np.float32)
Z_FLOOR = 0.016
# Fluid-centre contact plane against the discrete floor balls.  Keeping the lowest jittered
# centre here avoids manufacturing an initial half-spacing overlap with the numerical wall.
Z_CONTACT = Z_FLOOR + 0.5 * PS
H_IN = 0.30
Z_RIM = Z_FLOOR + H_IN
R_MUG = 0.150
R_JUG = 0.125
T_WALL = 0.016
T_BOTTOM = 0.016

FILL_C, FILL_M = 0.85, 0.92
BAND_C = (0.84, 0.86)
BAND_M = (0.88, 0.96)
R_C_SAMPLE = R_MUG - 0.5 * PS
R_M_SAMPLE = R_JUG - 0.5 * PS
POS_JITTER = 0.25 * PS
JITTER_SEED = 20260911

# H needs a relaxed coffee fill to create a real, connected dome before the independent final
# milk pulse.  Preserve both MF-15 baselines in metadata and record the exact deterministic
# additions instead of treating the former coffee population as the new target.
BASE_N_COFFEE = 42_840
BASE_N_MILK = 31_152
ADDED_MILK_RANGE = (4_000, 6_000)

LOWER_BOUND = np.array((-0.35, -0.35, Z_TABLE), dtype=np.float32)
UPPER_BOUND = np.array((0.80, 0.35, 0.80), dtype=np.float32)


def _load_asset(path: Path, expected_body: str, expected_kinematic: bool):
    assert path.is_file(), f"missing generated MF-16 ball asset: {path}"
    with np.load(path) as data:
        assert set(data.files) == {"pos_local", "meta"}, f"unexpected keys in {path}: {data.files}"
        pos = np.asarray(data["pos_local"], dtype=np.float32)
        meta = json.loads(str(data["meta"].item()))
    assert pos.ndim == 2 and pos.shape[1] == 3 and len(pos) > 0
    assert np.isfinite(pos).all()
    assert meta["body"] == expected_body
    assert bool(meta["kinematic"]) is expected_kinematic
    geom = meta["geometry"]
    expected_r = R_MUG if expected_body == "mug" else R_JUG
    assert abs(float(meta["ps"]) - PS) < 1e-12
    assert abs(float(geom["r_in"]) - expected_r) < 1e-12
    assert abs(float(geom["h_in"]) - H_IN) < 1e-12
    assert abs(float(geom["t_wall"]) - T_WALL) < 1e-12
    assert abs(float(geom["t_bottom"]) - T_BOTTOM) < 1e-12
    assert abs(float(geom["z_rim"]) - Z_RIM) < 1e-12
    assert "mf16_balls.py shared dictionaries" in geom["source"]
    return pos, meta


def _assert_asset_and_hash_contract():
    assert MUG_OBJ.is_file() and JUG_OBJ.is_file(), "visible MF-16 OBJ assets are missing"
    mug_local, mug_meta = _load_asset(MUG_NPZ, "mug", False)
    jug_local, jug_meta = _load_asset(JUG_NPZ, "jug", True)
    mug_world = mug_local + MUG_POS
    jug_world = jug_local + JUG_POS
    world = np.concatenate((mug_world, jug_world), axis=0)
    # SpatialHasher hashes particle centres.  The floor ball centres intentionally sit at z=0;
    # their collision radius extends below the table/hash lower plane, but no centre may do so.
    envelope_lo = world.min(axis=0)
    envelope_hi = world.max(axis=0)
    assert np.all(envelope_lo >= LOWER_BOUND - 1e-7), (envelope_lo, LOWER_BOUND)
    assert np.all(envelope_hi < UPPER_BOUND), (envelope_hi, UPPER_BOUND)
    print(
        "asset contract: shared mf16 source + local outer-bottom frame; "
        f"mug balls={len(mug_local)} static pose={MUG_POS.tolist()} obj={MUG_OBJ.name}; "
        f"jug balls={len(jug_local)} kinematic pose={JUG_POS.tolist()} obj={JUG_OBJ.name}"
    )
    print(
        f"hash centre envelope: lo={envelope_lo.tolist()} hi={envelope_hi.tolist()} "
        f"inside [{LOWER_BOUND.tolist()}, {UPPER_BOUND.tolist()})"
    )
    print(
        f"asset face counts: mug={mug_meta['counts_by_face']} | jug={jug_meta['counts_by_face']}"
    )
    return mug_local, jug_local


def _container_metrics(pos: np.ndarray, centre_xy: np.ndarray, radius: float):
    radial = np.linalg.norm(pos[:, :2] - centre_xy[None, :], axis=1)
    # A one-spacing tolerance measures actual escape rather than benign contact with the two-layer
    # discrete wall/floor.  Above-rim particles count as escaped even if still over the opening.
    inside = (
        (radial <= radius + PS)
        & (pos[:, 2] >= Z_FLOOR - PS)
        & (pos[:, 2] <= Z_RIM + PS)
    )
    return radial, inside


def _tail_nonincreasing(values: list[float], rel_tol: float):
    if len(values) < 4:
        return True, 0.0
    half = len(values) // 2
    a = float(np.mean(values[:half]))
    b = float(np.mean(values[half:]))
    growth = (b - a) / max(abs(a), 1e-12)
    return growth <= rel_tol, growth


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--seconds", type=float, default=6.0)
    parser.add_argument("--substeps", type=int, default=SUBSTEPS,
                        help="physics substeps per 1/240 s frame (default 4)")
    parser.add_argument("--dens-iters", type=int, default=20)
    parser.add_argument("--leps", type=float, default=0.1)
    parser.add_argument("--st-comp", type=float, default=1.0)
    parser.add_argument("--vdamp", type=float, default=0.99)
    parser.add_argument("--h-c0", type=float, default=0.390)
    parser.add_argument("--h-m0", type=float, default=0.405)
    parser.add_argument("--kz", type=float, required=True, help="ball-wall-specific axial pre-compression")
    parser.add_argument("--calibration", action="store_true", help="report a short calibration row; do not save")
    args = parser.parse_args()
    assert args.seconds > 0.0 and 0.0 < args.kz <= 1.0 and args.substeps >= 1
    assert args.leps < 1.0, "stock epsilon=100 collapses this high column; use the MF-15 verified recipe"

    print("genesis loaded from:", gs.__file__)
    print(
        f"mode={'CALIBRATION' if args.calibration else 'FORMAL'} seconds={args.seconds:g} "
        f"K_Z={args.kz:.5f} h_c0={args.h_c0:.5f} h_m0={args.h_m0:.5f}"
    )
    print(
        f"solver recipe: dt={DT:.9f} substeps={args.substeps} dt_sub={DT / args.substeps:.9f} "
        f"density_iters={args.dens_iters} lambda_epsilon={args.leps:g} "
        f"st_compliance={args.st_comp:g} velocity_damping={args.vdamp:g}"
    )
    mug_local, jug_local = _assert_asset_and_hash_contract()

    gs.init(backend=gs.gpu, precision="32", seed=0, logging_level="warning")
    scene = gs.Scene(
        sim_options=gs.options.SimOptions(dt=DT, substeps=args.substeps, gravity=(0.0, 0.0, -9.81)),
        pbd_options=gs.options.PBDOptions(
            particle_size=PS,
            lower_bound=tuple(LOWER_BOUND),
            upper_bound=tuple(UPPER_BOUND),
            boundary_ball_sets=((str(MUG_NPZ), False), (str(JUG_NPZ), True)),
            boundary_ball_initial_poses=(
                (tuple(MUG_POS), tuple(IDENTITY_QUAT)),
                (tuple(JUG_POS), tuple(IDENTITY_QUAT)),
            ),
            boundary_plane=(Z_TABLE,),
            diffusion_coeff=0.0,
            max_density_solver_iterations=args.dens_iters,
            max_viscosity_solver_iterations=1,
            density_lambda_epsilon=args.leps,
            surface_tension_enabled=True,
            st_compliance=args.st_comp,
            st_surface_density_factor=1.0,
            st_distance_enabled=True,
            st_distance_compliance=40.0,
            st_max_surface_neighbors=256,
            velocity_damping=args.vdamp,
            wall_adhesion_enabled=True,
            wall_adhesion_compliance=20.0,
        ),
        vis_options=gs.options.VisOptions(render_particle_as="points"),
        show_viewer=False,
    )
    coffee = scene.add_entity(
        material=gs.materials.PBD.Liquid(
            sampler="regular", rho=1000.0, c_init=1.0, density_relaxation=0.2, viscosity_relaxation=0.01
        ),
        morph=gs.morphs.Cylinder(
            radius=R_C_SAMPLE,
            height=args.h_c0,
            pos=(MUG_POS[0], MUG_POS[1], Z_FLOOR + 0.5 * PS + 0.5 * args.h_c0),
        ),
    )
    milk = scene.add_entity(
        material=gs.materials.PBD.Liquid(
            sampler="regular", rho=1000.0, c_init=0.0, density_relaxation=0.2, viscosity_relaxation=0.01
        ),
        morph=gs.morphs.Cylinder(
            radius=R_M_SAMPLE,
            height=args.h_m0,
            pos=(JUG_POS[0], JUG_POS[1], Z_FLOOR + 0.5 * PS + 0.5 * args.h_m0),
        ),
    )

    scene.build()
    solver = scene.sim.pbd_solver
    n_coffee, n_milk = coffee.n_particles, milk.n_particles
    n_fluid = n_coffee + n_milk
    added_coffee = n_coffee - BASE_N_COFFEE
    assert added_coffee > 0, f"relaxed coffee fill did not exceed baseline: {n_coffee}"
    added_milk = n_milk - BASE_N_MILK
    assert ADDED_MILK_RANGE[0] <= added_milk <= ADDED_MILK_RANGE[1], (
        f"milk increase {added_milk} outside requested {ADDED_MILK_RANGE}; total={n_milk}"
    )
    assert solver._n_entity_particles == solver._n_fluid_particles == n_fluid
    assert solver.n_boundary_balls == len(mug_local) + len(jug_local)
    assert solver.n_particles == n_fluid + solver.n_boundary_balls
    expected_ranges = [
        (n_fluid, n_fluid + len(mug_local), False),
        (n_fluid + len(mug_local), n_fluid + len(mug_local) + len(jug_local), True),
    ]
    assert solver.boundary_ball_ranges == expected_ranges
    assert solver._has_boundary_balls and solver._n_ball_sets == 2
    assert solver._diffusion_coeff == 0.0
    assert not solver._has_boundary_cylinder
    assert not solver._has_boundary_pitcher and not solver._has_boundary_cup_shell
    assert solver.boundary2 is None and solver.boundary_cup is None
    assert type(solver.boundary).__name__ == "CubeBoundary"
    assert type(solver.boundary3).__name__ == "PlaneBoundary"
    print(
        f"particle layout: fluid={n_fluid} ({n_coffee}+{n_milk}); "
        f"balls={solver.n_boundary_balls} ({len(mug_local)}+{len(jug_local)}); total={solver.n_particles}"
    )

    # The initial-pose API places the jug before Scene.build's hidden compile step, so there is no
    # identity->target sweep and no transient overlap with the mug.  The same constants are the
    # visible-OBJ pose; no post-build pose upload is needed for this static presettle.
    all_pos = solver.particles.pos.to_numpy()[:, 0, :]
    mug_slice = slice(*expected_ranges[0][:2])
    jug_slice = slice(*expected_ranges[1][:2])
    pose_err_mug = float(np.max(np.abs(all_pos[mug_slice] - (mug_local + MUG_POS))))
    pose_err_jug = float(np.max(np.abs(all_pos[jug_slice] - (jug_local + JUG_POS))))
    assert pose_err_mug < 5e-7 and pose_err_jug < 5e-7

    ng_active = solver.particles_ng.active.to_numpy()[n_fluid:, 0]
    ng_boundary = solver.particles_ng.is_boundary.to_numpy()[n_fluid:, 0]
    ball_free = solver.particles.free.to_numpy()[n_fluid:, 0]
    ball_material = solver.particles_info.material_type.to_numpy()[n_fluid:]
    assert np.all(ng_active) and np.all(ng_boundary) and not np.any(ball_free)
    assert np.all(ball_material == int(solver.MATERIAL.PARTICLE))

    # Runtime proof of the ownership contract. Scene state is entity-only; solver-owned ball
    # geometry must stay unchanged across both an explicit round-trip and a bare reset.
    ball_ref = all_pos[n_fluid:].copy()
    state = solver.get_state(0)
    assert tuple(state.pos.shape) == (1, solver.n_entity_particles, 3)
    assert tuple(state.free.shape) == (1, solver.n_entity_particles)
    solver.set_state(0, state)
    state_err = float(np.max(np.abs(solver.particles.pos.to_numpy()[n_fluid:, 0, :] - ball_ref)))
    assert state_err == 0.0, f"state restore overwrote solver-owned balls: {state_err}"
    scene.reset()
    reset_err = float(np.max(np.abs(solver.particles.pos.to_numpy()[n_fluid:, 0, :] - ball_ref)))
    assert reset_err == 0.0, f"scene.reset overwrote solver-owned balls: {reset_err}"
    print(
        f"pose/state contract: mug_err={pose_err_mug:.3e} jug_err={pose_err_jug:.3e} "
        f"entity-state shape={tuple(state.pos.shape)} ball_err={state_err:.3e} "
        f"reset_ball_err={reset_err:.3e} PASS"
    )

    rng = np.random.default_rng(JITTER_SEED)
    for name, ent, centre, sample_r in (
        ("coffee", coffee, MUG_POS[:2], R_C_SAMPLE),
        ("milk", milk, JUG_POS[:2], R_M_SAMPLE),
    ):
        pos = ent.get_particles_pos().cpu().numpy()
        pos += rng.uniform(-POS_JITTER, POS_JITTER, size=pos.shape)
        pos[:, 2] = Z_CONTACT + (pos[:, 2] - Z_CONTACT) * args.kz
        pos[:, 2] = np.maximum(pos[:, 2], Z_CONTACT)
        ent.set_particles_pos(pos)
        ent.set_particles_vel(np.zeros_like(pos))
        r = np.linalg.norm(pos[:, :2] - centre[None, :], axis=1)
        print(
            f"preset {name}: n={len(pos)} z=[{pos[:, 2].min():.5f},{pos[:, 2].max():.5f}] "
            f"r_max={r.max():.5f} sample_r={sample_r:.5f}; jitter=+/-{POS_JITTER:g} seed={JITTER_SEED}"
        )

    # Script lid is a presettle-only guard against substep-scale ejection from the nearly full jug.
    # It writes the milk entity only, never the appended ball rows.
    milk_lid_z = Z_FLOOR + min(args.h_m0 * args.kz + 2.0 * PS, H_IN - 0.003)
    print(f"milk presettle lid: z_cap={milk_lid_z:.5f}, physical rim={Z_RIM:.5f}")

    c_initial = solver.particles.c.to_numpy()[:n_fluid, 0].copy()
    sum_c0 = float(np.sum(c_initial, dtype=np.float64))
    assert np.allclose(c_initial[:n_coffee], 1.0) and np.allclose(c_initial[n_coffee:], 0.0)

    n_frames = int(round(args.seconds / DT))
    print_every = max(1, int(round(0.25 / DT if args.calibration else 0.5 / DT)))
    tail_start = max(0, n_frames - int(round(min(1.0, args.seconds * 0.4) / DT)))
    tail_ke: list[float] = []
    tail_fill_c: list[float] = []
    tail_fill_m: list[float] = []
    max_nan = 0
    max_leak_c = 0.0
    max_leak_m = 0.0
    max_c_drift = 0.0
    max_ke = 0.0
    max_capped = 0
    wall0 = time.time()
    for frame in range(n_frames):
        scene.step()
        milk_pos = milk.get_particles_pos().cpu().numpy()
        over = milk_pos[:, 2] > milk_lid_z
        if np.any(over):
            milk_pos[over, 2] = milk_lid_z
            milk.set_particles_pos(milk_pos)

        pos_state = solver.particles.pos.to_numpy()
        vel_state = solver.particles.vel.to_numpy()
        c_state = solver.particles.c.to_numpy()
        pos = pos_state[:n_fluid, 0, :]
        vel = vel_state[:n_fluid, 0, :]
        c_now = c_state[:n_fluid, 0]
        nan = int(
            (~np.isfinite(pos_state)).sum()
            + (~np.isfinite(vel_state)).sum()
            + (~np.isfinite(c_state)).sum()
        )
        max_nan = max(max_nan, nan)
        safe = np.nan_to_num(pos, nan=0.0, posinf=0.0, neginf=0.0)
        cp, mp = safe[:n_coffee], safe[n_coffee:]
        _, in_c = _container_metrics(cp, MUG_POS[:2], R_MUG)
        _, in_m = _container_metrics(mp, JUG_POS[:2], R_JUG)
        leak_c = 1.0 - float(np.mean(in_c))
        leak_m = 1.0 - float(np.mean(in_m))
        max_leak_c, max_leak_m = max(max_leak_c, leak_c), max(max_leak_m, leak_m)
        sum_c = float(np.nansum(c_now, dtype=np.float64))
        c_drift = abs(sum_c - sum_c0) / max(abs(sum_c0), 1.0)
        max_c_drift = max(max_c_drift, c_drift)
        ke = float(0.5 * np.nansum(np.sum(vel * vel, axis=1)))
        max_ke = max(max_ke, ke)
        max_capped = max(max_capped, int(over.sum()))
        fill_c = (float(np.percentile(cp[:, 2], 99)) - Z_FLOOR) / H_IN
        fill_m = (float(np.percentile(mp[:, 2], 99)) - Z_FLOOR) / H_IN
        if frame >= tail_start:
            tail_ke.append(ke)
            tail_fill_c.append(fill_c)
            tail_fill_m.append(fill_m)
        if (frame + 1) % print_every == 0 or frame == n_frames - 1:
            print(
                f"t={(frame + 1) * DT:5.2f}/{args.seconds:g}s KE={ke:.6e} "
                f"fill99=({fill_c:.4f},{fill_m:.4f}) "
                f"leak=({leak_c:.4%},{leak_m:.4%}) capped={int(over.sum())} "
                f"sum_c={sum_c:.6f} drift={c_drift:.3e} nan={nan} "
                f"wall_ms/frame={(time.time() - wall0) / (frame + 1) * 1000:.1f}"
            )

    pos_full = solver.particles.pos.to_numpy()
    vel_full = solver.particles.vel.to_numpy()
    c_full = solver.particles.c.to_numpy()
    pos = pos_full[:n_fluid].copy()
    vel = vel_full[:n_fluid].copy()
    c = c_full[:n_fluid].copy()
    cp, mp = pos[:n_coffee, 0, :], pos[n_coffee:, 0, :]
    r_c, in_c = _container_metrics(cp, MUG_POS[:2], R_MUG)
    r_m, in_m = _container_metrics(mp, JUG_POS[:2], R_JUG)
    leak_c = 1.0 - float(np.mean(in_c))
    leak_m = 1.0 - float(np.mean(in_m))
    fill_c = (float(np.percentile(cp[:, 2], 99)) - Z_FLOOR) / H_IN
    fill_m = (float(np.percentile(mp[:, 2], 99)) - Z_FLOOR) / H_IN
    final_nan = int(
        (~np.isfinite(pos_full)).sum() + (~np.isfinite(vel_full)).sum() + (~np.isfinite(c_full)).sum()
    )
    sum_c_final = float(np.sum(c[:, 0], dtype=np.float64))
    final_c_drift = abs(sum_c_final - sum_c0) / max(abs(sum_c0), 1.0)
    c_phase_error = max(
        float(np.max(np.abs(c[:n_coffee, 0] - 1.0))),
        float(np.max(np.abs(c[n_coffee:, 0]))),
    )
    ke_ok, ke_growth = _tail_nonincreasing(tail_ke, 0.20)
    fc_ok, fc_growth = _tail_nonincreasing(tail_fill_c, 0.01)
    fm_ok, fm_growth = _tail_nonincreasing(tail_fill_m, 0.01)
    tail_level_span_c = float(np.ptp(tail_fill_c)) if tail_fill_c else 0.0
    tail_level_span_m = float(np.ptp(tail_fill_m)) if tail_fill_m else 0.0

    print("=" * 88)
    print(
        f"FINAL K_Z={args.kz:.5f}: coffee fill99={fill_c:.5f} leak={leak_c:.6%} "
        f"z=[{cp[:, 2].min():.5f},{cp[:, 2].max():.5f}] r_max={r_c.max():.5f}"
    )
    print(
        f"FINAL K_Z={args.kz:.5f}: milk   fill99={fill_m:.5f} leak={leak_m:.6%} "
        f"z=[{mp[:, 2].min():.5f},{mp[:, 2].max():.5f}] r_max={r_m.max():.5f}"
    )
    print(
        f"conservation: fluid={len(pos)} expected={n_fluid}; sum_c={sum_c0:.6f}->{sum_c_final:.6f} "
        f"final_drift={final_c_drift:.3e} max_drift={max_c_drift:.3e}; "
        f"phase_c_error={c_phase_error:.3e}; nan_final={final_nan} max_nan={max_nan}"
    )
    print(
        f"tail stability: KE growth={ke_growth:+.3%}; fill growth=({fc_growth:+.3%},{fm_growth:+.3%}); "
        f"fill span=({tail_level_span_c:.5f},{tail_level_span_m:.5f})"
    )
    print(
        f"CALIBRATION_ROW K_Z={args.kz:.5f} seconds={args.seconds:g} "
        f"fill_c={fill_c:.6f} fill_m={fill_m:.6f} leak_c={leak_c:.8f} leak_m={leak_m:.8f} "
        f"max_leak_c={max_leak_c:.8f} max_leak_m={max_leak_m:.8f} "
        f"ke_tail_growth={ke_growth:.8f} fill_span_c={tail_level_span_c:.8f} "
        f"fill_span_m={tail_level_span_m:.8f} max_ke={max_ke:.8e} max_capped={max_capped} "
        f"nan={max_nan} c_drift={max_c_drift:.8e}"
    )

    final_ball = pos_full[n_fluid:, 0, :]
    final_ball_err = float(np.max(np.abs(final_ball - ball_ref)))
    collision_overlap, collision_swept = solver.boundary_ball_collision_stats()
    print(
        f"boundary-ball proof: final_pose_err={final_ball_err:.3e}; "
        f"contacts overlap={collision_overlap} swept={collision_swept}"
    )

    # Hard invariants apply to both short calibration and formal runs.
    assert len(pos) == n_fluid and pos.shape == (n_fluid, 1, 3)
    assert vel.shape == (n_fluid, 1, 3) and c.shape == (n_fluid, 1)
    assert final_nan == 0 and max_nan == 0, "NaN/Inf found during presettle"
    assert leak_c < 0.01 and leak_m < 0.01, "final vessel escape fraction must be <1%"
    assert max_leak_c < 0.01 and max_leak_m < 0.01, "transient vessel escape fraction must be <1%"
    assert final_c_drift < 0.01 and max_c_drift < 0.01, "concentration is not conserved"
    assert c_phase_error < 1e-6, "zero-diffusion coffee/milk concentrations changed"
    assert final_ball_err < 5e-7, "static presettle vessel balls drifted"
    assert collision_overlap + collision_swept > 0, "boundary-ball collision path was not exercised"

    if args.calibration:
        print("CALIBRATION PASS (canonical settled file intentionally not written)")
        return

    assert BAND_C[0] <= fill_c <= BAND_C[1], f"coffee fill {fill_c:.4f} outside {BAND_C}"
    assert BAND_M[0] <= fill_m <= BAND_M[1], f"milk fill {fill_m:.4f} outside {BAND_M}"
    assert ke_ok and fc_ok and fm_ok, "final window still has an upward KE/level trend"
    assert tail_level_span_c < 0.05 and tail_level_span_m < 0.05, "final fill level is not settled"

    VIDEOS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = VIDEOS_DIR / "mf16_settled.npz"
    np.savez(
        out_path,
        pos=pos,
        vel=vel,
        c=c,
        n_coffee=np.int64(n_coffee),
        n_milk=np.int64(n_milk),
        base_n_coffee=np.int64(BASE_N_COFFEE),
        added_coffee=np.int64(added_coffee),
        base_n_milk=np.int64(BASE_N_MILK),
        added_milk=np.int64(added_milk),
        n_fluid=np.int64(n_fluid),
        ps=np.float64(PS),
        coffee_r=np.float64(R_C_SAMPLE),
        coffee_h0=np.float64(args.h_c0),
        milk_r=np.float64(R_M_SAMPLE),
        milk_h0=np.float64(args.h_m0),
        k_z=np.float64(args.kz),
        dens_iters=np.int64(args.dens_iters),
        leps=np.float64(args.leps),
        density_lambda_epsilon=np.float64(args.leps),
        st_comp=np.float64(args.st_comp),
        st_compliance=np.float64(args.st_comp),
        velocity_damping=np.float64(args.vdamp),
        dt=np.float64(DT),
        substeps=np.int64(args.substeps),
        seconds=np.float64(args.seconds),
        mug_ball_count=np.int64(len(mug_local)),
        jug_ball_count=np.int64(len(jug_local)),
        mug_pos=MUG_POS,
        jug_pos=JUG_POS,
        jug_quat=IDENTITY_QUAT,
    )
    with np.load(out_path) as saved:
        for key in ("pos", "vel", "c"):
            assert saved[key].shape[0] == n_fluid, f"{key} accidentally contains boundary balls"
        assert int(saved["n_fluid"]) == n_fluid
    print(f"saved fluid-only state: {out_path} pos={pos.shape} vel={vel.shape} c={c.shape}")
    print("FORMAL PRESSETTLE PASS")


if __name__ == "__main__":
    main()
