"""MF-16 H smoke: pour milk from a handled jug into a handled mug, grow a surface-tension
dome, then overflow down the visible outer wall onto the table.

Narrative (all times CLI-tunable; ``--smoke`` installs the strict 20 s schedule): settled rest,
vertical lift, approach while tilting to 72 degrees, controlled fill, a 78-degree dome hold,
an independent 112-degree overfill pulse, then collision-checked return/park and settling.

Both vessels use MF-16 boundary-ball assets generated by ``mf16_balls.py`` from the same geometry
dictionaries as their visible OBJ meshes: set 0 is the static mug and set 1 is the kinematic jug.
The jug collision set and visible mesh receive exactly the same pure pose function every frame.
The analytic table plane is retained.  Solver snapshots remain entity-only; loading the G state
changes only the coffee/milk entity prefix and explicitly proves the solver-owned ball rows,
flags and poses are unchanged.

Per-frame CSV: multiflow/videos/mf16_smoke_metrics.csv
  The historical ``z_surf_p99`` column is retained for file compatibility, but it is not a
  particle p99: it is the coherent slow-column top-centre 75th percentile.  New files append
  the correctly named duplicate ``z_surf_coherent_p75``.
Videos: multiflow/videos/mf16_smoke_main.mp4 + mf16_smoke_closeup.mp4

Run the mandatory load/pose check before the 20 s smoke:
  python multiflow/scripts/mf16_pour_overflow.py --load-pose-smoke --no-video
  python multiflow/scripts/mf16_pour_overflow.py --smoke

Acceptance is strict: no NaN, concentration drift <1%, phase-A container leakage <1%, the
72-degree jug pose really clears the rim, mug/jug wall-or-bottom tunnel histories remain zero,
the above-rim dome lasts at least 2 s, all three overflow signals pass, and frame p95 <1 s.
"""

import argparse
import csv
import json
import os
import sys
import time

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # multiflow/
sys.path.insert(0, os.path.join(WORKSPACE, "genesis-world"))

import numpy as np  # noqa: E402
from scipy.spatial import cKDTree  # noqa: E402

import genesis as gs  # noqa: E402

print("genesis loaded from:", gs.__file__)
assert os.path.normpath(gs.__file__).startswith(os.path.normpath(WORKSPACE)), "Wrong genesis! Must be the multiflow copy."

MUG_OBJ = os.path.join(WORKSPACE, "assets", "mug.obj")
JUG_OBJ = os.path.join(WORKSPACE, "assets", "jug.obj")
MUG_NPZ = os.path.join(WORKSPACE, "videos", "mf16_balls_mug.npz")
JUG_NPZ = os.path.join(WORKSPACE, "videos", "mf16_balls_jug.npz")
VIDEOS_DIR = os.path.join(WORKSPACE, "videos")
CSV_PATH = os.path.join(VIDEOS_DIR, "mf16_smoke_metrics.csv")
MP4_MAIN = os.path.join(VIDEOS_DIR, "mf16_smoke_main.mp4")
MP4_CLOSEUP = os.path.join(VIDEOS_DIR, "mf16_smoke_closeup.mp4")
MP4_TOP = os.path.join(VIDEOS_DIR, "mf16_smoke_top.mp4")

DT = 1.0 / 60.0
SUBSTEPS = 8

# Local origin of both ball/OBJ assets is the outer-bottom centre.
R_IN = 0.15
L_MUG = 0.30
T_WALL = 0.016
T_BOTTOM = 0.016
R_OUT = R_IN + T_WALL  # 0.166
Z_FLOOR = T_BOTTOM  # 0.016 cavity floor (= boundary z_bot; the outer bottom sits at z=0)
Z_RIM = Z_FLOOR + L_MUG  # 0.316
Z_TABLE = 0.0
LOWER_BOUND = np.array((-0.35, -0.35, 0.0), dtype=np.float32)
UPPER_BOUND = np.array((0.88, 0.35, 0.80), dtype=np.float32)

# Jug geometry comes from the same MF-16 dictionary used to generate JUG_NPZ and JUG_OBJ.
R_JUG = 0.125
L_JUG = 0.30
T_JUG_WALL = 0.016
T_JUG_BOTTOM = 0.016
IDENTITY_QUAT = np.array([1.0, 0.0, 0.0, 0.0], dtype=np.float32)

# jug placement and timeline defaults. The upright rest pose (PX, PZ) is what the presettle npz
# is bound to; the pour stance is defined by the lip PIVOT the jug rotates about. A pivot
# hovering inside/above the mug mouth keeps the stream landing in the cup - a pivot far outside
# it with a slow tilt lets the milk wrap the lip and run down the outer wall (teapot effect).
PX, PZ = 0.42, 0.0  # origin_0: outer bottom standing on the table
PIVOT_X, PIVOT_Z = 0.09, 0.38
PARK_X = 0.65  # return trajectory keeps the actual mug/jug ball sets disjoint
T_LIFT0, T_LIFT1 = 5.0, 7.0  # phase B: pure vertical lift
T_TILT0, T_TILT1 = 7.0, 11.0  # phase C: approach + descent + tilt together
T_TRICKLE = 26.0  # phase D holds until here, then theta -> trickle
TRICKLE_RAMP = 1.5  # seconds to reach the drain angle; hold there until T_BACK
T_DOME_STOP = 30.0  # stop the incoming stream before judging the held dome
STOP_RAMP = 1.0
STOP_RETREAT_X = 0.04
STOP_LIFT_Z = 0.02
T_OVERFILL = 34.0  # independent final pulse begins here
OVERFILL_RAMP = 0.75
T_BACK = 34.0  # phase E ends here; return to upright starts here
T_PARK0, T_PARK1 = 42.0, 46.0  # phase F ends / phase G glide aside
TILT_MAX_DEG = 72.0
TILT_TRICKLE_DEG = 86.0
TILT_DOME_HOLD_DEG = 65.0
TILT_OVERFILL_DEG = 86.0
DUR = 52.0

PS_FULL = 0.008
R_COFFEE = 0.14
H_COFFEE = 0.20
S0 = 0.002  # sample margin above the cavity floor
FIRST_OVER_STREAK = 8  # frames (0.133 s) of sustained n_over_rim >= 5 before first_over_t is
                       # recorded: single-frame hits are load-blast droplets and pour splash
T_FIRST_OVER_MIN = 2.5  # the load-blast splash rain dies by t~2 (KE floor); nothing before this
                        # counts as overflow, whatever n_over_rim says

# A mug particle is not legally overflowed merely because it rises through the horizontal rim
# plane: the centre of a connected dome does exactly that.  Legal overflow is a two-stage path.
# First the particle path must reach a fixed annulus adjacent to the *inner* lip at rim height;
# then it must cross outward beyond the outer wall while still at rim height.  Requiring the
# z-plane crossing itself to occur in the annulus is too strict: a genuine central cap can rise
# first and only later spread radially to the lip.  The 2 ps inner band is geometric (one PBD
# support radius plus one particle radius), fixed before any run.
MUG_RIM_PATH_R_MIN_PS = 1.75  # R_IN - 1.75 ps = 0.136 m
MUG_RIM_PATH_R_MAX_PS = 0.5
MUG_OUTER_CLEAR_PS = 0.5
MUG_OUTER_CLEAR_Z_PS = 0.5  # centre must be >= Z_RIM + 0.5 ps = 0.320 m

def smoothstep(u):
    u = min(max(u, 0.0), 1.0)
    return u * u * (3.0 - 2.0 * u)


def _ramp(t, t0, t1):
    return smoothstep((t - t0) / max(t1 - t0, 1e-9))


def quat_roty_neg(theta):
    """Quaternion (w, x, y, z) of rotY(-theta): maps the mesh local +z to the jug axis."""
    return np.array([np.cos(theta / 2.0), 0.0, -np.sin(theta / 2.0), 0.0])


def jug_origin_p():
    return np.array([PIVOT_X + R_JUG, 0.0, PIVOT_Z - Z_RIM])


def jug_park():
    return np.array([PARK_X, 0.0, PZ])


def jug_theta(t):
    """Jug tilt: main pour -> fill -> stream stop/dome hold -> overfill -> upright.

    The return to upright shares the glide window [T_BACK, T_PARK1] with the park translation:
    coming upright while still at the pour stance puts the jug's outer wall through the mug rim.
    """
    th_max = np.deg2rad(TILT_MAX_DEG)
    th_tr = np.deg2rad(TILT_TRICKLE_DEG)
    th_hold = np.deg2rad(TILT_DOME_HOLD_DEG)
    if t < T_TILT0:
        return 0.0
    if t < T_TILT1:
        return th_max * _ramp(t, T_TILT0, T_TILT1)
    if t < T_TRICKLE:
        return th_max
    if t < T_DOME_STOP:
        # Reach the drain angle promptly, then hold it long enough for the jug to empty.
        # Stretching this ramp over the whole phase left a large, silent volume in the jug.
        return th_max + (th_tr - th_max) * _ramp(
            t, T_TRICKLE, min(T_TRICKLE + TRICKLE_RAMP, T_DOME_STOP)
        )
    if t < T_OVERFILL:
        # Explicitly retreat below the pouring angle and hold.  Dome evidence is only accepted
        # after the jug census has stabilized, so the incoming stream cannot create the apex.
        angle_start = T_DOME_STOP + 0.5 * STOP_RAMP
        return th_tr + (th_hold - th_tr) * _ramp(
            t, angle_start, min(T_DOME_STOP + STOP_RAMP, T_OVERFILL)
        )
    th_over = np.deg2rad(TILT_OVERFILL_DEG)
    if t < T_BACK:
        return th_hold + (th_over - th_hold) * _ramp(
            t, T_OVERFILL, min(T_OVERFILL + OVERFILL_RAMP, T_BACK)
        )
    return th_over * (1.0 - _ramp(t, T_BACK, T_PARK1))


def jug_pose(t):
    """One pure source of truth for jug translation, quaternion, axis, angle and tilt blend.

    Pure function of t. Phase B is a pure vertical lift to the pivot height, so the upright
    body clears the mug rim before the approach starts; phase C combines the approach, the
    descent and the tilt on one smoothstep, so the jug arrives at the pour stance already at
    tilt-max and no upright pose hangs over the mug. D onward rotates about the pour-side lip
    pivot PIVOT = (pivot_x, 0, pivot_z) - the pour-side lip point of the pour stance
    (origin_p + L*a0 - R_JUG*e1 with a0 = +z, e1 = +x) - which stays fixed in the world while
    the body tilts. The theta return and the park glide share [T_BACK, T_PARK1]: coming upright
    while still over the mug would sink the jug wall into the mug rim.
    """
    th = jug_theta(t)
    a = np.array([-np.sin(th), 0.0, np.cos(th)])  # bottom -> mouth
    e1 = np.array([np.cos(th), 0.0, np.sin(th)])  # in-plane, toward the pour side
    origin_0 = np.array([PX, 0.0, PZ])
    lift_top = np.array([PX, 0.0, PIVOT_Z - T_JUG_BOTTOM])
    origin_p = jug_origin_p()
    pivot = np.array([PIVOT_X, 0.0, PIVOT_Z])
    rot = (pivot - Z_RIM * a + R_JUG * e1) - origin_p  # vanishes at theta = 0
    u_lift = _ramp(t, T_LIFT0, T_LIFT1)
    u_tilt = _ramp(t, T_TILT0, T_TILT1)
    u_park = _ramp(t, T_BACK, T_PARK1)
    # Stop sequence: first lift/retreat the still-78-degree jug away from the mug, then reduce
    # its angle.  During the independent overfill pulse the offset is smoothly removed.  This
    # ordering is required by the actual ball-set clearance check; a fixed-pivot 65-degree pose
    # intersects the mug rim.
    stop_mid = T_DOME_STOP + 0.5 * STOP_RAMP
    if t < T_DOME_STOP:
        u_stop = 0.0
    elif t < stop_mid:
        u_stop = _ramp(t, T_DOME_STOP, stop_mid)
    elif t < T_OVERFILL:
        u_stop = 1.0
    elif t < T_OVERFILL + OVERFILL_RAMP:
        u_stop = 1.0 - _ramp(t, T_OVERFILL, T_OVERFILL + OVERFILL_RAMP)
    else:
        u_stop = 0.0
    origin = (origin_0
              + u_lift * (lift_top - origin_0)
              + u_tilt * (origin_p - lift_top)
              + rot
              + u_stop * np.array([STOP_RETREAT_X, 0.0, STOP_LIFT_Z])
              + u_park * (jug_park() - origin_p))
    quat = quat_roty_neg(th).astype(np.float32)
    return origin.astype(np.float32), quat, a.astype(np.float32), th, u_tilt


def transform_points(local, pos, quat):
    """Rigidly transform local rows using a normalized (w,x,y,z) quaternion."""
    q = np.asarray(quat, dtype=np.float64)
    q /= np.linalg.norm(q)
    w, x, y, z = q
    rot = np.array(
        [[1 - 2 * (y*y + z*z), 2 * (x*y - z*w), 2 * (x*z + y*w)],
         [2 * (x*y + z*w), 1 - 2 * (x*x + z*z), 2 * (y*z - x*w)],
         [2 * (x*z - y*w), 2 * (y*z + x*w), 1 - 2 * (x*x + y*y)]],
        dtype=np.float64,
    )
    return np.asarray(local, dtype=np.float64) @ rot.T + np.asarray(pos, dtype=np.float64)


def inverse_transform_points(world, pos, quat):
    """World rows to the local frame of ``(pos, quat)``."""
    q = np.asarray(quat, dtype=np.float64)
    q /= np.linalg.norm(q)
    w, x, y, z = q
    rot = np.array(
        [[1 - 2 * (y*y + z*z), 2 * (x*y - z*w), 2 * (x*z + y*w)],
         [2 * (x*y + z*w), 1 - 2 * (x*x + z*z), 2 * (y*z - x*w)],
         [2 * (x*z - y*w), 2 * (y*z + x*w), 1 - 2 * (x*x + y*y)]],
        dtype=np.float64,
    )
    return (np.asarray(world, dtype=np.float64) - np.asarray(pos, dtype=np.float64)) @ rot


def segment_outward_cylinder_crossing(prev, cur, radius):
    """Exact segment intersection with an infinite z-cylinder for inside->outside paths.

    Returns ``(crossed, u, z)`` arrays.  Radial linear interpolation is not exact because the
    radius is a norm; the positive quadratic root is the first outward intersection when the
    segment starts inside and ends outside.
    """
    p = np.asarray(prev, dtype=np.float64)
    q = np.asarray(cur, dtype=np.float64)
    dxy = q[:, :2] - p[:, :2]
    a = np.einsum("ij,ij->i", dxy, dxy)
    b = 2.0 * np.einsum("ij,ij->i", p[:, :2], dxy)
    c = np.einsum("ij,ij->i", p[:, :2], p[:, :2]) - radius * radius
    pr = np.linalg.norm(p[:, :2], axis=1)
    qr = np.linalg.norm(q[:, :2], axis=1)
    crossed = (pr < radius) & (qr >= radius) & (a > 1e-20)
    disc = np.maximum(b * b - 4.0 * a * c, 0.0)
    u = np.zeros(len(p), dtype=np.float64)
    u[crossed] = (-b[crossed] + np.sqrt(disc[crossed])) / (2.0 * a[crossed])
    crossed &= (u >= 0.0) & (u <= 1.0)
    z = p[:, 2] + np.clip(u, 0.0, 1.0) * (q[:, 2] - p[:, 2])
    return crossed, u, z


def segment_inward_cylinder_crossing(prev, cur, radius):
    """Exact outside->inside cylinder intersection, expressed in prev->cur parameterization."""
    crossed_rev, u_rev, z = segment_outward_cylinder_crossing(cur, prev, radius)
    return crossed_rev, 1.0 - u_rev, z


def segment_downward_plane_crossing(prev, cur, z_plane):
    """Exact segment crossing of a horizontal plane in the downward direction."""
    p = np.asarray(prev, dtype=np.float64)
    q = np.asarray(cur, dtype=np.float64)
    crossed = (p[:, 2] >= z_plane) & (q[:, 2] < z_plane)
    u = np.zeros(len(p), dtype=np.float64)
    dz = q[:, 2] - p[:, 2]
    good = crossed & (np.abs(dz) > 1e-20)
    u[good] = (z_plane - p[good, 2]) / dz[good]
    point = p + np.clip(u, 0.0, 1.0)[:, None] * (q - p)
    return crossed & good & (u >= 0.0) & (u <= 1.0), u, point


def load_ball_asset(path, body, kinematic):
    with np.load(path) as data:
        local = np.asarray(data["pos_local"], dtype=np.float32)
        meta = json.loads(str(data["meta"].item()))
    assert meta["body"] == body and bool(meta["kinematic"]) is kinematic
    assert local.ndim == 2 and local.shape[1] == 3 and np.isfinite(local).all()
    assert "mf16_balls.py shared dictionaries" in meta["geometry"]["source"]
    if body == "jug":
        assert float(meta["geometry"]["spout"]["center_deg"]) == 180.0
        assert float(meta["geometry"]["spout"]["spout_half_deg"]) == 20.0
        assert float(meta["geometry"]["spout"]["spout_dz"]) == -0.002
        assert float(meta["geometry"]["spout"]["spout_dr"]) == 0.030
        assert float(meta["geometry"]["side"]) == 1.0
    return local, meta


def assert_timeline_contract(mug_local, jug_local, t1):
    """Use the actual ball assets to prove hash containment and no vessel interpenetration."""
    mug_tree = cKDTree(np.asarray(mug_local, dtype=np.float64))
    min_dist, min_t = float("inf"), 0.0
    for t in np.linspace(0.0, t1, max(int(round(t1 / 0.05)) + 1, 2)):
        pos, quat, _, _, _ = jug_pose(float(t))
        world = transform_points(jug_local, pos, quat)
        lo, hi = world.min(axis=0), world.max(axis=0)
        assert np.all(lo >= LOWER_BOUND - 1e-7), (t, lo)
        assert np.all(hi < UPPER_BOUND), (t, hi)
        d = float(mug_tree.query(world, k=1, workers=-1)[0].min())
        if d < min_dist:
            min_dist, min_t = d, float(t)
    assert min_dist >= PS_FULL - 1e-6, (
        f"vessel ball sets interpenetrate: min centre distance {min_dist:.6f} at t={min_t:.3f}"
    )
    print(f"timeline asset contract: hash envelope PASS; min mug/jug ball distance "
          f"{min_dist:.6f} at t={min_t:.3f}s")


def coherent_mug_surface(pos, vel, bulk_mask, ps):
    """Return a broad, locally supported free-surface height and coherent dome count.

    A particle percentile is easily fooled by the incoming jet.  Here the surface is sampled
    once per 1.5-particle 2-D column over the mug core, only from slow particles that still
    belong to the mug bulk.  Each column top must have a genuine 3-D local neighbourhood, and
    the reported height is the 75th percentile across columns.  A narrow jet or a few droplets
    can therefore occupy some columns, but cannot masquerade as a cup-wide convex surface.
    """
    core_r = R_IN - 2.0 * ps
    speed = np.linalg.norm(vel, axis=1)
    r = np.linalg.norm(pos[:, :2], axis=1)
    eligible = bulk_mask & (r <= core_r) & (speed <= 0.2)
    idx = np.flatnonzero(eligible)
    if idx.size < 32:
        return float("nan"), 0

    cell = 1.5 * ps
    nxy = int(np.ceil(2.0 * core_r / cell)) + 1
    ij = np.floor((pos[idx, :2] + core_r) / cell).astype(np.int32)
    keys = ij[:, 0].astype(np.int64) * nxy + ij[:, 1]
    order = np.lexsort((pos[idx, 2], keys))
    sorted_idx, sorted_keys = idx[order], keys[order]
    starts = np.r_[0, 1 + np.flatnonzero(sorted_keys[1:] != sorted_keys[:-1])]
    ends = np.r_[starts[1:], sorted_idx.size]
    # Require several slow particles in a vertical column, then take its highest one.  The
    # subsequent spherical-neighbour test rejects an isolated top particle.
    tops = np.asarray([sorted_idx[e - 1] for s, e in zip(starts, ends) if e - s >= 4], dtype=np.int64)
    if tops.size < 24:
        return float("nan"), 0
    bulk_idx = np.flatnonzero(bulk_mask)
    tree = cKDTree(np.asarray(pos[bulk_idx], dtype=np.float64))
    n_local = tree.query_ball_point(
        np.asarray(pos[tops], dtype=np.float64), r=1.75 * ps, return_length=True, workers=-1
    )
    tops = tops[np.asarray(n_local) >= 6]
    if tops.size < 24:
        return float("nan"), 0
    top_z = pos[tops, 2]
    z_surface = float(np.percentile(top_z, 75.0))
    n_dome = int(np.count_nonzero(top_z >= Z_RIM + 0.5 * ps))
    return z_surface, n_dome


def phase_of(t):
    if t < T_LIFT0:
        return 0  # A rest
    if t < T_TILT0:
        return 1  # B lift
    if t < T_TILT1:
        return 2  # C tilt up
    if t < T_TRICKLE:
        return 3  # D pour at tilt-max
    if t < T_BACK:
        return 4  # E trickle + dome
    return 5 if t < T_PARK1 else 6  # F overflow + return/glide, G settle


def longest_true_run(mask):
    """Length (frames) of the longest run of True in a 1-D bool array."""
    best = cur = 0
    for v in mask:
        cur = cur + 1 if v else 0
        best = max(best, cur)
    return best


def best_window_frac(t_arr, ok, win_dur):
    """Max over start frames of the fraction of `ok` inside the ~`win_dur` window from it."""
    n = len(t_arr)
    if n == 0:
        return 0.0, 0, 0
    best_frac, bi, bj = 0.0, 0, 0
    j = 0
    csum = np.concatenate([[0], np.cumsum(ok.astype(np.int64))])
    for i in range(n):
        while j + 1 < n and t_arr[j + 1] - t_arr[i] <= win_dur + 0.5 * DT:
            j += 1
        if t_arr[j] - t_arr[i] >= win_dur:
            frac = (csum[j + 1] - csum[i]) / (j + 1 - i)
            if frac > best_frac:
                best_frac, bi, bj = frac, i, j
    return best_frac, bi, bj


def main():
    global PX, PZ, PARK_X, PIVOT_X, PIVOT_Z, T_LIFT0, T_LIFT1, T_TILT0, T_TILT1
    global T_TRICKLE, TRICKLE_RAMP, T_DOME_STOP, STOP_RAMP, STOP_RETREAT_X, STOP_LIFT_Z
    global T_OVERFILL, OVERFILL_RAMP
    global T_BACK, T_PARK0, T_PARK1
    global TILT_MAX_DEG, TILT_TRICKLE_DEG, TILT_DOME_HOLD_DEG, TILT_OVERFILL_DEG, DUR

    parser = argparse.ArgumentParser()
    parser.add_argument("--dur", type=float, default=52.0, help="recorded seconds outside smoke modes")
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--substeps", type=int, default=SUBSTEPS,
                        help="physics substeps per 1/60 s frame (default 8; use 16 for half dt_sub)")
    parser.add_argument("--no-video", action="store_true")
    parser.add_argument("--output-tag", type=str, default="",
                        help="optional basename for diagnostic CSV/dumps/videos; keeps canonical smoke outputs intact")
    parser.add_argument("--smooth-a2", action="store_true",
                        help="opt in to the same-source smooth mug barrel/rim narrow phase")
    parser.add_argument("--jug-hist", action="store_true",
                        help="opt in to the solver-owned jug exit history (rim staging / direct "
                             "tunnel, spout-aware); independent of --smooth-a2")
    parser.add_argument("--settled", type=str,
                        default=os.path.join(VIDEOS_DIR, "mf16_settled.npz"),
                        help="fluid-only state from mf16_presettle.py")
    parser.add_argument(
        "--smoke", action="store_true",
        help="20 s H smoke: 72/78-degree fill, 65-degree stream stop, 112-degree overfill pulse",
    )
    parser.add_argument("--load-pose-smoke", action="store_true",
                        help="2 s state-load and full-pose API smoke; no narrative acceptance")
    parser.add_argument("--st-comp", type=float, default=0.7, help="MF-15 verified st_compliance")
    parser.add_argument("--diffusion", type=float, default=0.01)
    parser.add_argument("--adh-comp", type=float, default=20.0, help="wall_adhesion_compliance (smaller = stickier)")
    parser.add_argument("--adh", action=argparse.BooleanOptionalAction, default=True,
                        help="enable wall adhesion; --no-adh keeps ST on and forces wall friction to zero")
    parser.add_argument("--wfric", type=float, default=0.01,
                        help="wall_friction: tangential damping for adhering particles (resists the "
                             "mercury-bead contraction of the table puddle; needs adhesion on)")
    parser.add_argument("--tilt-max", type=float, default=TILT_MAX_DEG)
    parser.add_argument("--tilt-trickle", type=float, default=TILT_TRICKLE_DEG)
    parser.add_argument("--t-lift0", type=float, default=T_LIFT0)
    parser.add_argument("--t-lift1", type=float, default=T_LIFT1)
    parser.add_argument("--t-tilt0", type=float, default=T_TILT0)
    parser.add_argument("--t-tilt1", type=float, default=T_TILT1)
    parser.add_argument("--t-trickle", type=float, default=T_TRICKLE)
    parser.add_argument("--trickle-ramp", type=float, default=TRICKLE_RAMP,
                        help="seconds for tilt-max -> tilt-trickle; held until t-dome-stop")
    parser.add_argument("--t-dome-stop", type=float, default=T_DOME_STOP,
                        help="start retreat from the fill angle to stop the incoming stream")
    parser.add_argument("--stop-ramp", type=float, default=STOP_RAMP,
                        help="seconds for tilt-trickle -> tilt-dome-hold")
    parser.add_argument("--tilt-dome-hold", type=float, default=TILT_DOME_HOLD_DEG,
                        help="sub-pour angle held while the stream-free dome is audited")
    parser.add_argument("--stop-retreat-x", type=float, default=STOP_RETREAT_X,
                        help="world +x retreat applied before lowering to the dome-hold angle")
    parser.add_argument("--stop-lift-z", type=float, default=STOP_LIFT_Z,
                        help="world +z lift applied before lowering to the dome-hold angle")
    parser.add_argument("--t-overfill", type=float, default=T_OVERFILL,
                        help="start time of the independent final overfill pulse")
    parser.add_argument("--overfill-ramp", type=float, default=OVERFILL_RAMP)
    parser.add_argument("--tilt-overfill", type=float, default=TILT_OVERFILL_DEG)
    parser.add_argument("--t-back", type=float, default=T_BACK)
    parser.add_argument("--t-park0", type=float, default=T_PARK0,
                        help="unused: the theta return and the glide share [t-back, t-park1] "
                             "(kept so old command lines still parse)")
    parser.add_argument("--t-park1", type=float, default=T_PARK1)
    parser.add_argument("--px", type=float, default=PX, help="upright jug axis x (rest pose, npz-bound)")
    parser.add_argument("--pz", type=float, default=PZ, help="upright jug outer-bottom z")
    parser.add_argument("--pivot-x", type=float, default=PIVOT_X,
                        help="pour-side lip pivot x the jug rotates about (inside the mug mouth -> clean pour)")
    parser.add_argument("--pivot-z", type=float, default=PIVOT_Z, help="pour-side lip pivot z")
    parser.add_argument("--park-x", type=float, default=PARK_X)
    parser.add_argument("--point-size", type=float, default=6.0,
                        help="main-camera particle sprite size in px (spacing there is ~8 px)")
    parser.add_argument("--point-size-cup", type=float, default=13.0,
                        help="closeup-camera particle sprite size in px (spacing there is ~28 px)")
    parser.add_argument("--cam-top", action=argparse.BooleanOptionalAction, default=False,
                        help="add a straight-down diagnostic camera on the pour column")
    parser.add_argument("--dump-slabs", type=str, default="",
                        help="comma-separated times: dump the milk particles in the stream slab "
                             "z=[0.315,0.345] (mug rim -> jug lip) at the nearest frame of each, "
                             "with per-time N/centroid/eigenvalues/ellipticity/effective diameter")
    parser.add_argument("--dump-frames", type=str, default="",
                        help="comma-separated times: full pos+c+pose snapshots at the nearest "
                             "frame, saved to videos/mf16_smoke_dumps.npz")
    parser.add_argument("--warmup", type=int, default=None,
                        help="off-camera re-settle frames before the first recorded frame: the "
                             "settled lattice is radially inhomogeneous, so the first substeps "
                             "drag wall-layer particles into the gaps and the mug surface "
                             "collapses briefly; 0 disables (default 0 for MF-16 settled state)")
    args = parser.parse_args()

    if args.output_tag and (os.path.basename(args.output_tag) != args.output_tag
                            or any(ch not in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-" for ch in args.output_tag)):
        raise SystemExit("--output-tag must be a plain [A-Za-z0-9_-] basename")
    csv_path = CSV_PATH if not args.output_tag else os.path.join(VIDEOS_DIR, f"{args.output_tag}_metrics.csv")
    mp4_main = MP4_MAIN if not args.output_tag else os.path.join(VIDEOS_DIR, f"{args.output_tag}_main.mp4")
    mp4_closeup = MP4_CLOSEUP if not args.output_tag else os.path.join(VIDEOS_DIR, f"{args.output_tag}_closeup.mp4")
    mp4_top = MP4_TOP if not args.output_tag else os.path.join(VIDEOS_DIR, f"{args.output_tag}_top.mp4")
    dump_path = os.path.join(VIDEOS_DIR, "mf16_smoke_dumps.npz" if not args.output_tag else f"{args.output_tag}_dumps.npz")
    slab_path = os.path.join(VIDEOS_DIR, "mf16_smoke_stream_slab.npz" if not args.output_tag else f"{args.output_tag}_stream_slab.npz")
    event_path = os.path.join(VIDEOS_DIR, "mf16_smoke_tunnel_events.csv" if not args.output_tag else f"{args.output_tag}_tunnel_events.csv")

    PX, PZ, PARK_X = args.px, args.pz, args.park_x
    PIVOT_X, PIVOT_Z = args.pivot_x, args.pivot_z
    TILT_MAX_DEG, TILT_TRICKLE_DEG = args.tilt_max, args.tilt_trickle
    TILT_OVERFILL_DEG = args.tilt_overfill
    T_LIFT0, T_LIFT1 = args.t_lift0, args.t_lift1
    T_TILT0, T_TILT1 = args.t_tilt0, args.t_tilt1
    T_TRICKLE, TRICKLE_RAMP = args.t_trickle, args.trickle_ramp
    T_DOME_STOP, STOP_RAMP = args.t_dome_stop, args.stop_ramp
    TILT_DOME_HOLD_DEG = args.tilt_dome_hold
    STOP_RETREAT_X, STOP_LIFT_Z = args.stop_retreat_x, args.stop_lift_z
    T_OVERFILL, OVERFILL_RAMP, T_BACK = args.t_overfill, args.overfill_ramp, args.t_back
    T_PARK0, T_PARK1 = args.t_park0, args.t_park1
    DUR = args.dur
    if args.smoke:
        DUR = 20.0
        T_LIFT0, T_LIFT1 = 2.0, 3.5
        T_TILT0, T_TILT1 = 3.5, 6.0
        # Controlled prefill creates a broad, low-speed surface before an independent pulse
        # expels the reserved milk.  The two stages prevent the incoming jet from serving as
        # the alleged dome and give the coherent-surface metric a genuine hold interval.
        T_TRICKLE, TRICKLE_RAMP = 8.0, 1.0
        T_DOME_STOP, STOP_RAMP = 11.0, 1.0
        STOP_RETREAT_X, STOP_LIFT_Z = 0.04, 0.02
        T_OVERFILL, OVERFILL_RAMP = 14.25, 0.75
        T_BACK, T_PARK0, T_PARK1 = 17.5, 17.5, 19.0
        TILT_MAX_DEG, TILT_TRICKLE_DEG = 72.0, 78.0
        TILT_DOME_HOLD_DEG, TILT_OVERFILL_DEG = 65.0, 112.0
        PIVOT_X, PIVOT_Z = 0.09, 0.38
    if args.load_pose_smoke:
        DUR = 2.0
        T_LIFT0, T_LIFT1 = 0.20, 0.55
        T_TILT0, T_TILT1 = 0.55, 1.50
        T_TRICKLE = T_DOME_STOP = T_OVERFILL = T_BACK = T_PARK0 = T_PARK1 = DUR + 5.0
        TILT_MAX_DEG = TILT_TRICKLE_DEG = TILT_DOME_HOLD_DEG = TILT_OVERFILL_DEG = 72.0
        PIVOT_X = 0.09
        args.no_video = True
    if args.warmup is None:
        args.warmup = 0
    if args.substeps < 1:
        raise SystemExit("--substeps must be >= 1")
    wall_friction = args.wfric if args.adh else 0.0
    ps = PS_FULL

    # ---- settled state: fail BEFORE the engine is initialized ----------------------------
    if not os.path.isfile(args.settled):
        raise SystemExit(f"settled npz not found: {args.settled} - run mf16_presettle.py first")
    dat = np.load(args.settled)
    need = ["pos", "vel", "c", "n_coffee", "n_milk", "coffee_r", "coffee_h0", "milk_r", "milk_h0"]
    missing = [k for k in need if k not in dat.files]
    if missing:
        raise SystemExit(f"settled npz {args.settled} is missing keys {missing}")
    r_coffee, h_coffee = float(dat["coffee_r"]), float(dat["coffee_h0"])
    r_milk, h_milk = float(dat["milk_r"]), float(dat["milk_h0"])
    settled_pos = dat["pos"].astype(np.float32)
    settled_vel = dat["vel"].astype(np.float32)
    settled_c = dat["c"].astype(np.float32)

    mug_local, mug_meta = load_ball_asset(MUG_NPZ, "mug", False)
    jug_local, jug_meta = load_ball_asset(JUG_NPZ, "jug", True)
    mug_ball_tree = cKDTree(np.asarray(mug_local, dtype=np.float64))
    jug_ball_tree = cKDTree(np.asarray(jug_local, dtype=np.float64))
    with np.load(MUG_NPZ) as ball_data:
        mug_ball_face = ball_data["face"].astype(str)
        mug_ball_layer = ball_data["layer"].astype(np.int8)
    with np.load(JUG_NPZ) as ball_data:
        jug_ball_face = ball_data["face"].astype(str)
        jug_ball_layer = ball_data["layer"].astype(np.int8)

    origin_0 = np.array([PX, 0.0, PZ])
    mp4_paths = [] if args.no_video else [mp4_main, mp4_closeup]
    assert_timeline_contract(mug_local, jug_local, DUR)

    gs.init(backend=gs.gpu, precision="32", seed=0)
    # Solver-owned jug exit history (--jug-hist): geometry is same-source.  The spout
    # parameters come from the JUG_NPZ meta (asserted in load_ball_asset); the radii/heights
    # are the script's own jug geometry constants (jug local origin = outer-bottom centre).
    # boundary_ball_sets registers the mug first (static set 0) and the jug second
    # (kinematic set 1), so the jug history targets set_index 1.
    jug_hist_opt = None
    if args.jug_hist:
        jug_spout = jug_meta["geometry"]["spout"]
        jug_hist_opt = (
            1,                       # jug kinematic boundary-ball set (mug static set 0)
            R_JUG,                   # r_inner = 0.125
            R_JUG + T_JUG_WALL,      # r_outer = 0.141
            0.0,                     # jug local outer-bottom z
            Z_RIM,                   # visible rim z = 0.316
            np.deg2rad(float(jug_spout["center_deg"])),
            np.deg2rad(float(jug_spout["spout_half_deg"])),
            float(jug_spout["spout_dz"]),
            float(jug_spout["spout_dr"]),
            2e-4 * ps,               # hist_tol
        )
    scene = gs.Scene(
        sim_options=gs.options.SimOptions(dt=DT, substeps=args.substeps, gravity=(0.0, 0.0, -9.81)),
        coupler_options=gs.options.LegacyCouplerOptions(rigid_pbd=False),
        rigid_options=gs.options.RigidOptions(enable_collision=False, gravity=(0.0, 0.0, 0.0)),
        pbd_options=gs.options.PBDOptions(
            particle_size=ps,
            lower_bound=tuple(LOWER_BOUND),
            upper_bound=tuple(UPPER_BOUND),
            boundary_ball_sets=((MUG_NPZ, False), (JUG_NPZ, True)),
            boundary_ball_initial_poses=(
                ((0.0, 0.0, 0.0), tuple(IDENTITY_QUAT)),
                (tuple(origin_0), tuple(IDENTITY_QUAT)),
            ),
            boundary_ball_mass_weight_enabled=False,
            boundary_ball_smooth_barrel=(
                0, 0.0, 0.0, R_IN, R_OUT, 0.0, Z_RIM,
                np.pi, np.deg2rad(35.0), 0.08, 0.24, 0.002,
            ) if args.smooth_a2 else None,
            boundary_ball_jug_history=jug_hist_opt,
            boundary_plane=(Z_TABLE,),
            max_density_solver_iterations=20,
            max_viscosity_solver_iterations=1,
            density_lambda_epsilon=0.1,
            diffusion_coeff=args.diffusion,
            surface_tension_enabled=True,
            st_compliance=args.st_comp,
            st_surface_density_factor=1.0,
            st_distance_enabled=True,
            st_distance_compliance=40.0,
            st_max_surface_neighbors=256,
            velocity_damping=1.0,
            wall_adhesion_enabled=args.adh,
            wall_adhesion_compliance=args.adh_comp,
            wall_friction=wall_friction,
        ),
        vis_options=gs.options.VisOptions(
            render_particle_as="points",  # per-particle concentration coloring
        ),
        show_viewer=False,
    )

    # Visual vessels share the exact local frame and source dictionaries of the ball assets.
    mug = scene.add_entity(
        morph=gs.morphs.Mesh(
            file=MUG_OBJ,
            pos=(0.0, 0.0, 0.0),
            fixed=True,
            collision=False,
            decimate=False,
        ),
        material=gs.materials.Rigid(),
        surface=gs.surfaces.Default(color=(0.85, 0.85, 0.9, 0.35), opacity=0.35),
    )
    jug = scene.add_entity(
        morph=gs.morphs.Mesh(
            file=JUG_OBJ,
            pos=tuple(origin_0),
            euler=(0.0, 0.0, 0.0),
            fixed=True,
            collision=False,
            decimate=False,
        ),
        material=gs.materials.Rigid(),
        surface=gs.surfaces.Default(color=(0.9, 0.92, 0.95, 0.45), opacity=0.45),
    )
    # table visual: top face exactly at the PlaneBoundary height (mf14 convention); sized so the
    # splash (r p90 ~ 0.7) stays on the visible deck instead of hovering past its edge
    table = scene.add_entity(
        morph=gs.morphs.Box(size=(2.6, 1.6, 0.04), pos=(0.35, 0.0, Z_TABLE - 0.02), fixed=True),
        material=gs.materials.Rigid(),
        surface=gs.surfaces.Default(color=(0.55, 0.55, 0.58, 1.0), opacity=1.0),
    )

    coffee = scene.add_entity(
        material=gs.materials.PBD.Liquid(
            sampler="regular", rho=1000.0, c_init=1.0,
            density_relaxation=0.2, viscosity_relaxation=0.01,
        ),
        morph=gs.morphs.Cylinder(
            radius=r_coffee,
            height=h_coffee,
            pos=(0.0, 0.0, Z_FLOOR + S0 + 0.5 * h_coffee),
        ),
    )
    # The initial pose is already installed before build; no first-frame identity-to-park sweep.
    milk = scene.add_entity(
        material=gs.materials.PBD.Liquid(
            sampler="regular", rho=1000.0, c_init=0.0,
            density_relaxation=0.2, viscosity_relaxation=0.01,
        ),
        morph=gs.morphs.Cylinder(
            radius=r_milk,
            height=h_milk,
            pos=(PX, 0.0, PZ + Z_FLOOR + S0 + 0.5 * h_milk),
        ),
    )

    # front view (-y): the mug handle (-x side) reads on the left of frame and the jug (+x) on
    # the right - the old three-quarter view hid the handle behind the mug body
    camera_res = (480, 640) if args.smoke else (960, 1280)
    cam = scene.add_camera(res=camera_res, pos=(0.28, -1.42, 0.60), lookat=(0.22, 0.0, 0.20), fov=42, GUI=False)
    cam_close = scene.add_camera(res=camera_res, pos=(0.44, -0.40, 0.40), lookat=(0.06, 0.0, 0.29), fov=32, GUI=False)
    # straight-down diagnostic view of the pour column; the explicit horizontal up vector keeps
    # the look-at build non-degenerate for a -z view direction
    cam_top = None
    if args.cam_top:
        cam_top = scene.add_camera(res=camera_res, pos=(0.10, 0.02, 0.85), lookat=(0.10, 0.02, 0.25),
                                   up=(0.0, 1.0, 0.0), fov=50, GUI=False)
    scene.build()
    print(f"mug geoms: {mug.n_geoms}, jug geoms: {jug.n_geoms}, table geoms: {table.n_geoms}, "
          f"coffee particles: {coffee.n_particles}, milk particles: {milk.n_particles}")
    print(
        f"ps={ps} dt={DT:.5f} substeps={args.substeps} dt_sub={DT / args.substeps:.7f} "
        f"st_comp={args.st_comp:g} adh={args.adh} adh_comp={args.adh_comp:g} "
        f"wfric={wall_friction:g} diffusion={args.diffusion:g} "
        f"tilt_max={TILT_MAX_DEG:g} tilt_trickle={TILT_TRICKLE_DEG:g} "
        f"lift=({T_LIFT0:g},{T_LIFT1:g}) tilt=({T_TILT0:g},{T_TILT1:g}) "
        f"trickle={T_TRICKLE:g}+{TRICKLE_RAMP:g}s "
        f"stop={T_DOME_STOP:g}+{STOP_RAMP:g}s@{TILT_DOME_HOLD_DEG:g}deg "
        f"stop_offset=(+{STOP_RETREAT_X:g}x,+{STOP_LIFT_Z:g}z) "
        f"overfill={T_OVERFILL:g}+{OVERFILL_RAMP:g}s@{TILT_OVERFILL_DEG:g}deg "
        f"back={T_BACK:g} park=({T_PARK0:g},{T_PARK1:g}) dur={DUR:g} smoke={args.smoke} "
        f"cam_top={args.cam_top} slabs='{args.dump_slabs}' warmup={args.warmup} "
        f"smooth_a2={args.smooth_a2} jug_hist={args.jug_hist} "
        f"mass_weight=False output_tag='{args.output_tag}'"
    )
    print(f"jug: origin_0=({PX:g},0,{PZ:g}) pivot=({PIVOT_X:g},0,{PIVOT_Z:g}) "
          f"origin_p={np.round(jug_origin_p(), 3).tolist()} "
          f"park={np.round(jug_park(), 3).tolist()} | mug r_in={R_IN} rim z={Z_RIM:.3f} "
          f"| coffee r={r_coffee:.3f} h0={h_coffee:.3f} | milk r={r_milk:.3f} h0={h_milk:.3f}")

    # per-camera sprite size: the two viewpoints sit at very different distances, so one value
    # cannot close the gaps between particles in both frames
    scene.visualizer.rasterizer._camera_targets[cam.uid].point_size = args.point_size
    scene.visualizer.rasterizer._camera_targets[cam_close.uid].point_size = args.point_size_cup
    if cam_top is not None:
        scene.visualizer.rasterizer._camera_targets[cam_top.uid].point_size = 18.0

    solver = scene.sim.pbd_solver
    assert type(solver.boundary).__name__ == "CubeBoundary", f"unexpected boundary: {type(solver.boundary)}"
    assert type(solver.boundary3).__name__ == "PlaneBoundary", f"unexpected boundary3: {type(solver.boundary3)}"
    assert solver.boundary_ball_ranges == [
        (solver._n_entity_particles, solver._n_entity_particles + len(mug_local), False),
        (solver._n_entity_particles + len(mug_local), solver._n_entity_particles + len(mug_local) + len(jug_local), True),
    ]
    n_fluid = solver._n_entity_particles
    n_coffee = coffee.n_particles
    n_milk = milk.n_particles
    assert n_coffee + n_milk == n_fluid
    assert solver._boundary_ball_mass_weight_enabled is False
    assert solver._has_boundary_ball_smooth_barrel is args.smooth_a2
    assert solver._has_boundary_ball_jug_history is args.jug_hist
    os.makedirs(VIDEOS_DIR, exist_ok=True)

    # ---- initial state -------------------------------------------------------------------
    pos_np = solver.particles.pos.to_numpy()[:n_fluid, 0, :]
    assert settled_pos.shape == settled_vel.shape == (n_fluid, 1, 3)
    assert settled_c.shape == (n_fluid, 1)
    assert int(dat["n_coffee"]) == n_coffee and int(dat["n_milk"]) == n_milk
    assert int(dat["mug_ball_count"]) == len(mug_local)
    assert int(dat["jug_ball_count"]) == len(jug_local), "settled state predates current jug asset; rerun G"
    assert abs(float(dat["ps"]) - ps) < 1e-12

    # Prove that loading touches only the entity prefix.  Positions/velocities use entity APIs;
    # concentration has no entity setter, so only its prefix is changed in a preserved full copy.
    ball_slice = slice(n_fluid, n_fluid + solver.n_boundary_balls)
    ball_pos_before = solver.particles.pos.to_numpy()[ball_slice].copy()
    ball_active_before = solver.particles_ng.active.to_numpy()[ball_slice].copy()
    ball_boundary_before = solver.particles_ng.is_boundary.to_numpy()[ball_slice].copy()
    ball_free_before = solver.particles.free.to_numpy()[ball_slice].copy()
    pose_pos_before = solver._ball_set_pos.to_numpy().copy()
    pose_quat_before = solver._ball_set_quat.to_numpy().copy()
    coffee.set_particles_pos(settled_pos[:n_coffee, 0])
    milk.set_particles_pos(settled_pos[n_coffee:, 0])
    coffee.set_particles_vel(settled_vel[:n_coffee, 0])
    milk.set_particles_vel(settled_vel[n_coffee:, 0])
    c_full = solver.particles.c.to_numpy()
    c_ball_before = c_full[ball_slice].copy()
    c_full[:n_fluid] = settled_c
    solver.particles.c.from_numpy(c_full)
    # Scene.build executes throwaway compile steps on sampled entity state.  The loaded settled
    # snapshot deliberately contains no solver-owned collision history, so start it from false;
    # all A2 staging in this run must be earned by an accepted substep after the real state load.
    if args.smooth_a2:
        solver.reset_boundary_ball_smooth_barrel_history()
    # Same contract for the jug exit history (--jug-hist): the loaded settled snapshot contains
    # no solver-owned jug staging/direct state, so start it from false; all jug staging in this
    # run must be earned by an accepted substep after the real state load.
    if args.jug_hist:
        solver.reset_boundary_ball_jug_history()
    ball_pos_after = solver.particles.pos.to_numpy()[ball_slice]
    assert np.array_equal(ball_pos_after, ball_pos_before)
    assert np.array_equal(solver.particles_ng.active.to_numpy()[ball_slice], ball_active_before)
    assert np.array_equal(solver.particles_ng.is_boundary.to_numpy()[ball_slice], ball_boundary_before)
    assert np.array_equal(solver.particles.free.to_numpy()[ball_slice], ball_free_before)
    assert np.array_equal(solver.particles.c.to_numpy()[ball_slice], c_ball_before)
    assert np.array_equal(solver._ball_set_pos.to_numpy(), pose_pos_before)
    assert np.array_equal(solver._ball_set_quat.to_numpy(), pose_quat_before)
    assert bool(ball_active_before.all() and ball_boundary_before.all() and (~ball_free_before).all())
    expected_initial = np.concatenate((mug_local, transform_points(jug_local, origin_0, IDENTITY_QUAT)), axis=0)
    load_ball_err = float(np.max(np.abs(ball_pos_after[:, 0, :] - expected_initial)))
    assert load_ball_err < 5e-7
    print(f"loaded fluid-only settled state: pos/vel/c={n_fluid}; ball rows preserved exactly; "
          f"initial ball error={load_ball_err:.3e}")

    chk = solver.particles.pos.to_numpy()[:n_fluid, 0, :]
    r_c = np.linalg.norm(chk[:n_coffee, :2], axis=1)
    out_c = int(((r_c > R_IN + ps) | (chk[:n_coffee, 2] < Z_FLOOR - ps) |
                 (chk[:n_coffee, 2] > Z_RIM + ps)).sum())
    rel_m = chk[n_coffee:] - origin_0
    s_m = rel_m[:, 2]
    r_m = np.linalg.norm(rel_m[:, :2], axis=1)
    out_m = int(((r_m > R_JUG + ps) | (s_m < Z_FLOOR - ps) | (s_m > Z_RIM + ps)).sum())
    print(f"settled check: coffee outside mug={out_c}/{n_coffee}; milk outside jug={out_m}/{n_milk}")
    assert out_c < 0.01 * n_coffee and out_m < 0.01 * n_milk

    n_frames = int(round(DUR / DT))
    rows = []
    tunnel_event_records = []

    # ---- off-camera warm-up (mf14 resettle precedent) --------------------------------------
    # the settled lattice is radially inhomogeneous (an under-filled near-wall shell), so the
    # first substeps drag wall-layer particles into the gaps and the mug surface collapses
    # briefly; letting that happen before the first recorded frame keeps the shot clean. The
    # jug holds the phase-A pose; nothing is recorded and no CSV row is produced. The main
    # loop's t still counts from 0, so the t=2 stray clean-up simply fires one warm-up later
    # in physical time.
    if args.warmup > 0:
        origin, quat, _, _, _ = jug_pose(0.0)
        solver.set_boundary_ball_pose(1, origin, quat)
        jug.set_pos(origin, relative=True, zero_velocity=True)
        jug.set_quat(quat, relative=True, zero_velocity=True)

        def warm_stats():
            pos_np = solver.particles.pos.to_numpy()[:n_fluid, 0, :]
            vel_np = solver.particles.vel.to_numpy()[:n_fluid, 0, :]
            safe_np = np.nan_to_num(pos_np, nan=0.0, posinf=0.0, neginf=0.0)
            r_np = np.sqrt(safe_np[:, 0] ** 2 + safe_np[:, 1] ** 2)
            in_mug = (r_np <= R_IN + ps) & (safe_np[:, 2] >= Z_FLOOR - ps)
            z_s = float(np.percentile(safe_np[in_mug, 2], 99)) if in_mug.any() else float("nan")
            return z_s, float(0.5 * np.nansum((vel_np**2).sum(axis=1)))

        zs0, ke0 = warm_stats()
        for _ in range(args.warmup):
            scene.step()
        zs1, ke1 = warm_stats()
        print(f"warm-up {args.warmup} frames: z_surf {zs0:.3f} -> {zs1:.3f}, "
              f"KE {ke0:.3e} -> {ke1:.3e}")

    first_over_t = None
    over_streak = 0
    all_valid = np.ones(n_fluid, dtype=bool)
    z_min_run = float("inf")
    wall0 = time.time()
    if not args.no_video:
        cam.start_recording(save_to_filename=mp4_main, fps=args.fps)
        cam_close.start_recording(save_to_filename=mp4_closeup, fps=args.fps)
        if cam_top is not None:
            cam_top.start_recording(save_to_filename=mp4_top, fps=args.fps)
    print_every = int(round(1.0 / DT))
    slab_frames = {}
    if args.dump_slabs:
        for ts in [float(v) for v in args.dump_slabs.split(",") if v.strip()]:
            slab_frames[min(max(int(round(ts / DT)), 0), n_frames)] = ts  # nearest frame
    slab_records = []
    # Offline-renderer frame dumps: full fluid prefix plus shared jug pose.
    dump_frames = {}
    if args.dump_frames:
        for ts in [float(v) for v in args.dump_frames.split(",") if v.strip()]:
            dump_frames[min(max(int(round(ts / DT)), 0), n_frames)] = ts
    frame_dumps = {}

    prev_pos = solver.particles.pos.to_numpy()[:n_fluid, 0, :].copy()
    prev_origin, prev_quat, _, _, _ = jug_pose(0.0)
    prev_jlocal = inverse_transform_points(prev_pos, prev_origin, prev_quat)
    jug_resident = np.zeros(n_fluid, dtype=bool)
    jug_resident[n_coffee:] = (
        (np.linalg.norm(prev_jlocal[n_coffee:, :2], axis=1) <= R_JUG + ps)
        & (prev_jlocal[n_coffee:, 2] >= Z_FLOOR - ps)
        & (prev_jlocal[n_coffee:, 2] <= Z_RIM + ps)
    )
    jug_cleared = np.zeros(n_fluid, dtype=bool)
    jug_wall_entered = (
        jug_resident & (np.linalg.norm(prev_jlocal[:, :2], axis=1) > R_JUG - 0.5 * ps)
        & (prev_jlocal[:, 2] <= Z_RIM - 0.5 * ps)
    )
    jug_wall_inbound_entered = np.zeros(n_fluid, dtype=bool)
    jug_bottom_entered = jug_resident & (prev_jlocal[:, 2] < Z_FLOOR + 0.5 * ps)
    jug_wall_tunnel = np.zeros(n_fluid, dtype=bool)
    jug_bottom_tunnel = np.zeros(n_fluid, dtype=bool)
    mug_resident = np.zeros(n_fluid, dtype=bool)
    mug_resident[:n_coffee] = True
    mug_rim_crossed = np.zeros(n_fluid, dtype=bool)
    mug_cleared = np.zeros(n_fluid, dtype=bool)
    prev_r_mug0 = np.linalg.norm(prev_pos[:, :2], axis=1)
    mug_wall_entered = (
        mug_resident & (prev_r_mug0 > R_IN - 0.5 * ps)
        & (prev_pos[:, 2] <= Z_RIM - 0.5 * ps)
    )
    mug_wall_inbound_entered = np.zeros(n_fluid, dtype=bool)
    mug_bottom_entered = mug_resident & (prev_pos[:, 2] < Z_FLOOR + 0.5 * ps)
    mug_wall_tunnel = np.zeros(n_fluid, dtype=bool)
    mug_bottom_tunnel = np.zeros(n_fluid, dtype=bool)
    outer_wall_run = np.zeros(n_fluid, dtype=np.int32)
    outer_wall_max_run = np.zeros(n_fluid, dtype=np.int32)
    max_ball_pose_err = 0.0
    max_active_fluid_error = 0

    for i in range(n_frames + 1):
        # ---- animation: physics clamp pose + visual mesh pose -----------------------------
        t = i * DT
        origin, quat, axis, th, _ = jug_pose(t)
        jug_world_expected = transform_points(jug_local, origin, quat)
        env_lo, env_hi = jug_world_expected.min(axis=0), jug_world_expected.max(axis=0)
        assert np.all(env_lo >= LOWER_BOUND - 1e-7), (t, env_lo)
        assert np.all(env_hi < UPPER_BOUND), (t, env_hi)
        solver.set_boundary_ball_pose(1, origin, quat)
        jug.set_pos(origin, relative=True, zero_velocity=True)
        jug.set_quat(quat, relative=True, zero_velocity=True)

        frame_t0 = time.time()
        if i > 0:
            scene.step()

        # ---- metrics ----------------------------------------------------------------------
        phase = phase_of(t)
        pos_all = solver.particles.pos.to_numpy()[:n_fluid, 0, :]
        vel = solver.particles.vel.to_numpy()[:n_fluid, 0, :]
        c = solver.particles.c.to_numpy()[:n_fluid, 0]
        nan_count = int((~np.isfinite(pos_all)).sum() + (~np.isfinite(vel)).sum() + (~np.isfinite(c)).sum())
        safe = np.nan_to_num(pos_all, nan=0.0, posinf=0.0, neginf=0.0)
        safe_v = np.nan_to_num(vel, nan=0.0, posinf=0.0, neginf=0.0)
        safe_c = np.nan_to_num(c, nan=0.0, posinf=0.0, neginf=0.0)
        r_all = np.linalg.norm(safe[:, :2], axis=1)
        z_all = safe[:, 2]
        active_fluid = int(solver.particles_ng.active.to_numpy()[:n_fluid, 0].sum())
        max_active_fluid_error = max(max_active_fluid_error, abs(active_fluid - n_fluid))
        assert active_fluid == n_fluid, f"active fluid changed at t={t:.3f}: {active_fluid}/{n_fluid}"
        valid = all_valid

        # Collision/mesh pose proof after the step has advanced the staged kinematic trajectory.
        jug_start, jug_end, _ = solver.boundary_ball_ranges[1]
        jug_ball_now = solver.particles.pos.to_numpy()[jug_start:jug_end, 0, :]
        ball_pose_err = float(np.max(np.abs(jug_ball_now - jug_world_expected)))
        max_ball_pose_err = max(max_ball_pose_err, ball_pose_err)
        assert ball_pose_err < 5e-7, f"jug ball pose mismatch at t={t:.3f}: {ball_pose_err:.3e}"

        # Historical tunnel metric.  A legal exit must first cross the true visible inner rim;
        # contact layers are not leakage, and a tunnel flag is irreversible.
        if args.smooth_a2:
            solver_rim_staged, solver_direct_tunnel = solver.boundary_ball_smooth_barrel_history()
        else:
            solver_rim_staged = np.zeros(n_fluid, dtype=bool)
            solver_direct_tunnel = np.zeros(n_fluid, dtype=bool)
        # Solver-owned jug exit history (--jug-hist): rim staging / irreversible direct tunnel
        # per accepted substep in the substep-interpolated jug-local frame, spout-aware.  In the
        # spout sector (azimuth 180 deg +/- 20 deg) the frame probes below disagree with the
        # solver BY DESIGN: the frame probe still uses the flat 0.320 clearance plane while the
        # solver uses the spout-aware top surface z_top(az) = 0.316 + spout_dz*w(az) + particle
        # radius (0.318 at the beak centre).  Such disagreement is EXPECTED and benign; the
        # frame probes are kept only as diagnostic counters.
        if args.jug_hist:
            solver_jug_staged, solver_jug_direct = solver.boundary_ball_jug_history()
        else:
            solver_jug_staged = np.zeros(n_fluid, dtype=bool)
            solver_jug_direct = np.zeros(n_fluid, dtype=bool)
        cur_jlocal = inverse_transform_points(safe, origin, quat)
        pr, cr = np.linalg.norm(prev_jlocal[:, :2], axis=1), np.linalg.norm(cur_jlocal[:, :2], axis=1)
        pzj, czj = prev_jlocal[:, 2], cur_jlocal[:, 2]
        jug_clear_z = Z_RIM + 0.5 * ps
        jug_wall_z_lo = -0.5 * ps
        jug_wall_z_hi = Z_RIM + 0.5 * ps
        up = (czj > pzj) & (pzj < jug_clear_z) & (czj >= jug_clear_z)
        u = np.clip((jug_clear_z - pzj) / np.maximum(czj - pzj, 1e-12), 0.0, 1.0)
        cross_xy = prev_jlocal[:, :2] + u[:, None] * (cur_jlocal[:, :2] - prev_jlocal[:, :2])
        legal_jug_cross = up & (np.linalg.norm(cross_xy, axis=1) <= R_JUG + 0.5 * ps)
        jug_any_tunnel = jug_wall_tunnel | jug_bottom_tunnel
        jug_open = jug_resident & ~jug_cleared & ~jug_any_tunnel
        jug_wall_entered |= (
            jug_open & (cr > R_JUG - 0.5 * ps)
            & (czj >= jug_wall_z_lo) & (czj < jug_clear_z)
        )
        jug_bottom_entered |= (
            jug_open & (czj < Z_FLOOR + 0.5 * ps)
            & (cr <= R_JUG + T_JUG_WALL + ps)
        )
        jug_outer_r = R_JUG + T_JUG_WALL + 0.5 * ps
        jug_outer_cross, _, jug_outer_z = segment_outward_cylinder_crossing(
            prev_jlocal, cur_jlocal, jug_outer_r
        )
        jug_outer_in, _, jug_outer_in_z = segment_inward_cylinder_crossing(
            prev_jlocal, cur_jlocal, jug_outer_r
        )
        jug_wall_inbound_entered |= (
            jug_resident & ~jug_cleared & ~jug_any_tunnel & jug_outer_in
            & (jug_outer_in_z >= jug_wall_z_lo) & (jug_outer_in_z <= jug_wall_z_hi)
        )
        jug_inner_in, _, jug_inner_in_z = segment_inward_cylinder_crossing(
            prev_jlocal, cur_jlocal, R_JUG - 0.5 * ps
        )
        frame_jug_inbound_tunnel_probe = (
            jug_resident & ~jug_cleared & ~jug_any_tunnel & jug_wall_inbound_entered
            & jug_inner_in & (jug_inner_in_z >= jug_wall_z_lo) & (jug_inner_in_z < jug_clear_z)
        )
        # A particle centre that crosses the outer wall radius at/above .320, or is already
        # outside there at the previous accepted frame endpoint, is in open space above the
        # strict clearance plane.  Record that high exit before evaluating low-wall occupancy;
        # this is not a relaxed threshold and cannot legalize a crossing below .320.
        jug_high_clear_now = jug_open & (
            legal_jug_cross
            | (jug_outer_cross & (jug_outer_z >= jug_clear_z))
            | ((pr >= jug_outer_r) & (pzj >= jug_clear_z))
        )
        # Frame-level wall-crossing probe, kept for diagnostics.  Under --jug-hist the solver's
        # spout-aware substep history is authoritative: an unstaged frame chord or the solver's
        # irreversible direct counter is a wall tunnel.  Staging only excuses the rounded frame
        # chord at the physical top face; it never grants a permanent exemption to a later
        # low-z outside->inside wall penetration, and staged must never wash a set direct.
        frame_jug_wall_tunnel_probe = (
            jug_open & ~jug_high_clear_now & jug_wall_entered
            & (
                (jug_outer_cross & (jug_outer_z >= jug_wall_z_lo) & (jug_outer_z < jug_clear_z))
                | (~jug_outer_cross & (cr >= jug_outer_r)
                   & (czj >= jug_wall_z_lo) & (czj < jug_clear_z))
            )
        )
        jug_wall_tunnel_now = (frame_jug_wall_tunnel_probe & ~solver_jug_staged) | solver_jug_direct
        # Mirror of the mug staged_top_reentry exemption (see below): staging excuses only the
        # rounded frame chord re-entering at the physical top surface (jug rim z = Z_RIM),
        # never a later low-z out->in crossing below the clearance plane.
        jug_staged_top_reentry = solver_jug_staged & (jug_inner_in_z >= Z_RIM - 1e-6)
        jug_inbound_tunnel_now = frame_jug_inbound_tunnel_probe & ~jug_staged_top_reentry
        jug_bottom_cross, _, jug_bottom_point = segment_downward_plane_crossing(
            prev_jlocal, cur_jlocal, -0.5 * ps
        )
        jug_bottom_cross_r = np.linalg.norm(jug_bottom_point[:, :2], axis=1)
        jug_bottom_tunnel_now = (
            jug_open & jug_bottom_entered
            & (
                (jug_bottom_cross & (jug_bottom_cross_r <= R_JUG + T_JUG_WALL + ps))
                | (~jug_bottom_cross & (czj < -0.5 * ps)
                   & (cr <= R_JUG + T_JUG_WALL + ps))
            )
        )
        # Tunnel history is locked first.  A later rim event can never wash it into "cleared".
        new_jug_wall_tunnel = (jug_wall_tunnel_now | jug_inbound_tunnel_now) & ~jug_wall_tunnel
        for pid in np.flatnonzero(new_jug_wall_tunnel):
            is_solver_direct = bool(solver_jug_direct[pid])
            is_inbound = bool(jug_inbound_tunnel_now[pid]) and not is_solver_direct
            query_pt = cur_jlocal[pid]
            ball_d, ball_idx = jug_ball_tree.query(query_pt, k=1, workers=-1)
            ball_d, ball_idx = float(ball_d), int(ball_idx)
            prev_az = float(np.degrees(np.arctan2(prev_jlocal[pid, 1], prev_jlocal[pid, 0])))
            cur_az = float(np.degrees(np.arctan2(cur_jlocal[pid, 1], cur_jlocal[pid, 0])))
            ball_az = float(np.degrees(np.arctan2(jug_local[ball_idx, 1], jug_local[ball_idx, 0])))
            kind = "solver_direct" if is_solver_direct else ("wall_inbound" if is_inbound else "wall")
            event_cross_z = float(jug_outer_in_z[pid] if is_inbound else jug_outer_z[pid])
            event = {
                "body": "jug", "pid": int(pid), "t": float(t), "phase": int(phase), "kind": kind,
                "prev_r": float(pr[pid]), "prev_z": float(pzj[pid]), "prev_az_deg": prev_az,
                "cur_r": float(cr[pid]), "cur_z": float(czj[pid]), "cur_az_deg": cur_az,
                "cross_z": event_cross_z, "speed": float(np.linalg.norm(safe_v[pid])),
                "cleared_before": bool(jug_cleared[pid]), "resident": bool(jug_resident[pid]),
                "entered": bool(jug_wall_entered[pid]), "nearest_ball_d": ball_d,
                "nearest_ball_idx": ball_idx, "nearest_face": str(jug_ball_face[ball_idx]),
                "nearest_layer": int(jug_ball_layer[ball_idx]),
                "nearest_ball_r": float(np.linalg.norm(jug_local[ball_idx, :2])),
                "nearest_ball_z": float(jug_local[ball_idx, 2]), "nearest_ball_az_deg": ball_az,
                "spout_sector": bool(abs(((cur_az - 180.0 + 180.0) % 360.0) - 180.0) <= 20.0),
            }
            tunnel_event_records.append(event)
            print(
                f"TUNNEL_JUG id={pid} t={t:.6f} kind={kind} cross_outer_z={event_cross_z:.6f} "
                f"prev_rz=({pr[pid]:.6f},{pzj[pid]:.6f}) cur_rz=({cr[pid]:.6f},{czj[pid]:.6f}) "
                f"az=({prev_az:.2f},{cur_az:.2f}) speed={np.linalg.norm(safe_v[pid]):.6f} "
                f"cleared_before={bool(jug_cleared[pid])} ball_d_local={ball_d:.6f} "
                f"ball={ball_idx}:{jug_ball_face[ball_idx]}:{int(jug_ball_layer[ball_idx])} "
                f"ball_rz=({np.linalg.norm(jug_local[ball_idx,:2]):.6f},{jug_local[ball_idx,2]:.6f}) "
                f"entered={bool(jug_wall_entered[pid])} spout_sector={event['spout_sector']}"
            )
        for pid in np.flatnonzero(jug_bottom_tunnel_now & ~jug_bottom_tunnel):
            ball_d, ball_idx = jug_ball_tree.query(cur_jlocal[pid], k=1, workers=-1)
            ball_d, ball_idx = float(ball_d), int(ball_idx)
            prev_az = float(np.degrees(np.arctan2(prev_jlocal[pid, 1], prev_jlocal[pid, 0])))
            cur_az = float(np.degrees(np.arctan2(cur_jlocal[pid, 1], cur_jlocal[pid, 0])))
            ball_az = float(np.degrees(np.arctan2(jug_local[ball_idx, 1], jug_local[ball_idx, 0])))
            event = {
                "body": "jug", "pid": int(pid), "t": float(t), "phase": int(phase), "kind": "bottom",
                "prev_r": float(pr[pid]), "prev_z": float(pzj[pid]), "prev_az_deg": prev_az,
                "cur_r": float(cr[pid]), "cur_z": float(czj[pid]), "cur_az_deg": cur_az,
                "cross_z": float("nan"), "speed": float(np.linalg.norm(safe_v[pid])),
                "cleared_before": bool(jug_cleared[pid]), "resident": bool(jug_resident[pid]),
                "entered": bool(jug_bottom_entered[pid]), "nearest_ball_d": ball_d,
                "nearest_ball_idx": ball_idx, "nearest_face": str(jug_ball_face[ball_idx]),
                "nearest_layer": int(jug_ball_layer[ball_idx]),
                "nearest_ball_r": float(np.linalg.norm(jug_local[ball_idx, :2])),
                "nearest_ball_z": float(jug_local[ball_idx, 2]), "nearest_ball_az_deg": ball_az,
                "spout_sector": bool(abs(((cur_az - 180.0 + 180.0) % 360.0) - 180.0) <= 20.0),
            }
            tunnel_event_records.append(event)
            print(
                f"TUNNEL_JUG id={pid} t={t:.6f} kind=bottom cross_outer_z=nan "
                f"prev_rz=({pr[pid]:.6f},{pzj[pid]:.6f}) cur_rz=({cr[pid]:.6f},{czj[pid]:.6f}) "
                f"az=({prev_az:.2f},{cur_az:.2f}) speed={np.linalg.norm(safe_v[pid]):.6f} "
                f"cleared_before={bool(jug_cleared[pid])} ball_d_local={ball_d:.6f} "
                f"ball={ball_idx}:{jug_ball_face[ball_idx]}:{int(jug_ball_layer[ball_idx])} "
                f"ball_rz=({np.linalg.norm(jug_local[ball_idx,:2]):.6f},{jug_local[ball_idx,2]:.6f}) "
                f"entered={bool(jug_bottom_entered[pid])} spout_sector={event['spout_sector']}"
            )
        jug_wall_tunnel |= jug_wall_tunnel_now | jug_inbound_tunnel_now
        jug_bottom_tunnel |= jug_bottom_tunnel_now
        jug_any_tunnel = jug_wall_tunnel | jug_bottom_tunnel
        jug_cleared &= ~jug_any_tunnel
        # Legal clear consumes the solver's accepted-substep rim staging under --jug-hist
        # (mirror of the mug consumption below); without the flag the frame-level high-exit
        # probe remains the clearance source, exactly as before.
        jug_clear_event = solver_jug_staged if args.jug_hist else jug_high_clear_now
        jug_cleared |= jug_resident & ~jug_any_tunnel & jug_clear_event
        assert not np.any(jug_cleared & jug_any_tunnel), "jug clear/tunnel histories must be exclusive"
        assert not np.any(solver_jug_staged & solver_jug_direct), \
            "jug staged/direct histories must be exclusive"

        prev_r_mug = np.linalg.norm(prev_pos[:, :2], axis=1)
        cur_r_mug = np.linalg.norm(safe[:, :2], axis=1)
        inside_mug_now = (
            (cur_r_mug <= R_IN - 0.5 * ps) & (z_all >= Z_FLOOR) & (z_all <= Z_RIM)
        )
        mug_resident |= inside_mug_now
        mug_any_tunnel = mug_wall_tunnel | mug_bottom_tunnel
        mug_open = mug_resident & ~mug_cleared & ~mug_any_tunnel
        mug_wall_entered |= (
            mug_open & (cur_r_mug > R_IN - 0.5 * ps)
            & (z_all >= 0.0) & (z_all < Z_RIM + MUG_OUTER_CLEAR_Z_PS * ps)
        )
        mug_bottom_entered |= (
            mug_open & (z_all < Z_FLOOR + 0.5 * ps) & (cur_r_mug <= R_OUT + ps)
        )
        outer_clear_r = R_OUT + MUG_OUTER_CLEAR_PS * ps
        outer_cross, outer_u, cross_outer_z = segment_outward_cylinder_crossing(
            prev_pos, safe, outer_clear_r
        )
        legal_outer_z = Z_RIM + MUG_OUTER_CLEAR_Z_PS * ps
        outer_in, _, cross_outer_in_z = segment_inward_cylinder_crossing(
            prev_pos, safe, outer_clear_r
        )
        # Aligns with the jug side: a legally overflow-cleared particle re-crossing the inner
        # proxy is not tunnelling.
        mug_wall_inbound_entered |= (
            mug_resident & ~mug_cleared & ~mug_any_tunnel & outer_in & (cross_outer_in_z < legal_outer_z)
        )
        inner_safe_r = R_IN - 0.5 * ps
        inner_in, inner_in_u, cross_inner_in_z = segment_inward_cylinder_crossing(
            prev_pos, safe, inner_safe_r
        )
        frame_mug_inbound_tunnel_now = (
            mug_resident & ~mug_cleared & ~mug_any_tunnel & mug_wall_inbound_entered
            & inner_in & (cross_inner_in_z < legal_outer_z)
        )
        frame_mug_wall_tunnel_now = (
            mug_open & mug_wall_entered
            & (
                (outer_cross & (cross_outer_z >= 0.0) & (cross_outer_z < legal_outer_z))
                | (~outer_cross & (cur_r_mug >= outer_clear_r)
                   & (z_all >= 0.0) & (z_all < legal_outer_z))
            )
        )
        # A 60 Hz endpoint chord can cut through the rounded rim even when accepted substeps
        # actually touched z=.320 first.  Keep that probe for diagnostics, but only an unstaged
        # chord or the solver's irreversible direct counter is a wall tunnel under A2.
        # Staging only excuses the rounded-corner chord at the physical top face.  It must not
        # grant a permanent exemption to a later low-z outside->inside wall penetration.
        staged_top_reentry = solver_rim_staged & (cross_inner_in_z >= Z_RIM - 1e-6)
        mug_inbound_tunnel_now = frame_mug_inbound_tunnel_now & ~staged_top_reentry
        mug_wall_tunnel_now = (frame_mug_wall_tunnel_now & ~solver_rim_staged) | solver_direct_tunnel
        mug_bottom_cross, _, mug_bottom_point = segment_downward_plane_crossing(
            prev_pos, safe, -0.5 * ps
        )
        mug_bottom_cross_r = np.linalg.norm(mug_bottom_point[:, :2], axis=1)
        mug_bottom_tunnel_now = (
            mug_open & mug_bottom_entered
            & (
                (mug_bottom_cross & (mug_bottom_cross_r <= R_OUT + ps))
                | (~mug_bottom_cross & (z_all < -0.5 * ps) & (cur_r_mug <= R_OUT + ps))
            )
        )
        new_mug_wall_tunnel = (mug_wall_tunnel_now | mug_inbound_tunnel_now) & ~mug_wall_tunnel
        for pid in np.flatnonzero(new_mug_wall_tunnel):
            is_solver_direct = bool(solver_direct_tunnel[pid])
            is_inbound = bool(mug_inbound_tunnel_now[pid]) and not is_solver_direct
            cp = (prev_pos[pid] + inner_in_u[pid] * (safe[pid] - prev_pos[pid])) \
                if is_inbound else ((prev_pos[pid] + outer_u[pid] * (safe[pid] - prev_pos[pid])) \
                if outer_cross[pid] else safe[pid])
            ball_d, ball_idx = mug_ball_tree.query(cp, k=1, workers=-1)
            ball_d, ball_idx = float(ball_d), int(ball_idx)
            prev_az = float(np.degrees(np.arctan2(prev_pos[pid, 1], prev_pos[pid, 0])))
            cur_az = float(np.degrees(np.arctan2(safe[pid, 1], safe[pid, 0])))
            ball_az = float(np.degrees(np.arctan2(mug_local[ball_idx, 1], mug_local[ball_idx, 0])))
            kind = "solver_direct" if is_solver_direct else ("wall_inbound" if is_inbound else "wall")
            event_cross_z = float(cross_inner_in_z[pid] if is_inbound else cross_outer_z[pid])
            event = {
                "body": "mug", "pid": int(pid), "t": float(t), "phase": int(phase), "kind": kind,
                "prev_r": float(prev_r_mug[pid]), "prev_z": float(prev_pos[pid, 2]), "prev_az_deg": prev_az,
                "cur_r": float(cur_r_mug[pid]), "cur_z": float(z_all[pid]), "cur_az_deg": cur_az,
                "cross_z": event_cross_z, "speed": float(np.linalg.norm(safe_v[pid])),
                "cleared_before": bool(mug_cleared[pid]), "resident": bool(mug_resident[pid]),
                "entered": bool(mug_wall_entered[pid]), "nearest_ball_d": ball_d,
                "nearest_ball_idx": ball_idx, "nearest_face": str(mug_ball_face[ball_idx]),
                "nearest_layer": int(mug_ball_layer[ball_idx]),
                "nearest_ball_r": float(np.linalg.norm(mug_local[ball_idx, :2])),
                "nearest_ball_z": float(mug_local[ball_idx, 2]), "nearest_ball_az_deg": ball_az,
                "spout_sector": False,
            }
            tunnel_event_records.append(event)
            print(
                f"TUNNEL_MUG id={pid} t={t:.6f} "
                f"kind={kind} cross_outer_z={event_cross_z:.6f} "
                f"prev_rz=({prev_r_mug[pid]:.6f},{prev_pos[pid, 2]:.6f}) "
                f"cur_rz=({cur_r_mug[pid]:.6f},{z_all[pid]:.6f}) "
                f"speed={np.linalg.norm(safe_v[pid]):.6f} ball_d={ball_d:.6f} "
                f"gap={ball_d >= ps} entered={bool(mug_wall_entered[pid])} "
                f"rim_path={bool(mug_rim_crossed[pid])}"
            )
        for pid in np.flatnonzero(mug_bottom_tunnel_now & ~mug_bottom_tunnel):
            ball_d, ball_idx = mug_ball_tree.query(safe[pid], k=1, workers=-1)
            ball_d, ball_idx = float(ball_d), int(ball_idx)
            prev_az = float(np.degrees(np.arctan2(prev_pos[pid, 1], prev_pos[pid, 0])))
            cur_az = float(np.degrees(np.arctan2(safe[pid, 1], safe[pid, 0])))
            ball_az = float(np.degrees(np.arctan2(mug_local[ball_idx, 1], mug_local[ball_idx, 0])))
            event = {
                "body": "mug", "pid": int(pid), "t": float(t), "phase": int(phase), "kind": "bottom",
                "prev_r": float(prev_r_mug[pid]), "prev_z": float(prev_pos[pid, 2]), "prev_az_deg": prev_az,
                "cur_r": float(cur_r_mug[pid]), "cur_z": float(z_all[pid]), "cur_az_deg": cur_az,
                "cross_z": float("nan"), "speed": float(np.linalg.norm(safe_v[pid])),
                "cleared_before": bool(mug_cleared[pid]), "resident": bool(mug_resident[pid]),
                "entered": bool(mug_bottom_entered[pid]), "nearest_ball_d": ball_d,
                "nearest_ball_idx": ball_idx, "nearest_face": str(mug_ball_face[ball_idx]),
                "nearest_layer": int(mug_ball_layer[ball_idx]),
                "nearest_ball_r": float(np.linalg.norm(mug_local[ball_idx, :2])),
                "nearest_ball_z": float(mug_local[ball_idx, 2]), "nearest_ball_az_deg": ball_az,
                "spout_sector": False,
            }
            tunnel_event_records.append(event)
            print(
                f"TUNNEL_MUG id={pid} t={t:.6f} kind=bottom cross_outer_z=nan "
                f"prev_rz=({prev_r_mug[pid]:.6f},{prev_pos[pid, 2]:.6f}) "
                f"cur_rz=({cur_r_mug[pid]:.6f},{z_all[pid]:.6f}) "
                f"speed={np.linalg.norm(safe_v[pid]):.6f} ball_d={ball_d:.6f} "
                f"gap={ball_d >= ps} entered={bool(mug_bottom_entered[pid])} "
                f"rim_path={bool(mug_rim_crossed[pid])}"
            )
        mug_wall_tunnel |= mug_wall_tunnel_now | mug_inbound_tunnel_now
        mug_bottom_tunnel |= mug_bottom_tunnel_now
        mug_any_tunnel = mug_wall_tunnel | mug_bottom_tunnel
        mug_cleared &= ~mug_any_tunnel

        # Frame geometry remains a cross-check, but under A2 legal clearance must consume the
        # accepted-substep history.  No 60 Hz event may create staged state or wash direct tunnel.
        rim_path_r = R_IN - MUG_RIM_PATH_R_MIN_PS * ps
        inner_cross, _, cross_inner_z = segment_outward_cylinder_crossing(prev_pos, safe, rim_path_r)
        upm = (z_all > prev_pos[:, 2]) & (prev_pos[:, 2] < Z_RIM) & (z_all >= Z_RIM)
        uz = np.clip(
            (Z_RIM - prev_pos[:, 2]) / np.maximum(z_all - prev_pos[:, 2], 1e-12),
            0.0,
            1.0,
        )
        cross_rim_xy = prev_pos[:, :2] + uz[:, None] * (safe[:, :2] - prev_pos[:, :2])
        cross_rim_r = np.linalg.norm(cross_rim_xy, axis=1)
        near_inner_lip_now = (
            (cur_r_mug >= rim_path_r)
            & (cur_r_mug <= R_OUT + MUG_RIM_PATH_R_MAX_PS * ps)
            & (z_all >= Z_RIM)
        )
        rim_plane_event = (
            upm & (cross_rim_r >= rim_path_r)
            & (cross_rim_r <= R_OUT + MUG_RIM_PATH_R_MAX_PS * ps)
        )
        rim_path_event = (inner_cross & (cross_inner_z >= Z_RIM)) | rim_plane_event
        frame_rim_probe = near_inner_lip_now | rim_path_event
        authoritative_rim_event = solver_rim_staged if args.smooth_a2 else frame_rim_probe
        mug_rim_crossed |= mug_resident & ~mug_cleared & ~mug_any_tunnel & authoritative_rim_event
        mug_rim_crossed &= ~mug_any_tunnel
        legal_outer_clear = (
            mug_rim_crossed & ~mug_cleared & ~mug_any_tunnel
            & (
                (outer_cross & (cross_outer_z >= legal_outer_z))
                | (args.smooth_a2 & solver_rim_staged & (cur_r_mug >= outer_clear_r))
            )
        )
        mug_cleared |= legal_outer_clear
        assert not np.any(mug_cleared & mug_any_tunnel), "mug clear/tunnel histories must be exclusive"
        n_solver_rim_staged = int(solver_rim_staged.sum())
        n_solver_direct_tunnel = int(solver_direct_tunnel.sum())
        n_frame_rim_probe = int(frame_rim_probe.sum())
        n_frame_low_cross_staged = int(
            ((frame_mug_wall_tunnel_now | frame_mug_inbound_tunnel_now) & solver_rim_staged).sum()
        )
        # Jug solver-history diagnostics (milk range), plus frame/solver agreement counters.
        # In the spout sector the frame probe fires on crossings the spout-aware solver surface
        # legalizes - n_frame_jug_wall_staged counts exactly those benign disagreements.
        n_solver_jug_rim_staged = int(solver_jug_staged[n_coffee:].sum())
        n_solver_jug_direct_tunnel = int(solver_jug_direct[n_coffee:].sum())
        n_frame_jug_wall_probe = int(frame_jug_wall_tunnel_probe[n_coffee:].sum())
        n_frame_jug_wall_staged = int(
            (frame_jug_wall_tunnel_probe & solver_jug_staged)[n_coffee:].sum()
        )
        n_frame_jug_wall_direct = int(
            (frame_jug_wall_tunnel_probe & solver_jug_direct)[n_coffee:].sum()
        )
        n_jug_cleared = int(jug_cleared[n_coffee:].sum())
        n_jug_wall_tunnel = int(jug_wall_tunnel[n_coffee:].sum())
        n_jug_bottom_tunnel = int(jug_bottom_tunnel[n_coffee:].sum())
        n_mug_rim_crossed = int(mug_rim_crossed.sum())
        n_mug_cleared = int(mug_cleared.sum())
        n_mug_wall_tunnel = int(mug_wall_tunnel.sum())
        n_mug_bottom_tunnel = int(mug_bottom_tunnel.sum())
        n_leak = n_jug_wall_tunnel + n_jug_bottom_tunnel + n_mug_wall_tunnel + n_mug_bottom_tunnel
        sum_c = float(safe_c[valid].sum())
        std_c = float(safe_c[valid].std())
        ke = float(0.5 * np.nansum((safe_v[valid] ** 2).sum(axis=1)))
        rel_j = safe[n_coffee:n_fluid] - origin
        s_j = rel_j @ axis
        r_j = np.linalg.norm(rel_j - s_j[:, None] * axis[None, :], axis=1)
        # particles still inside the jug's own footprint (cavity + wall + escape band): the jug
        # stands on the table with its cavity floor at z=Z_FLOOR > 2.5 ps, and its carried milk
        # rides above the mug rim, so without this mask the literal n_table / n_over_rim windows
        # count the jug's own bottom layers and its milk instead of spilled milk
        in_jug_fp = (s_j > Z_FLOOR - 3.0 * ps) & (s_j < Z_RIM + 3.0 * ps) \
            & (r_j <= R_JUG + T_JUG_WALL + 3.0 * ps)
        not_jug = np.ones(n_fluid, dtype=bool)
        not_jug[n_coffee:] = ~in_jug_fp
        in_mug = (r_all <= R_IN + ps) & (z_all >= Z_FLOOR - ps) & valid
        bulk_surface = in_mug & not_jug & mug_resident & ~mug_cleared
        z_surf, n_dome = coherent_mug_surface(safe, safe_v, bulk_surface, ps)
        n_coffee_mug = int(in_mug[:n_coffee].sum())
        legal_mug_out = mug_cleared & ~mug_wall_tunnel & ~mug_bottom_tunnel & not_jug & valid
        n_over_rim = int((legal_mug_out & (z_all > Z_RIM + 0.5 * ps)
                          & (r_all > R_OUT - ps)).sum())
        outer_wall_mask = (
            legal_mug_out & (r_all >= R_OUT - 0.5 * ps) & (r_all <= R_OUT + 2.5 * ps)
            & (z_all >= 0.02) & (z_all <= Z_RIM)
        )
        n_outer_wall = int(outer_wall_mask.sum())
        outer_wall_run = np.where(outer_wall_mask, outer_wall_run + 1, 0)
        outer_wall_max_run = np.maximum(outer_wall_max_run, outer_wall_run)
        wall_speeds = np.linalg.norm(safe_v[outer_wall_mask], axis=1)
        wall_runs_s = outer_wall_run[outer_wall_mask].astype(np.float64) * DT
        wall_speed_p50 = float(np.median(wall_speeds)) if len(wall_speeds) else 0.0
        wall_speed_p90 = float(np.percentile(wall_speeds, 90)) if len(wall_speeds) else 0.0
        wall_res_p50 = float(np.median(wall_runs_s)) if len(wall_runs_s) else 0.0
        wall_res_p90 = float(np.percentile(wall_runs_s, 90)) if len(wall_runs_s) else 0.0
        wall_res_max = float(outer_wall_max_run.max() * DT)
        n_wall_ever_1s = int(np.count_nonzero(outer_wall_max_run >= round(1.0 / DT)))
        n_wall_persistent_1s = int(np.count_nonzero(outer_wall_run >= round(1.0 / DT)))
        wall_lifetime_runs = outer_wall_max_run[outer_wall_max_run > 0].astype(np.float64) * DT
        wall_max_res_p90 = float(np.percentile(wall_lifetime_runs, 90)) if len(wall_lifetime_runs) else 0.0
        n_outer_wall_coffee = int(outer_wall_mask[:n_coffee].sum())
        n_outer_wall_milk = int(outer_wall_mask[n_coffee:].sum())
        n_table = int((legal_mug_out & (z_all <= 2.5 * ps)
                       & (r_all > R_OUT + 3.0 * ps)).sum())
        n_milk_jug = int(((s_j > Z_FLOOR - ps) & (s_j < Z_RIM + ps) & (r_j <= R_JUG + ps)).sum())
        n_milk_mug = int(in_mug[n_coffee:].sum())
        if i in dump_frames:
            # Full fluid state plus the exact history masks required by the independent surface
            # audit.  These are diagnostics only; no state is written back to the solver.
            frame_dumps[f"{dump_frames[i]:g}"] = safe[:n_fluid].copy()
            frame_dumps[f"vel_{dump_frames[i]:g}"] = safe_v[:n_fluid].copy()
            frame_dumps[f"c_{dump_frames[i]:g}"] = solver.particles.c.to_numpy()[:n_fluid, 0].copy()
            frame_dumps[f"pose_{dump_frames[i]:g}"] = np.concatenate([origin, quat])
            frame_dumps[f"valid_{dump_frames[i]:g}"] = valid[:n_fluid].copy()
            frame_dumps[f"mug_resident_{dump_frames[i]:g}"] = mug_resident[:n_fluid].copy()
            frame_dumps[f"not_jug_{dump_frames[i]:g}"] = not_jug[:n_fluid].copy()
            frame_dumps[f"jug_wall_entered_{dump_frames[i]:g}"] = jug_wall_entered[:n_fluid].copy()
            frame_dumps[f"jug_bottom_entered_{dump_frames[i]:g}"] = jug_bottom_entered[:n_fluid].copy()
            frame_dumps[f"mug_wall_entered_{dump_frames[i]:g}"] = mug_wall_entered[:n_fluid].copy()
            frame_dumps[f"mug_bottom_entered_{dump_frames[i]:g}"] = mug_bottom_entered[:n_fluid].copy()
            frame_dumps[f"mug_rim_crossed_{dump_frames[i]:g}"] = mug_rim_crossed[:n_fluid].copy()
            frame_dumps[f"mug_cleared_{dump_frames[i]:g}"] = mug_cleared[:n_fluid].copy()
            frame_dumps[f"mug_wall_tunnel_{dump_frames[i]:g}"] = mug_wall_tunnel[:n_fluid].copy()
            frame_dumps[f"mug_bottom_tunnel_{dump_frames[i]:g}"] = mug_bottom_tunnel[:n_fluid].copy()
            frame_dumps[f"solver_rim_staged_{dump_frames[i]:g}"] = solver_rim_staged[:n_fluid].copy()
            frame_dumps[f"solver_direct_tunnel_{dump_frames[i]:g}"] = solver_direct_tunnel[:n_fluid].copy()
        if i in slab_frames:
            # cross-section of the pour column in the z band between the mug rim and the jug
            # lip, in two variants: every milk particle in the band (stream plus whatever clings
            # to the jug wall), and the free-falling part alone (jug footprint excluded) - with
            # adhesion the column partly hugs the wall, so the two answers differ by design
            mk_xy = safe[n_coffee:n_fluid, :2]
            mk_z = z_all[n_coffee:n_fluid]
            in_band = (mk_z >= 0.315) & (mk_z <= 0.345)
            selections = (
                ("all", valid[n_coffee:] & in_band),
                ("free", valid[n_coffee:] & not_jug[n_coffee:] & in_band),
            )
            rec = [slab_frames[i]]
            line = f"slab t={slab_frames[i]:.2f}s:"
            for name, msk in selections:
                pts = mk_xy[msk]
                n_pts = int(pts.shape[0])
                cen = pts.mean(axis=0) if n_pts else np.array([np.nan, np.nan])
                if n_pts >= 2:
                    ev = np.linalg.eigvalsh(np.cov(pts.T, ddof=0))
                    lam1, lam2 = float(ev[1]), float(ev[0])
                    ellip = float(np.sqrt(max(lam2, 0.0) / lam1)) if lam1 > 0.0 else float("nan")
                else:
                    lam1 = lam2 = ellip = float("nan")
                d_eff = 2.0 * np.sqrt(n_pts * 0.8 * ps * ps / np.pi)
                line += (f" | {name}: N={n_pts} cen=({cen[0]:.4f},{cen[1]:.4f}) "
                         f"lam=({lam1:.6f},{lam2:.6f}) e={ellip:.3f} d_eff={d_eff:.4f}")
                rec.extend([n_pts, pts, cen, (lam1, lam2), ellip, d_eff])
            print(line)
            slab_records.append(rec)
        over_streak = over_streak + 1 if (n_over_rim >= 5 and t >= T_FIRST_OVER_MIN) else 0
        if first_over_t is None and over_streak >= FIRST_OVER_STREAK:
            first_over_t = t - (FIRST_OVER_STREAK - 1) * DT  # the streak's first frame
        z_min_run = min(z_min_run, float(z_all[valid].min()))
        safe_last = safe
        n_adh = solver.wall_adhesion_stats()
        frame_ms = (time.time() - frame_t0) * 1000.0
        rows.append((i, t, phase, float(np.rad2deg(th)), sum_c, std_c, ke, nan_count, n_coffee_mug,
                     n_milk_jug, z_surf, n_dome, n_over_rim, n_outer_wall, n_table, n_adh,
                     0 if first_over_t is None else 1, frame_ms, n_jug_cleared,
                     n_jug_wall_tunnel, n_jug_bottom_tunnel, n_mug_cleared,
                     n_mug_wall_tunnel, n_mug_bottom_tunnel, n_leak, active_fluid,
                     ball_pose_err, z_surf, n_milk_mug, n_mug_rim_crossed,
                     n_outer_wall_coffee, n_outer_wall_milk, wall_speed_p50, wall_speed_p90,
                     wall_res_p50, wall_res_p90, wall_res_max, n_wall_ever_1s,
                     n_wall_persistent_1s, n_solver_rim_staged, n_solver_direct_tunnel,
                     n_frame_rim_probe, n_frame_low_cross_staged, wall_max_res_p90,
                     n_solver_jug_rim_staged, n_solver_jug_direct_tunnel,
                     n_frame_jug_wall_probe, n_frame_jug_wall_staged, n_frame_jug_wall_direct))
        if i % print_every == 0 or i == n_frames:
            wall = time.time() - wall0
            print(
                f"t={t:6.2f}s  ph={phase}  th={np.rad2deg(th):5.1f}  jug={n_milk_jug:6d}  "
                f"mugM={n_milk_mug:5d}  coherent_z_p75={z_surf:6.3f}  "
                f"dome={n_dome:5d}  over={n_over_rim:4d}  "
                f"outer={n_outer_wall:5d}  table={n_table:5d}  clearedJ={n_jug_cleared:5d} "
                 f"tunnelJ/M={n_jug_wall_tunnel+n_jug_bottom_tunnel}/{n_mug_wall_tunnel+n_mug_bottom_tunnel} "
                 f"staged/direct={n_solver_rim_staged}/{n_solver_direct_tunnel} "
                 f"jugStaged/direct={n_solver_jug_rim_staged}/{n_solver_jug_direct_tunnel} "
                f"KE={ke:.3e}  nan={nan_count}  "
                f"({wall / max(i, 1) * 1000:.0f} ms/frame avg)"
            )
        prev_pos = safe.copy()
        prev_origin, prev_quat = origin.copy(), quat.copy()
        prev_jlocal = cur_jlocal.copy()

    if not args.no_video:
        cam.stop_recording()
        cam_close.stop_recording()
        if cam_top is not None:
            cam_top.stop_recording()

    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(
            ["frame", "t", "phase", "theta_deg", "sum_c", "std_c", "ke", "nan", "n_coffee",
             "n_milk_in_jug", "z_surf_p99", "n_dome", "n_over_rim", "n_outer_wall", "n_table",
             "n_adh", "first_over_flag", "frame_ms", "n_jug_cleared", "n_jug_wall_tunnel",
             "n_jug_bottom_tunnel", "n_mug_cleared", "n_mug_wall_tunnel",
             "n_mug_bottom_tunnel", "n_leak", "active_fluid", "ball_pose_err",
             "z_surf_coherent_p75", "n_milk_in_mug", "n_mug_rim_crossed",
             "n_outer_wall_coffee", "n_outer_wall_milk", "outer_wall_speed_p50",
             "outer_wall_speed_p90", "outer_wall_residence_p50_s",
             "outer_wall_residence_p90_s", "outer_wall_residence_max_s",
             "n_outer_wall_ever_1s", "n_outer_wall_persistent_1s",
             "n_solver_rim_staged", "n_solver_direct_tunnel",
             "n_frame_rim_probe", "n_frame_low_cross_staged",
             "outer_wall_max_residence_p90_s",
             # Jug solver-history diagnostics.  In the spout sector (azimuth 180 deg +/- 20 deg)
             # frame probe vs solver disagreement is EXPECTED and benign: the frame probe still
             # uses the flat 0.320 clearance plane while the solver uses the spout-aware top
             # surface z_top(az) = 0.316 + spout_dz*w(az) + particle_radius (0.318 at the beak
             # centre).  n_frame_jug_wall_staged counts exactly those excused disagreements.
             "n_solver_jug_rim_staged", "n_solver_jug_direct_tunnel",
             "n_frame_jug_wall_probe", "n_frame_jug_wall_staged", "n_frame_jug_wall_direct"]
        )
        w.writerows(rows)

    if tunnel_event_records:
        with open(event_path, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=list(tunnel_event_records[0]))
            w.writeheader()
            w.writerows(tunnel_event_records)
        print(f"tunnel events: {event_path} ({len(tunnel_event_records)} events)")

    if slab_records:
        # per record: t, N, xy, centroid, (lam1, lam2), ellipticity, effective diameter - the
        # first six for the raw band, the last six for the jug-footprint-free part
        payload = {"times": np.array([r[0] for r in slab_records])}
        for name, off in (("all", 1), ("free", 7)):
            payload[f"Ns_{name}"] = np.array([r[off] for r in slab_records], dtype=np.int64)
            payload[f"cents_{name}"] = np.array([r[off + 2] for r in slab_records])
            payload[f"eigvals_{name}"] = np.array([r[off + 3] for r in slab_records])
            payload[f"ellip_{name}"] = np.array([r[off + 4] for r in slab_records])
            payload[f"d_eff_{name}"] = np.array([r[off + 5] for r in slab_records])
        for k, rec in enumerate(slab_records):
            payload[f"xy_all_{k}"] = rec[2]
            payload[f"xy_free_{k}"] = rec[8]
        np.savez(slab_path, **payload)
        print(f"stream slabs: {slab_path} ({len(slab_records)} snapshots)")
    if frame_dumps:
        np.savez(dump_path, **frame_dumps)
        meta_prefixes = ('c_', 'vel_', 'pose_', 'valid_', 'mug_resident_', 'not_jug_',
                         'jug_wall_entered_', 'jug_bottom_entered_', 'mug_wall_entered_',
                         'mug_bottom_entered_', 'mug_rim_crossed_', 'mug_cleared_',
                         'mug_wall_tunnel_', 'mug_bottom_tunnel_', 'solver_rim_staged_',
                         'solver_direct_tunnel_')
        print(f"frame dumps: {dump_path} "
              f"({len([k for k in frame_dumps if not k.startswith(meta_prefixes)])} snapshots)")

    # ---- pass/fail summary -------------------------------------------------------------------
    cols = ["frame", "t", "phase", "theta", "sum_c", "std_c", "ke", "nan", "n_coffee",
            "n_milk_jug", "z_surf", "n_dome", "n_over_rim", "n_outer_wall", "n_table", "n_adh",
            "first_over", "frame_ms", "n_jug_cleared", "n_jug_wall_tunnel",
            "n_jug_bottom_tunnel", "n_mug_cleared", "n_mug_wall_tunnel",
            "n_mug_bottom_tunnel", "n_leak", "active_fluid", "ball_pose_err",
            "z_surf_coherent_p75", "n_milk_in_mug", "n_mug_rim_crossed",
            "n_outer_wall_coffee", "n_outer_wall_milk", "outer_wall_speed_p50",
            "outer_wall_speed_p90", "outer_wall_residence_p50_s",
            "outer_wall_residence_p90_s", "outer_wall_residence_max_s",
            "n_outer_wall_ever_1s", "n_outer_wall_persistent_1s",
            "n_solver_rim_staged", "n_solver_direct_tunnel",
            "n_frame_rim_probe", "n_frame_low_cross_staged",
            "outer_wall_max_residence_p90_s",
            "n_solver_jug_rim_staged", "n_solver_jug_direct_tunnel",
            "n_frame_jug_wall_probe", "n_frame_jug_wall_staged", "n_frame_jug_wall_direct"]
    arr = {k: np.array([r_[j] for r_ in rows], dtype=float) for j, k in enumerate(cols)}
    sum_c0 = arr["sum_c"][0]
    drift = float(np.max(np.abs(arr["sum_c"] - sum_c0)) / sum_c0) if sum_c0 > 0 else float("nan")
    t_end = arr["t"][-1]
    print("=" * 78)
    print(f"[1] nan    max = {int(arr['nan'].max())}                                        "
          f"-> {'PASS' if arr['nan'].max() == 0 else 'FAIL'}")
    p2 = bool(z_min_run >= -ps - 1e-6)
    print(f"[2] z_min  min = {z_min_run:+.4f}  (table {Z_TABLE:.2f}, limit {Z_TABLE - ps:.3f})     "
          f"-> {'PASS' if p2 else 'FAIL'}")
    p3 = bool(drift < 0.01)
    print(f"[3] sum_c drift = {drift:.3e}  (limit 1e-2, sum_c0={sum_c0:.2f})      -> {'PASS' if p3 else 'FAIL'}")
    print(f"    first_over_t = {first_over_t}  (n_over_rim >= 5 for {FIRST_OVER_STREAK} consecutive "
          f"frames, from t>={T_FIRST_OVER_MIN:g}s)")
    # where did the milk end up? (final-frame census, mutually exclusive buckets in priority
    # order: jug cavity > table > mug > rest of the domain; the landing site is the pour knob)
    mkr = np.sqrt(safe_last[n_coffee:n_fluid, 0] ** 2 + safe_last[n_coffee:n_fluid, 1] ** 2)
    mkz = safe_last[n_coffee:n_fluid, 2]
    mvalid = all_valid[n_coffee:]
    mk_jug = (s_j > Z_FLOOR - ps) & (s_j < Z_RIM + ps) & (r_j <= R_JUG + ps) & mvalid
    mk_rest = mvalid & ~mk_jug
    mk_tab = mk_rest & (mkz <= 2.5 * ps) & (mkr > R_OUT + 3.0 * ps)
    mk_mug = mk_rest & ~mk_tab & (mkr <= R_IN + ps) & (mkz >= Z_FLOOR - ps)
    cen_jug, cen_tab, cen_mug = int(mk_jug.sum()), int(mk_tab.sum()), int(mk_mug.sum())
    print(f"    milk census: in jug={cen_jug}, in mug={cen_mug}, on table={cen_tab}, "
          f"other={n_milk - cen_jug - cen_mug - cen_tab} (total {n_milk}) | "
          f"milk r p50/p90 = {np.percentile(mkr, 50):.3f}/{np.percentile(mkr, 90):.3f}, "
          f"z p50/p90 = {np.percentile(mkz, 50):.3f}/{np.percentile(mkz, 90):.3f}")
    p_dome = p_fill = p_ov = True
    if not args.load_pose_smoke:
        if first_over_t is not None:
            pre = arr["t"] < first_over_t
            dur_above = float(longest_true_run(pre & (arr["z_surf"] >= Z_RIM + 0.5 * ps))) * DT
            frac, _, _ = best_window_frac(arr["t"], (arr["z_surf"] >= Z_RIM + 0.5 * ps) & pre, 2.0)
            p_dome = bool(frac >= 0.9 and dur_above >= 2.0)
            print(f"[4] dome: longest above-rim run {dur_above:.2f}s (need >=2s), "
                  f"best 2s-window fraction {frac:.2f} (need >=0.9) -> {'PASS' if p_dome else 'FAIL'}")
        else:
            p_dome = False
            print(f"[4] dome: never overflowed (n_over_rim < 5 the whole run)          -> FAIL")
        z_surf_max = float(np.nanmax(arr["z_surf"]))
        p_fill = bool(z_surf_max >= Z_RIM - ps)
        print(f"[5] coherent column-top centre p75 max = {z_surf_max:.4f}  "
              f"(legacy CSV z_surf_p99; rim {Z_RIM:.3f}, need >= {Z_RIM - ps:.3f})  "
              f"-> {'PASS' if p_fill else 'FAIL'}")
        if t_end >= T_TRICKLE:
            n_tab_end = arr["n_table"][-1]
            p_ov_a = bool(n_tab_end >= 3000)
            i0 = 0
            p_ov_b = False
            if n_tab_end > 0:
                i0 = int(np.nonzero(arr["n_table"] >= 0.05 * n_tab_end)[0][0])
                p_ov_b = bool(t_end - arr["t"][i0] >= 1.0)
            film_run = longest_true_run((arr["t"] >= arr["t"][i0]) & (arr["n_outer_wall"] > 0))
            p_ov = bool(p_ov_a and p_ov_b and film_run >= 60)
            print(f"[6] overflow: n_table end {int(n_tab_end)} (need >=3000), growth "
                  f"{t_end - arr['t'][i0]:.2f}s (need >=1s), outer-wall film {film_run} frames "
                  f"(need >=60) -> {'PASS' if p_ov else 'FAIL'}")
    mask_a = (arr["t"] >= 0.25) & (arr["t"] <= min(T_LIFT0 - 0.10, t_end))
    p_rest = True
    if mask_a.any():
        leak_c = float(np.max(np.abs(arr["n_coffee"][mask_a] - arr["n_coffee"][mask_a][0]))
                       / max(arr["n_coffee"][mask_a][0], 1))
        leak_m = float(np.max(np.abs(arr["n_milk_jug"][mask_a] - arr["n_milk_jug"][mask_a][0]))
                       / max(arr["n_milk_jug"][mask_a][0], 1))
        p_rest = bool(leak_c < 0.01 and leak_m < 0.01)
        print(f"[7] phase-A rest: coffee leak {leak_c:.4%}, milk leak {leak_m:.4%} (limit 1%) "
              f"-> {'PASS' if p_rest else 'FAIL'}")
    ke_med = float(np.median(arr["ke"][arr["t"] >= t_end - 2.0])) if t_end > 2.0 else float("nan")
    print(f"[8] KE last-2s median = {ke_med:.3e} (diagnostic)")
    ms_p95 = float(np.percentile(arr["frame_ms"], 95))
    p_ms = bool(ms_p95 < 1000.0)
    print(f"[9] frame_ms p95 = {ms_p95:.0f} (strict limit <1000) -> {'PASS' if p_ms else 'FAIL'}")
    p_pose = bool(max_ball_pose_err < 5e-7)
    print(f"[10] shared mesh/ball pose max error = {max_ball_pose_err:.3e} -> {'PASS' if p_pose else 'FAIL'}")
    p_active = bool(max_active_fluid_error == 0 and np.all(arr["active_fluid"] == n_fluid))
    print(f"[11] active fluid = {int(arr['active_fluid'].min())}..{int(arr['active_fluid'].max())} "
          f"(required {n_fluid}) -> {'PASS' if p_active else 'FAIL'}")
    jug_tunnel = int(arr["n_jug_wall_tunnel"][-1] + arr["n_jug_bottom_tunnel"][-1])
    mug_tunnel = int(arr["n_mug_wall_tunnel"][-1] + arr["n_mug_bottom_tunnel"][-1])
    p_tunnel = bool(jug_tunnel == 0 and mug_tunnel == 0)
    jug_hist_note = ""
    if args.jug_hist:
        jug_hist_note = (
            f"; jug solver staged/direct="
            f"{int(arr['n_solver_jug_rim_staged'][-1])}/{int(arr['n_solver_jug_direct_tunnel'][-1])}"
        )
    print(f"[12] historical tunnel: jug={jug_tunnel}, mug={mug_tunnel}, total n_leak={int(arr['n_leak'][-1])}"
          f"{jug_hist_note} -> {'PASS' if p_tunnel else 'FAIL'}")
    max_theta = float(arr["theta"].max())
    p_72 = bool(max_theta >= 72.0 - 1e-5)
    print(f"[13] maximum jug tilt = {max_theta:.3f} deg (need 72) -> {'PASS' if p_72 else 'FAIL'}")
    p_clear = True
    if not args.load_pose_smoke:
        cleared = int(arr["n_jug_cleared"][-1])
        p_clear = bool(cleared >= int(np.ceil(0.10 * n_milk)))
        print(f"[14] legal jug rim-cleared history = {cleared}/{n_milk} "
              f"(need >=10%) -> {'PASS' if p_clear else 'FAIL'}")

    # The dome-hold interval must actually be stream-free.  Evaluate only after one full second
    # beyond the stop ramp; use both the jug loss and mug gain, and reject any historical mug-rim
    # clearing before the independent overfill pulse.  The 0.5% milk/s limit is fixed before the
    # run and is not inferred from the observed curve.  The same interval must independently
    # contain a >=2 s coherent above-rim dome; this prevents the earlier incoming stream from
    # satisfying the dome gate.
    p_stop = True
    p_hold_dome = True
    if not args.load_pose_smoke and t_end >= T_OVERFILL:
        stop_begin = T_DOME_STOP + STOP_RAMP
        hold = (arr["t"] >= stop_begin) & (arr["t"] < T_OVERFILL)
        max_rate = 0.005 * n_milk
        if np.count_nonzero(hold) >= 2:
            idx = np.flatnonzero(hold)
            span = max(float(arr["t"][idx[-1]] - arr["t"][idx[0]]), DT)
            jug_rate = max(0.0, float(arr["n_milk_jug"][idx[0]] - arr["n_milk_jug"][idx[-1]])) / span
            mug_rate = max(0.0, float(arr["n_milk_in_mug"][idx[-1]] - arr["n_milk_in_mug"][idx[0]])) / span
        else:
            jug_rate = mug_rate = float("inf")
        pre_pulse = arr["t"] < T_OVERFILL
        pre_cleared = int(np.max(arr["n_mug_cleared"][pre_pulse])) if np.any(pre_pulse) else 0
        p_stop = bool(jug_rate <= max_rate and mug_rate <= max_rate and pre_cleared == 0)
        print(
            f"[15] stream-free hold: jug_loss={jug_rate:.1f}/s mug_gain={mug_rate:.1f}/s "
            f"(limit {max_rate:.1f}/s), pre-pulse mug-cleared={pre_cleared} -> "
            f"{'PASS' if p_stop else 'FAIL'}"
        )
        hold_above = hold & (arr["z_surf"] >= Z_RIM + 0.5 * ps) & (arr["n_dome"] > 0)
        hold_run = float(longest_true_run(hold_above)) * DT
        hold_frac, _, _ = best_window_frac(arr["t"], hold_above, 2.0)
        p_hold_dome = bool(hold_run >= 2.0 and hold_frac >= 0.9)
        print(
            f"[16] stream-free dome: longest={hold_run:.2f}s (need >=2s), "
            f"best 2s-window fraction={hold_frac:.2f} (need >=0.9) -> "
            f"{'PASS' if p_hold_dome else 'FAIL'}"
        )

    p_smooth_residence = True
    if args.smooth_a2 and not args.load_pose_smoke:
        outer_end = int(arr["n_outer_wall"][-1])
        persistent_end = int(arr["n_outer_wall_persistent_1s"][-1])
        ever_1s = int(arr["n_outer_wall_ever_1s"][-1])
        residence_p90 = float(arr["outer_wall_max_residence_p90_s"][-1])
        p_smooth_residence = bool(
            outer_end < 200 and persistent_end < 200 and ever_1s < 200 and residence_p90 < 1.0
        )
        print(
            f"[17] A2 wall residence: outer={outer_end}, persistent1s={persistent_end}, "
            f"ever1s={ever_1s} (each need <200), p90={residence_p90:.3f}s (need <1s) "
            f"-> {'PASS' if p_smooth_residence else 'FAIL'}"
        )
        print(
            f"     solver staged/direct={int(arr['n_solver_rim_staged'][-1])}/"
            f"{int(arr['n_solver_direct_tunnel'][-1])}; frame rim/low-cross-staged="
            f"{int(arr['n_frame_rim_probe'][-1])}/{int(arr['n_frame_low_cross_staged'][-1])}"
        )

    mandatory = [bool(arr["nan"].max() == 0), p2, p3, p_rest, p_ms, p_pose, p_active, p_tunnel, p_72]
    if not args.load_pose_smoke:
        mandatory += [p_dome, p_fill, p_ov, p_clear, p_stop, p_hold_dome, p_smooth_residence]
    if not all(mandatory):
        print("MF16 H ACCEPTANCE FAIL")
        raise SystemExit(1)
    print("MF16 LOAD/POSE SMOKE PASS" if args.load_pose_smoke else "MF16 H SMOKE PASS")

    print(f"csv: {csv_path}")
    for p in mp4_paths:
        print(f"mp4: {p}")


if __name__ == "__main__":
    main()
