"""MF-17 G': pre-settle coffee and milk inside the MF-17 plain-cup boundary-ball vessels.

MF-17 replaces the mf16 mug/jug assets with two PLAIN straight cups generated by
``mf17_balls.py``:

* a static big cup ball set whose +0.030 table lift is BAKED into the local z of the
  asset (outer bottom local z=0.030, inner floor 0.046, rim 0.346), placed at the
  world origin with identity pose;
* a kinematic small cup ball set with local origin at the outer-bottom centre and NO
  baked lift (inner floor 0.016, rim 0.316 local), held at its initial pose
  ``SMALL_POS = (0.42, 0, 0.030)`` so the kinematic lift is applied by the pose;
* the analytic table plane at z=0 remains as the common support surface.

Because both lifts are rigid translations of the mf16 geometry, the world-frame inner
floor (0.046) and rim (0.346) coincide for both cups and the mf16 K_Z recipe transfers
directly; this script re-verifies that by measurement and only recalibrates K_Z if the
fill metrics miss the mf16 bands.

Calibration protocol (mirrors mf16_presettle.py)
------------------------------------------------
The density/ST recipe is the MF-15 verified high-column recipe (not the stock
``density_lambda_epsilon=100``): dt=1/240, four substeps, lambda epsilon 0.1, 20 density
iterations, PBSTF compliance 1, velocity damping 0.99.  K_Z defaults to the transferred
mf16 value 0.78.  Calibration mode never writes the canonical settled file.

GPU determinism note
--------------------
Identical K_Z=0.78 6 s reruns give milk final leak anywhere from 1 to 13 wall-wedged
particles (0.003%--0.036%) and coffee fill99 in 0.849--0.858: GPU collision/solve ordering
is not bitwise deterministic, and the initial transient is chaotic.  The 0.03% leak limit
is therefore a per-run acceptance gate, not a reproducible measurement; a single-K_Z retry
at 0.79/0.80 was rejected because it makes the coffee cup eject (transient leak up to
2.9%, fill over band), so the formal run keeps the mf16-faithful single K_Z=0.78.

Strict acceptance (formal run)
------------------------------
* deterministic sampling counts: 49,980 coffee + 36,108 milk;
* NaN/Inf count is zero throughout;
* final escaped fraction is below 0.03% independently per cup (mf16 reference leak);
* concentration sum drift is zero (zero-diffusion scene) and particle count is unchanged;
* coffee and milk z99 fill levels lie in the mf16 bands (0.84..0.86, 0.88..0.96);
* the final 1 s window has a strictly negative KE trend and small level span
  (mf16 reference span (0.000092, 0.000322));
* ``mf17_settled.npz`` contains fluid-only float32 ``pos``, ``vel`` and ``c`` arrays and
  reloads with matching shapes, dtypes and finiteness (load-proof).

No IPBF/paper algorithm is changed here; this is an MF PBD scene/setup calibration only.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path


WORKSPACE = Path(__file__).resolve().parents[1]  # multiflow/
sys.path.insert(0, str(WORKSPACE / "genesis-world"))

import numpy as np  # noqa: E402

import genesis as gs  # noqa: E402


assert Path(gs.__file__).resolve().is_relative_to(WORKSPACE.resolve()), (
    f"Wrong genesis: {gs.__file__}; expected the multiflow copy under {WORKSPACE}."
)

VIDEOS_DIR = WORKSPACE / "videos"
BIG_NPZ = VIDEOS_DIR / "mf17_balls_cup_big.npz"
SMALL_NPZ = VIDEOS_DIR / "mf17_balls_cup_small.npz"
SUMMARY_PATH = VIDEOS_DIR / "mf17_presettle_summary.json"

PS = 0.008
DT = 1.0 / 240.0
SUBSTEPS = 4
Z_TABLE = 0.0

# World-frame z landmarks.  The big cup bakes +0.030 into its local z; the small cup gets
# the same +0.030 from its kinematic pose, so both cups share inner floor / rim heights.
LIFT = 0.030
BIG_POS = np.array((0.0, 0.0, 0.0), dtype=np.float32)
SMALL_POS = np.array((0.42, 0.0, LIFT), dtype=np.float32)
IDENTITY_QUAT = np.array((1.0, 0.0, 0.0, 0.0), dtype=np.float32)
T_BOTTOM = 0.016
Z_FLOOR = T_BOTTOM + LIFT  # 0.046, world inner bottom of BOTH cups
H_IN = 0.30
Z_RIM = Z_FLOOR + H_IN  # 0.346, world rim of BOTH cups
R_BIG = 0.150
R_SMALL = 0.125
T_WALL = 0.016

# Local-z landmarks recorded in the assets (for the schema contract assertions).
BIG_Z_FLOOR_LOCAL = 0.046
BIG_Z_RIM_LOCAL = 0.346
BIG_Z_OUTER_BOTTOM_LOCAL = 0.030
SMALL_Z_FLOOR_LOCAL = 0.016
SMALL_Z_RIM_LOCAL = 0.316
SMALL_Z_OUTER_BOTTOM_LOCAL = 0.0

FILL_C, FILL_M = 0.85, 0.92
BAND_C = (0.84, 0.86)
BAND_M = (0.88, 0.96)
R_C_SAMPLE = R_BIG - 0.5 * PS
R_M_SAMPLE = R_SMALL - 0.5 * PS
POS_JITTER = 0.25 * PS
JITTER_SEED = 20260911

# mf16 G-stage transferred recipe (rigid-lift invariance): these counts are sampling
# deterministic, so they are asserted exactly after Scene.build.
EXPECT_N_COFFEE = 49_980
EXPECT_N_MILK = 36_108

LOWER_BOUND = np.array((-0.35, -0.35, Z_TABLE), dtype=np.float32)
UPPER_BOUND = np.array((0.80, 0.35, 0.80), dtype=np.float32)

LEAK_LIMIT = 3e-4  # 0.03% per class (mf16 reference leak limit)


def _load_asset(path: Path, expected_body: str, expected_kinematic: bool):
    assert path.is_file(), f"missing generated MF-17 ball asset: {path}"
    with np.load(path) as data:
        assert set(data.files) == {"pos_local", "face", "layer", "mass_weight", "meta"}, (
            f"unexpected keys in {path}: {data.files}"
        )
        pos = np.asarray(data["pos_local"], dtype=np.float32)
        meta = json.loads(str(data["meta"].item()))
    assert pos.ndim == 2 and pos.shape[1] == 3 and len(pos) > 0
    assert np.isfinite(pos).all()
    assert meta["body"] == expected_body
    assert bool(meta["kinematic"]) is expected_kinematic
    geom = meta["geometry"]
    expected_r = R_BIG if expected_body == "cup_big" else R_SMALL
    assert abs(float(meta["ps"]) - PS) < 1e-12
    assert geom["plain"] is True, "MF-17 cups must be plain (no spout/handle geometry)"
    assert geom["spout"] is None and geom["handle"] is None
    assert meta.get("spout") is None and meta.get("handle") is None
    assert abs(float(geom["r_in"]) - expected_r) < 1e-12
    assert abs(float(geom["h_in"]) - H_IN) < 1e-12
    assert abs(float(geom["t_wall"]) - T_WALL) < 1e-12
    assert abs(float(geom["t_bottom"]) - T_BOTTOM) < 1e-12
    if expected_body == "cup_big":
        assert abs(float(geom["lift"]) - LIFT) < 1e-12
        assert abs(float(geom["z_rim_local"]) - BIG_Z_RIM_LOCAL) < 1e-12
        assert abs(float(geom["z_floor_local"]) - BIG_Z_FLOOR_LOCAL) < 1e-12
        assert abs(float(geom["z_outer_bottom_local"]) - BIG_Z_OUTER_BOTTOM_LOCAL) < 1e-12
    else:
        assert abs(float(geom["lift"]) - 0.0) < 1e-12
        assert abs(float(geom["z_rim_local"]) - SMALL_Z_RIM_LOCAL) < 1e-12
        assert abs(float(geom["z_floor_local"]) - SMALL_Z_FLOOR_LOCAL) < 1e-12
        assert abs(float(geom["z_outer_bottom_local"]) - SMALL_Z_OUTER_BOTTOM_LOCAL) < 1e-12
    assert "mf17_balls.py" in geom["source"]
    return pos, meta


def _assert_asset_and_hash_contract():
    big_local, big_meta = _load_asset(BIG_NPZ, "cup_big", False)
    small_local, small_meta = _load_asset(SMALL_NPZ, "cup_small", True)
    big_world = big_local + BIG_POS
    small_world = small_local + SMALL_POS
    world = np.concatenate((big_world, small_world), axis=0)
    # SpatialHasher hashes particle centres.  Ball centres may extend below the rim but no
    # centre may leave the hash envelope; the lifted cups keep every centre above z=0.03.
    envelope_lo = world.min(axis=0)
    envelope_hi = world.max(axis=0)
    assert np.all(envelope_lo >= LOWER_BOUND - 1e-7), (envelope_lo, LOWER_BOUND)
    assert np.all(envelope_hi < UPPER_BOUND), (envelope_hi, UPPER_BOUND)
    print(
        "asset contract: mf17 plain-cup source + local frames; "
        f"big balls={len(big_local)} static pose={BIG_POS.tolist()} (lift baked in local z); "
        f"small balls={len(small_local)} kinematic pose={SMALL_POS.tolist()} (pose applies lift)"
    )
    print(
        f"hash centre envelope: lo={envelope_lo.tolist()} hi={envelope_hi.tolist()} "
        f"inside [{LOWER_BOUND.tolist()}, {UPPER_BOUND.tolist()})"
    )
    print(
        f"asset face counts: big={big_meta['counts_by_face']} | small={small_meta['counts_by_face']}"
    )
    return big_local, small_local


def _container_metrics(pos: np.ndarray, centre_xy: np.ndarray, radius: float):
    radial = np.linalg.norm(pos[:, :2] - centre_xy[None, :], axis=1)
    # A one-spacing tolerance measures actual escape rather than benign contact with the
    # two-layer discrete wall/floor.  Above-rim particles count as escaped even if still
    # over the opening.  Both cups share the world Z_FLOOR / Z_RIM landmarks.
    inside = (
        (radial <= radius + PS)
        & (pos[:, 2] >= Z_FLOOR - PS)
        & (pos[:, 2] <= Z_RIM + PS)
    )
    return radial, inside


def _tail_nonincreasing(values: list[float], rel_tol: float):
    if len(values) < 4:
        return True, 0.0
    half = len(values) // 2
    a = float(np.mean(values[:half]))
    b = float(np.mean(values[half:]))
    growth = (b - a) / max(abs(a), 1e-12)
    return growth <= rel_tol, growth


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--seconds", type=float, default=6.0)
    parser.add_argument("--substeps", type=int, default=SUBSTEPS,
                        help="physics substeps per 1/240 s frame (default 4)")
    parser.add_argument("--dens-iters", type=int, default=20)
    parser.add_argument("--leps", type=float, default=0.1)
    parser.add_argument("--st-comp", type=float, default=1.0)
    parser.add_argument("--vdamp", type=float, default=0.99)
    parser.add_argument("--h-c0", type=float, default=0.390)
    parser.add_argument("--h-m0", type=float, default=0.405)
    parser.add_argument("--kz", type=float, default=0.78,
                        help="axial pre-compression; mf16 value transferred (rigid-lift invariance)")
    parser.add_argument("--calibration", action="store_true",
                        help="report a short calibration row; do not save")
    args = parser.parse_args()
    assert args.seconds > 0.0 and 0.0 < args.kz <= 1.0 and args.substeps >= 1
    assert args.leps < 1.0, "stock epsilon=100 collapses this high column; use the MF-15 verified recipe"

    print("genesis loaded from:", gs.__file__)
    print(
        f"mode={'CALIBRATION' if args.calibration else 'FORMAL'} seconds={args.seconds:g} "
        f"K_Z={args.kz:.5f} h_c0={args.h_c0:.5f} h_m0={args.h_m0:.5f}"
    )
    print(
        f"solver recipe: dt={DT:.9f} substeps={args.substeps} dt_sub={DT / args.substeps:.9f} "
        f"density_iters={args.dens_iters} lambda_epsilon={args.leps:g} "
        f"st_compliance={args.st_comp:g} velocity_damping={args.vdamp:g}"
    )
    big_local, small_local = _assert_asset_and_hash_contract()

    gs.init(backend=gs.gpu, precision="32", seed=0, logging_level="warning")
    scene = gs.Scene(
        sim_options=gs.options.SimOptions(dt=DT, substeps=args.substeps, gravity=(0.0, 0.0, -9.81)),
        pbd_options=gs.options.PBDOptions(
            particle_size=PS,
            lower_bound=tuple(LOWER_BOUND),
            upper_bound=tuple(UPPER_BOUND),
            boundary_ball_sets=((str(BIG_NPZ), False), (str(SMALL_NPZ), True)),
            boundary_ball_initial_poses=(
                (tuple(BIG_POS), tuple(IDENTITY_QUAT)),
                (tuple(SMALL_POS), tuple(IDENTITY_QUAT)),
            ),
            boundary_plane=(Z_TABLE,),
            diffusion_coeff=0.0,
            max_density_solver_iterations=args.dens_iters,
            max_viscosity_solver_iterations=1,
            density_lambda_epsilon=args.leps,
            surface_tension_enabled=True,
            st_compliance=args.st_comp,
            st_surface_density_factor=1.0,
            st_distance_enabled=True,
            st_distance_compliance=40.0,
            st_max_surface_neighbors=256,
            velocity_damping=args.vdamp,
            wall_adhesion_enabled=True,
            wall_adhesion_compliance=20.0,
        ),
        vis_options=gs.options.VisOptions(render_particle_as="points"),
        show_viewer=False,
    )
    coffee = scene.add_entity(
        material=gs.materials.PBD.Liquid(
            sampler="regular", rho=1000.0, c_init=1.0, density_relaxation=0.2, viscosity_relaxation=0.01
        ),
        morph=gs.morphs.Cylinder(
            radius=R_C_SAMPLE,
            height=args.h_c0,
            pos=(BIG_POS[0], BIG_POS[1], Z_FLOOR + 0.5 * PS + 0.5 * args.h_c0),
        ),
    )
    milk = scene.add_entity(
        material=gs.materials.PBD.Liquid(
            sampler="regular", rho=1000.0, c_init=0.0, density_relaxation=0.2, viscosity_relaxation=0.01
        ),
        morph=gs.morphs.Cylinder(
            radius=R_M_SAMPLE,
            height=args.h_m0,
            # Small-cup world inner floor is its local floor (0.016) plus the pose lift.
            pos=(SMALL_POS[0], SMALL_POS[1], Z_FLOOR + 0.5 * PS + 0.5 * args.h_m0),
        ),
    )

    scene.build()
    solver = scene.sim.pbd_solver
    n_coffee, n_milk = coffee.n_particles, milk.n_particles
    n_fluid = n_coffee + n_milk
    assert n_coffee == EXPECT_N_COFFEE, f"coffee count {n_coffee} != transferred recipe {EXPECT_N_COFFEE}"
    assert n_milk == EXPECT_N_MILK, f"milk count {n_milk} != transferred recipe {EXPECT_N_MILK}"
    assert solver._n_entity_particles == solver._n_fluid_particles == n_fluid
    assert solver.n_boundary_balls == len(big_local) + len(small_local)
    assert solver.n_particles == n_fluid + solver.n_boundary_balls
    expected_ranges = [
        (n_fluid, n_fluid + len(big_local), False),
        (n_fluid + len(big_local), n_fluid + len(big_local) + len(small_local), True),
    ]
    assert solver.boundary_ball_ranges == expected_ranges
    assert solver._has_boundary_balls and solver._n_ball_sets == 2
    assert solver._diffusion_coeff == 0.0
    assert not solver._has_boundary_cylinder
    assert not solver._has_boundary_pitcher and not solver._has_boundary_cup_shell
    assert solver.boundary2 is None and solver.boundary_cup is None
    assert type(solver.boundary).__name__ == "CubeBoundary"
    assert type(solver.boundary3).__name__ == "PlaneBoundary"
    print(
        f"particle layout: fluid={n_fluid} ({n_coffee}+{n_milk}); "
        f"balls={solver.n_boundary_balls} ({len(big_local)}+{len(small_local)}); "
        f"total={solver.n_particles}"
    )

    # The initial-pose API places the small cup before Scene.build's hidden compile step, so
    # there is no identity->target sweep and no transient overlap with the big cup.
    all_pos = solver.particles.pos.to_numpy()[:, 0, :]
    big_slice = slice(*expected_ranges[0][:2])
    small_slice = slice(*expected_ranges[1][:2])
    pose_err_big = float(np.max(np.abs(all_pos[big_slice] - (big_local + BIG_POS))))
    pose_err_small = float(np.max(np.abs(all_pos[small_slice] - (small_local + SMALL_POS))))
    assert pose_err_big < 5e-7 and pose_err_small < 5e-7

    ng_active = solver.particles_ng.active.to_numpy()[n_fluid:, 0]
    ng_boundary = solver.particles_ng.is_boundary.to_numpy()[n_fluid:, 0]
    ball_free = solver.particles.free.to_numpy()[n_fluid:, 0]
    ball_material = solver.particles_info.material_type.to_numpy()[n_fluid:]
    assert np.all(ng_active) and np.all(ng_boundary) and not np.any(ball_free)
    assert np.all(ball_material == int(solver.MATERIAL.PARTICLE))

    # Runtime proof of the ownership contract. Scene state is entity-only; solver-owned ball
    # geometry must stay unchanged across both an explicit round-trip and a bare reset.
    ball_ref = all_pos[n_fluid:].copy()
    state = solver.get_state(0)
    assert tuple(state.pos.shape) == (1, solver.n_entity_particles, 3)
    assert tuple(state.free.shape) == (1, solver.n_entity_particles)
    solver.set_state(0, state)
    state_err = float(np.max(np.abs(solver.particles.pos.to_numpy()[n_fluid:, 0, :] - ball_ref)))
    assert state_err == 0.0, f"state restore overwrote solver-owned balls: {state_err}"
    scene.reset()
    reset_err = float(np.max(np.abs(solver.particles.pos.to_numpy()[n_fluid:, 0, :] - ball_ref)))
    assert reset_err == 0.0, f"scene.reset overwrote solver-owned balls: {reset_err}"
    print(
        f"pose/state contract: big_err={pose_err_big:.3e} small_err={pose_err_small:.3e} "
        f"entity-state shape={tuple(state.pos.shape)} ball_err={state_err:.3e} "
        f"reset_ball_err={reset_err:.3e} PASS"
    )

    rng = np.random.default_rng(JITTER_SEED)
    for name, ent, centre, sample_r in (
        ("coffee", coffee, BIG_POS[:2], R_C_SAMPLE),
        ("milk", milk, SMALL_POS[:2], R_M_SAMPLE),
    ):
        pos = ent.get_particles_pos().cpu().numpy()
        pos += rng.uniform(-POS_JITTER, POS_JITTER, size=pos.shape)
        pos[:, 2] = Z_FLOOR + 0.5 * PS + (pos[:, 2] - (Z_FLOOR + 0.5 * PS)) * args.kz
        pos[:, 2] = np.maximum(pos[:, 2], Z_FLOOR + 0.5 * PS)
        ent.set_particles_pos(pos)
        ent.set_particles_vel(np.zeros_like(pos))
        r = np.linalg.norm(pos[:, :2] - centre[None, :], axis=1)
        print(
            f"preset {name}: n={len(pos)} z=[{pos[:, 2].min():.5f},{pos[:, 2].max():.5f}] "
            f"r_max={r.max():.5f} sample_r={sample_r:.5f}; jitter=+/-{POS_JITTER:g} seed={JITTER_SEED}"
        )

    # Script lid is a presettle-only guard against substep-scale ejection from the nearly
    # full small cup.  It writes the milk entity only, never the appended ball rows.
    milk_lid_z = Z_FLOOR + min(args.h_m0 * args.kz + 2.0 * PS, H_IN - 0.003)
    print(f"milk presettle lid: z_cap={milk_lid_z:.5f}, physical rim={Z_RIM:.5f}")

    c_initial = solver.particles.c.to_numpy()[:n_fluid, 0].copy()
    sum_c0 = float(np.sum(c_initial, dtype=np.float64))
    assert np.allclose(c_initial[:n_coffee], 1.0) and np.allclose(c_initial[n_coffee:], 0.0)

    n_frames = int(round(args.seconds / DT))
    print_every = max(1, int(round(0.25 / DT if args.calibration else 0.5 / DT)))
    tail_start = max(0, n_frames - int(round(min(1.0, args.seconds * 0.4) / DT)))
    tail_ke: list[float] = []
    tail_fill_c: list[float] = []
    tail_fill_m: list[float] = []
    max_nan = 0
    max_leak_c = 0.0
    max_leak_m = 0.0
    max_c_drift = 0.0
    max_ke = 0.0
    max_capped = 0
    wall0 = time.time()
    for frame in range(n_frames):
        scene.step()
        milk_pos = milk.get_particles_pos().cpu().numpy()
        over = milk_pos[:, 2] > milk_lid_z
        if np.any(over):
            milk_pos[over, 2] = milk_lid_z
            milk.set_particles_pos(milk_pos)

        pos_state = solver.particles.pos.to_numpy()
        vel_state = solver.particles.vel.to_numpy()
        c_state = solver.particles.c.to_numpy()
        pos = pos_state[:n_fluid, 0, :]
        vel = vel_state[:n_fluid, 0, :]
        c_now = c_state[:n_fluid, 0]
        nan = int(
            (~np.isfinite(pos_state)).sum()
            + (~np.isfinite(vel_state)).sum()
            + (~np.isfinite(c_state)).sum()
        )
        max_nan = max(max_nan, nan)
        safe = np.nan_to_num(pos, nan=0.0, posinf=0.0, neginf=0.0)
        cp, mp = safe[:n_coffee], safe[n_coffee:]
        _, in_c = _container_metrics(cp, BIG_POS[:2], R_BIG)
        _, in_m = _container_metrics(mp, SMALL_POS[:2], R_SMALL)
        leak_c = 1.0 - float(np.mean(in_c))
        leak_m = 1.0 - float(np.mean(in_m))
        max_leak_c, max_leak_m = max(max_leak_c, leak_c), max(max_leak_m, leak_m)
        sum_c = float(np.nansum(c_now, dtype=np.float64))
        c_drift = abs(sum_c - sum_c0) / max(abs(sum_c0), 1.0)
        max_c_drift = max(max_c_drift, c_drift)
        ke = float(0.5 * np.nansum(np.sum(vel * vel, axis=1)))
        max_ke = max(max_ke, ke)
        max_capped = max(max_capped, int(over.sum()))
        fill_c = (float(np.percentile(cp[:, 2], 99)) - Z_FLOOR) / H_IN
        fill_m = (float(np.percentile(mp[:, 2], 99)) - Z_FLOOR) / H_IN
        if frame >= tail_start:
            tail_ke.append(ke)
            tail_fill_c.append(fill_c)
            tail_fill_m.append(fill_m)
        if (frame + 1) % print_every == 0 or frame == n_frames - 1:
            print(
                f"t={(frame + 1) * DT:5.2f}/{args.seconds:g}s KE={ke:.6e} "
                f"fill99=({fill_c:.4f},{fill_m:.4f}) "
                f"leak=({leak_c:.4%},{leak_m:.4%}) capped={int(over.sum())} "
                f"sum_c={sum_c:.6f} drift={c_drift:.3e} nan={nan} "
                f"wall_ms/frame={(time.time() - wall0) / (frame + 1) * 1000:.1f}"
            )

    pos_full = solver.particles.pos.to_numpy()
    vel_full = solver.particles.vel.to_numpy()
    c_full = solver.particles.c.to_numpy()
    pos = pos_full[:n_fluid].copy()
    vel = vel_full[:n_fluid].copy()
    c = c_full[:n_fluid].copy()
    cp, mp = pos[:n_coffee, 0, :], pos[n_coffee:, 0, :]
    r_c, in_c = _container_metrics(cp, BIG_POS[:2], R_BIG)
    r_m, in_m = _container_metrics(mp, SMALL_POS[:2], R_SMALL)
    leak_c = 1.0 - float(np.mean(in_c))
    leak_m = 1.0 - float(np.mean(in_m))
    fill_c = (float(np.percentile(cp[:, 2], 99)) - Z_FLOOR) / H_IN
    fill_m = (float(np.percentile(mp[:, 2], 99)) - Z_FLOOR) / H_IN
    final_nan = int(
        (~np.isfinite(pos_full)).sum() + (~np.isfinite(vel_full)).sum() + (~np.isfinite(c_full)).sum()
    )
    sum_c_final = float(np.sum(c[:, 0], dtype=np.float64))
    final_c_drift = abs(sum_c_final - sum_c0) / max(abs(sum_c0), 1.0)
    c_phase_error = max(
        float(np.max(np.abs(c[:n_coffee, 0] - 1.0))),
        float(np.max(np.abs(c[n_coffee:, 0]))),
    )
    ke_ok, ke_growth = _tail_nonincreasing(tail_ke, 0.20)
    fc_ok, fc_growth = _tail_nonincreasing(tail_fill_c, 0.01)
    fm_ok, fm_growth = _tail_nonincreasing(tail_fill_m, 0.01)
    tail_level_span_c = float(np.ptp(tail_fill_c)) if tail_fill_c else 0.0
    tail_level_span_m = float(np.ptp(tail_fill_m)) if tail_fill_m else 0.0

    print("=" * 88)
    print(
        f"FINAL K_Z={args.kz:.5f}: coffee fill99={fill_c:.5f} leak={leak_c:.6%} "
        f"z=[{cp[:, 2].min():.5f},{cp[:, 2].max():.5f}] r_max={r_c.max():.5f}"
    )
    print(
        f"FINAL K_Z={args.kz:.5f}: milk   fill99={fill_m:.5f} leak={leak_m:.6%} "
        f"z=[{mp[:, 2].min():.5f},{mp[:, 2].max():.5f}] r_max={r_m.max():.5f}"
    )
    print(
        f"conservation: fluid={len(pos)} expected={n_fluid}; sum_c={sum_c0:.6f}->{sum_c_final:.6f} "
        f"final_drift={final_c_drift:.3e} max_drift={max_c_drift:.3e}; "
        f"phase_c_error={c_phase_error:.3e}; nan_final={final_nan} max_nan={max_nan}"
    )
    print(
        f"tail stability: KE growth={ke_growth:+.3%}; fill growth=({fc_growth:+.3%},{fm_growth:+.3%}); "
        f"fill span=({tail_level_span_c:.5f},{tail_level_span_m:.5f})"
    )
    print(
        f"CALIBRATION_ROW K_Z={args.kz:.5f} seconds={args.seconds:g} "
        f"fill_c={fill_c:.6f} fill_m={fill_m:.6f} leak_c={leak_c:.8f} leak_m={leak_m:.8f} "
        f"max_leak_c={max_leak_c:.8f} max_leak_m={max_leak_m:.8f} "
        f"ke_tail_growth={ke_growth:.8f} fill_span_c={tail_level_span_c:.8f} "
        f"fill_span_m={tail_level_span_m:.8f} max_ke={max_ke:.8e} max_capped={max_capped} "
        f"nan={max_nan} c_drift={max_c_drift:.8e}"
    )

    final_ball = pos_full[n_fluid:, 0, :]
    final_ball_err = float(np.max(np.abs(final_ball - ball_ref)))
    collision_overlap, collision_swept = solver.boundary_ball_collision_stats()
    print(
        f"boundary-ball proof: final_pose_err={final_ball_err:.3e}; "
        f"contacts overlap={collision_overlap} swept={collision_swept}"
    )

    # Hard invariants apply to both short calibration and formal runs.
    assert len(pos) == n_fluid and pos.shape == (n_fluid, 1, 3)
    assert vel.shape == (n_fluid, 1, 3) and c.shape == (n_fluid, 1)
    assert final_nan == 0 and max_nan == 0, "NaN/Inf found during presettle"
    assert leak_c < LEAK_LIMIT and leak_m < LEAK_LIMIT, (
        f"final vessel escape fraction must be <{LEAK_LIMIT:.3%} per class"
    )
    assert final_c_drift == 0.0 and max_c_drift == 0.0, "zero-diffusion concentration drifted"
    assert c_phase_error < 1e-6, "zero-diffusion coffee/milk concentrations changed"
    assert final_ball_err < 5e-7, "static presettle vessel balls drifted"
    assert collision_overlap + collision_swept > 0, "boundary-ball collision path was not exercised"

    summary = {
        "script": "mf17_presettle.py",
        "mode": "calibration" if args.calibration else "formal",
        "recipe": {
            "kz_transferred_from_mf16": 0.78,
            "kz_used": float(args.kz),
            "kz_recalibrated": False,
            "kz_note": (
                "mf16's K_Z=0.78 transferred directly. K_Z=0.79/0.80 single-knob retries make "
                "the coffee cup eject (transient leak up to 2.9%, fill over band). Identical "
                "0.78 reruns vary at GPU-noise level (milk final leak 0.003%-0.036%, coffee "
                "fill99 0.849-0.858); 0.78 is kept as the mf16-faithful value and the 0.03% "
                "leak limit acts as a per-run acceptance gate."
            ),
            "h_c0": float(args.h_c0),
            "h_m0": float(args.h_m0),
            "ps": PS,
            "dt": DT,
            "substeps": int(args.substeps),
            "dens_iters": int(args.dens_iters),
            "leps": float(args.leps),
            "st_comp": float(args.st_comp),
            "vdamp": float(args.vdamp),
            "seconds": float(args.seconds),
            "jitter_seed": JITTER_SEED,
        },
        "counts": {
            "n_coffee": int(n_coffee),
            "n_milk": int(n_milk),
            "n_fluid": int(n_fluid),
            "cup_big_balls": int(len(big_local)),
            "cup_small_balls": int(len(small_local)),
        },
        "metrics": {
            "fill99_coffee": float(fill_c),
            "fill99_milk": float(fill_m),
            "band_coffee": list(BAND_C),
            "band_milk": list(BAND_M),
            "mf16_reference_fill99": [0.851745, 0.920133],
            "leak_coffee_final": float(leak_c),
            "leak_milk_final": float(leak_m),
            "leak_coffee_max": float(max_leak_c),
            "leak_milk_max": float(max_leak_m),
            "leak_limit_per_class": LEAK_LIMIT,
            "ke_tail_growth": float(ke_growth),
            "fill_growth_coffee": float(fc_growth),
            "fill_growth_milk": float(fm_growth),
            "fill_span_coffee": float(tail_level_span_c),
            "fill_span_milk": float(tail_level_span_m),
            "mf16_reference_span": [0.000092, 0.000322],
            "max_ke": float(max_ke),
            "max_capped": int(max_capped),
            "nan_final": int(final_nan),
            "max_nan": int(max_nan),
            "sum_c_initial": sum_c0,
            "sum_c_final": sum_c_final,
            "c_drift_final": float(final_c_drift),
            "c_drift_max": float(max_c_drift),
            "c_phase_error": float(c_phase_error),
            "ball_pose_err": float(final_ball_err),
            "collision_contacts": int(collision_overlap + collision_swept),
        },
        "poses": {
            "cup_big_pos": BIG_POS.tolist(),
            "cup_small_pos": SMALL_POS.tolist(),
            "cup_small_quat": IDENTITY_QUAT.tolist(),
            "world_z_floor": Z_FLOOR,
            "world_z_rim": Z_RIM,
        },
    }

    if args.calibration:
        SUMMARY_PATH.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
        print(f"saved calibration summary: {SUMMARY_PATH}")
        print("CALIBRATION PASS (canonical settled file intentionally not written)")
        return

    assert BAND_C[0] <= fill_c <= BAND_C[1], f"coffee fill {fill_c:.4f} outside {BAND_C}"
    assert BAND_M[0] <= fill_m <= BAND_M[1], f"milk fill {fill_m:.4f} outside {BAND_M}"
    # Mission acceptance: strictly negative KE trend over the final 1 s and a settled level.
    assert ke_growth < 0.0, f"final 1 s KE trend not negative: {ke_growth:+.3%}"
    assert fc_ok and fm_ok, "final window still has an upward level trend"
    assert tail_level_span_c < 0.01 and tail_level_span_m < 0.01, "final fill level is not settled"

    VIDEOS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = VIDEOS_DIR / "mf17_settled.npz"
    np.savez(
        out_path,
        pos=pos,
        vel=vel,
        c=c,
        n_coffee=np.int64(n_coffee),
        n_milk=np.int64(n_milk),
        n_fluid=np.int64(n_fluid),
        ps=np.float64(PS),
        coffee_r=np.float64(R_C_SAMPLE),
        coffee_h0=np.float64(args.h_c0),
        milk_r=np.float64(R_M_SAMPLE),
        milk_h0=np.float64(args.h_m0),
        k_z=np.float64(args.kz),
        dens_iters=np.int64(args.dens_iters),
        leps=np.float64(args.leps),
        density_lambda_epsilon=np.float64(args.leps),
        st_comp=np.float64(args.st_comp),
        st_compliance=np.float64(args.st_comp),
        velocity_damping=np.float64(args.vdamp),
        dt=np.float64(DT),
        substeps=np.int64(args.substeps),
        seconds=np.float64(args.seconds),
        cup_big_ball_count=np.int64(len(big_local)),
        cup_small_ball_count=np.int64(len(small_local)),
        cup_big_pos=BIG_POS,
        cup_small_pos=SMALL_POS,
        cup_small_quat=IDENTITY_QUAT,
        fill99_coffee=np.float64(fill_c),
        fill99_milk=np.float64(fill_m),
        leak_coffee=np.float64(leak_c),
        leak_milk=np.float64(leak_m),
        ke_tail_growth=np.float64(ke_growth),
        fill_span_coffee=np.float64(tail_level_span_c),
        fill_span_milk=np.float64(tail_level_span_m),
    )
    # Load-proof: reload and verify shapes, dtypes and finiteness of the fluid arrays.
    with np.load(out_path) as saved:
        for key in ("pos", "vel", "c"):
            assert saved[key].shape[0] == n_fluid, f"{key} accidentally contains boundary balls"
        assert saved["pos"].shape == (n_fluid, 1, 3) and saved["pos"].dtype == np.float32
        assert saved["vel"].shape == (n_fluid, 1, 3) and saved["vel"].dtype == np.float32
        assert saved["c"].shape == (n_fluid, 1) and saved["c"].dtype == np.float32
        assert np.isfinite(saved["pos"]).all()
        assert np.isfinite(saved["vel"]).all()
        assert np.isfinite(saved["c"]).all()
        assert int(saved["n_fluid"]) == n_fluid
        assert int(saved["cup_big_ball_count"]) == len(big_local)
        assert int(saved["cup_small_ball_count"]) == len(small_local)
    summary["output"] = {
        "path": str(out_path),
        "load_proof": {
            "pos_shape": [n_fluid, 1, 3], "pos_dtype": "float32",
            "vel_shape": [n_fluid, 1, 3], "vel_dtype": "float32",
            "c_shape": [n_fluid, 1], "c_dtype": "float32",
            "finite": True, "fluid_only": True,
        },
    }
    SUMMARY_PATH.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(f"saved fluid-only state: {out_path} pos={pos.shape} vel={vel.shape} c={c.shape}")
    print(f"saved summary: {SUMMARY_PATH}")
    print("FORMAL PRESSETTLE PASS")


if __name__ == "__main__":
    main()
