"""MF-18 real-scale PBD probe: the MF-18 narrative on the PBD solver, 30 density iterations.

Same scene/timeline/metrics as mf18_realscale_ipbf.py (real-world scale: 10 cm mug, 5.6 cm jug,
ps=0.002) with the solver swapped to PBD at the user-requested settings:

  * max_density_solver_iterations=30 (the MF-17 formal PBD runs use 20; more Jacobi passes
    stiffen incompressibility, which the 4x smaller particles at real scale make harder).
  * viscosity_relaxation=0.3 (the PBD XSPH viscosity knob) mirroring the IPBF runs' xsph=0.3.
    PBD has no interface-restricted surface viscosity; the IPBF surface_viscosity_xsph has no
    PBD counterpart in this probe.
  * surface_tension_enabled=True, st_compliance rescaled with particle size (NOT transferred
    unchanged). This solver's mass convention is mass == rho_rest (see the boundary-ball init
    in pbd_solver.py), so the area-constraint denominator st_compliance/st_default_mass
    (~7e-4) dominates the gradient terms (~1e-8) by ~5 orders: the projection correction
    scales as ps^3/st_compliance per application. Matching MF-17 (ps=0.008, 480 substeps x 20
    iters) at real scale (ps=0.002, 960 x 20) therefore needs st_comp *= (0.002/0.008)^2 x
    (19200/9600) = 1/8: MF-17's 0.7 -> ~0.09 (30 iters -> ~0.13). Values < ~0.03 over-contract
    (fat beads, stringy pull-in, energy injection).

Boundaries follow the MF-17 formal pattern: Akinci ball walls generated by mf18_balls.py
(static mug set 0 + kinematic jug set 1 animated per frame via set_boundary_ball_pose) +
table plane.  The analytic clamps of the IPBF variant are unusable here: they provide no
boundary density and PBD's explicit density Jacobi geysers a fresh real-scale sample at the
wall deficit.  Milk is sampled directly in the upright jug (domain box is the primary
boundary).  Fresh + ST may pass build directly with ball walls; --presettle/--settled-npz
keeps the two-stage fallback.

Per-frame CSV: multiflow/videos/mf18_pbd{tag}_metrics.csv
Videos: multiflow/videos/mf18_pbd{tag}_{main,closeup}.mp4
"""

import argparse
import csv
import os
import sys
import time

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # multiflow/
sys.path.insert(0, os.path.join(WORKSPACE, "genesis-world"))

import numpy as np  # noqa: E402
from scipy.spatial import cKDTree  # noqa: E402

import genesis as gs  # noqa: E402

print("genesis loaded from:", gs.__file__)
assert os.path.normpath(gs.__file__).startswith(os.path.normpath(WORKSPACE)), "Wrong genesis! Must be the multiflow copy."

VIDEOS_DIR = os.path.join(WORKSPACE, "videos")

# Formal recipe (2026-09-21 diagnosis): dt=1/240 with 4 substeps (h=1/960).  Even with a
# correct epsilon, h=1/480 keeps bleeding particles through the ball wall (~64%/8 s);
# h=1/960 is required and matches the --dt help and the MF-18 formal runs.
DT = 1.0 / 240.0
SUBSTEPS = 4
PS = 0.002

# Real-world mug: 7 cm diameter mouth, 10 cm tall, 4 mm walls, standing on the table.
R_IN = 0.035
L_MUG = 0.10
T_WALL = 0.004
T_BOTTOM = 0.004
R_OUT = R_IN + T_WALL  # 0.039
Z_FLOOR = T_BOTTOM  # 0.004 cavity floor
Z_RIM = Z_FLOOR + L_MUG  # 0.104 rim
Z_TABLE = 0.0
ESCAPE_BAND = 3.0 * PS

# Real-world jug (small cup): 5.6 cm diameter, 10 cm tall; pitcher origin = inner bottom.
R_JUG = 0.028
L_JUG = 0.10
T_JUG_WALL = 0.004
T_JUG_BOTTOM = 0.004
Z_JUG_RIM = T_JUG_BOTTOM + L_JUG  # 0.104 jug-local rim

# fresh-sampled columns (lattice settles/compacts by the 0.8 volume factor into ~0.7-0.8 fill).
# H_MILK must fit the jug interior (S0 + H_MILK < L_JUG) or the sample top leaves the
# pitcher keep region on the first substep.
R_COFFEE = R_IN - 0.5 * PS  # 0.0345
# fill levels leave transient headroom: the fresh lattice compacts ~20% and the rebound
# slosh exits a brim-full vessel before the settle damping catches it
H_COFFEE = 0.090
R_MILK = R_JUG - 0.75 * PS  # 0.0265
H_MILK = 0.082
S0 = 0.5 * PS  # sample margin above the cavity floor

# jug placement / timeline: MF-17 values scaled by 1/3 (same relative geometry).
PX, PZ = 0.14, 0.0
PIVOT_X, PIVOT_Z = 0.030, 0.125
PARK_X = 0.217
T_LIFT0, T_LIFT1 = 5.0, 7.0
T_TILT0, T_TILT1 = 7.0, 11.0
T_TRICKLE = 26.0
TRICKLE_RAMP = 1.5
T_DOME_STOP = 30.0
STOP_RAMP = 1.0
STOP_RETREAT_X = 0.04 / 3.0
STOP_LIFT_Z = 0.02 / 3.0
T_OVERFILL = 34.0
OVERFILL_RAMP = 0.75
T_BACK = 37.0
T_PARK0, T_PARK1 = 42.0, 46.0
TILT_MAX_DEG = 72.0
TILT_TRICKLE_DEG = 86.0
TILT_DOME_HOLD_DEG = 65.0
# 112-deg true drain pulse (2026-09-21 diagnosis): at <=86 deg the straight-walled jug keeps a
# geometric liquid-retention wedge, so the overfill pulse must go to ~100-112 deg (the smoke
# branch already used 112) for a genuine end-of-narrative drain
TILT_OVERFILL_DEG = 112.0
DUR = 52.0

# tight domain around the pour theatre (jug rest/park span x 0.084..0.273, lift z <= 0.23):
# keeps the spatial-hash slot count ~1e6; the earlier spill-roomy domain (~5.8e6 slots)
# crashed CUDA with an async illegal address in the ball-set configuration
LOWER_BOUND = np.array((-0.05, -0.08, 0.0), dtype=np.float32)
UPPER_BOUND = np.array((0.30, 0.08, 0.26), dtype=np.float32)


def smoothstep(u):
    u = min(max(u, 0.0), 1.0)
    return u * u * (3.0 - 2.0 * u)


def _ramp(t, t0, t1):
    return smoothstep((t - t0) / max(t1 - t0, 1e-9))


def quat_roty_neg(theta):
    return np.array([np.cos(theta / 2.0), 0.0, -np.sin(theta / 2.0), 0.0])


def jug_origin_p():
    return np.array([PIVOT_X + R_JUG, 0.0, PIVOT_Z - Z_RIM])


def jug_park():
    return np.array([PARK_X, 0.0, PZ])


def jug_theta(t):
    th_max = np.deg2rad(TILT_MAX_DEG)
    th_tr = np.deg2rad(TILT_TRICKLE_DEG)
    th_hold = np.deg2rad(TILT_DOME_HOLD_DEG)
    if t < T_TILT0:
        return 0.0
    if t < T_TILT1:
        return th_max * _ramp(t, T_TILT0, T_TILT1)
    if t < T_TRICKLE:
        return th_max
    if t < T_DOME_STOP:
        return th_max + (th_tr - th_max) * _ramp(t, T_TRICKLE, min(T_TRICKLE + TRICKLE_RAMP, T_DOME_STOP))
    if t < T_OVERFILL:
        angle_start = T_DOME_STOP + 0.5 * STOP_RAMP
        return th_tr + (th_hold - th_tr) * _ramp(t, angle_start, min(T_DOME_STOP + STOP_RAMP, T_OVERFILL))
    th_over = np.deg2rad(TILT_OVERFILL_DEG)
    if t < T_BACK:
        return th_hold + (th_over - th_hold) * _ramp(t, T_OVERFILL, min(T_OVERFILL + OVERFILL_RAMP, T_BACK))
    return th_over * (1.0 - _ramp(t, T_BACK, T_PARK1))


def jug_pose(t):
    """MF-17 jug pose (scale-agnostic): (origin=outer-bottom centre, quat, axis, theta, u)."""
    th = jug_theta(t)
    a = np.array([-np.sin(th), 0.0, np.cos(th)])
    e1 = np.array([np.cos(th), 0.0, np.sin(th)])
    origin_0 = np.array([PX, 0.0, PZ])
    lift_top = np.array([PX, 0.0, PIVOT_Z - T_JUG_BOTTOM])
    origin_p = jug_origin_p()
    pivot = np.array([PIVOT_X, 0.0, PIVOT_Z])
    rot = (pivot - Z_RIM * a + R_JUG * e1) - origin_p
    u_lift = _ramp(t, T_LIFT0, T_LIFT1)
    u_tilt = _ramp(t, T_TILT0, T_TILT1)
    u_park = _ramp(t, T_BACK, T_PARK1)
    stop_mid = T_DOME_STOP + 0.5 * STOP_RAMP
    if t < T_DOME_STOP:
        u_stop = 0.0
    elif t < stop_mid:
        u_stop = _ramp(t, T_DOME_STOP, stop_mid)
    elif t < T_OVERFILL:
        u_stop = 1.0
    elif t < T_OVERFILL + OVERFILL_RAMP:
        u_stop = 1.0 - _ramp(t, T_OVERFILL, T_OVERFILL + OVERFILL_RAMP)
    else:
        u_stop = 0.0
    origin = (origin_0
              + u_lift * (lift_top - origin_0)
              + u_tilt * (origin_p - lift_top)
              + rot
              + u_stop * np.array([STOP_RETREAT_X, 0.0, STOP_LIFT_Z])
              + u_park * (jug_park() - origin_p))
    quat = quat_roty_neg(th).astype(np.float32)
    return origin.astype(np.float32), quat, a.astype(np.float32), th, u_tilt


def coherent_mug_surface(pos, vel, bulk_mask, ps):
    """MF-17 coherent surface height (p75 of column tops) and above-rim dome count."""
    core_r = R_IN - 2.0 * ps
    speed = np.linalg.norm(vel, axis=1)
    r = np.linalg.norm(pos[:, :2], axis=1)
    eligible = bulk_mask & (r <= core_r) & (speed <= 0.2)
    idx = np.flatnonzero(eligible)
    if idx.size < 32:
        return float("nan"), 0

    cell = 1.5 * ps
    nxy = int(np.ceil(2.0 * core_r / cell)) + 1
    ij = np.floor((pos[idx, :2] + core_r) / cell).astype(np.int32)
    keys = ij[:, 0].astype(np.int64) * nxy + ij[:, 1]
    order = np.lexsort((pos[idx, 2], keys))
    sorted_idx, sorted_keys = idx[order], keys[order]
    starts = np.r_[0, 1 + np.flatnonzero(sorted_keys[1:] != sorted_keys[:-1])]
    ends = np.r_[starts[1:], sorted_idx.size]
    tops = np.asarray([sorted_idx[e - 1] for s, e in zip(starts, ends) if e - s >= 4], dtype=np.int64)
    if tops.size < 24:
        return float("nan"), 0
    bulk_idx = np.flatnonzero(bulk_mask)
    tree = cKDTree(np.asarray(pos[bulk_idx], dtype=np.float64))
    n_local = tree.query_ball_point(
        np.asarray(pos[tops], dtype=np.float64), r=1.75 * ps, return_length=True, workers=-1
    )
    tops = tops[np.asarray(n_local) >= 6]
    if tops.size < 24:
        return float("nan"), 0
    top_z = pos[tops, 2]
    z_surface = float(np.percentile(top_z, 75.0))
    n_dome = int(np.count_nonzero(top_z >= Z_RIM + 0.5 * ps))
    return z_surface, n_dome


def phase_of(t):
    if t < T_LIFT0:
        return 0
    if t < T_TILT0:
        return 1
    if t < T_TILT1:
        return 2
    if t < T_TRICKLE:
        return 3
    if t < T_BACK:
        return 4
    return 5 if t < T_PARK1 else 6


def longest_true_run(mask):
    best = cur = 0
    for v in mask:
        cur = cur + 1 if v else 0
        best = max(best, cur)
    return best


def main():
    global T_LIFT0, T_LIFT1, T_TILT0, T_TILT1
    global T_TRICKLE, TRICKLE_RAMP, T_DOME_STOP, STOP_RAMP, STOP_RETREAT_X, STOP_LIFT_Z
    global T_OVERFILL, OVERFILL_RAMP, T_BACK, T_PARK0, T_PARK1
    global TILT_MAX_DEG, TILT_TRICKLE_DEG, TILT_DOME_HOLD_DEG, TILT_OVERFILL_DEG, DUR

    parser = argparse.ArgumentParser()
    parser.add_argument("--dur", type=float, default=DUR)
    parser.add_argument("--smoke", action="store_true", help="20 s compressed MF-17 smoke schedule")
    parser.add_argument("--substeps", type=int, default=SUBSTEPS)
    parser.add_argument("--dt", type=float, default=DT,
                        help="frame timestep; default = formal recipe dt=1/240 with substeps=4 (h=1/960): "
                             "the explicit density Jacobi geysers a fresh real-scale sample at h=1/480 "
                             "regardless of sampler/iteration knobs")
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--no-video", action="store_true")
    parser.add_argument("--cpu", action="store_true", help="CPU backend (debugging: illegal GPU "
                        "accesses surface as Python exceptions with stacks)")
    parser.add_argument("--tag", type=str, default="")
    parser.add_argument("--iters", type=int, default=30,
                        help="max_density_solver_iterations (MF-17 formal PBD uses 20)")
    parser.add_argument("--leps", type=float, default=0.1,
                        help="density_lambda_epsilon; the MF-17 value 0.1 transfers UNCHANGED across ps: the "
                             "spiky() kernel normalizes distance by dist_scale~ps first, so the gradient terms "
                             "and lower_sum are ps-invariant and epsilon must NOT be rescaled by 1/ps^4 (the "
                             "former 25.6 default shut the density pressure off, the column free-fell onto the "
                             "ball wall/floor and the hard-contact projection turned into a jet; 2026-09-21 "
                             "diagnosis)")
    parser.add_argument("--visc", type=float, default=0.01,
                        help="viscosity_relaxation (PBD XSPH viscosity). Default 0.01 per the 2026-09-21 "
                             "'too viscous' diagnosis: 0.3 is 30x stock and, applied every substep at "
                             "h=1/960 (960/s vs MF-12 formal 480/s), ~60x MF-12's effective viscosity - "
                             "the primary cause of the 72-deg wedge retaining 91% of the milk. If still "
                             "sluggish try 0.005 (= 0.01 x 480/960 call-rate compensation)")
    parser.add_argument("--epsd", type=float, default=0.01)
    parser.add_argument("--no-st", action="store_true")
    parser.add_argument("--presettle", type=float, default=0.0,
                        help="settle-only stage: run this many seconds with ST off and the jug "
                             "frozen at its rest pose, then dump the settled state npz and exit")
    parser.add_argument("--settled-npz", type=str,
                        default=os.path.join(VIDEOS_DIR, "mf18_pbd_settled.npz"))
    parser.add_argument("--fresh", action="store_true",
                        help="skip the settled-npz load (only valid together with --no-st: a "
                             "fresh sample with ST on cannot pass build at this scale)")
    parser.add_argument("--st-comp", type=float, default=0.09,
                        help="st_compliance; smaller = stronger tension. Compliance-dominated "
                             "denominator (mass==rho convention) makes the effective strength "
                             "scale as ps^2 x (substeps x iters) per second, so it MUST be "
                             "rescaled with particle size: MF-17's 0.7 @ ps=0.008/480x20 = "
                             "0.09 here @ ps=0.008/960x20. Scan verdict: 0.12/0.09 clean, "
                             "0.06 over-contracts (fat-bead stream, pocked surface)")
    parser.add_argument("--tilt-max", type=float, default=TILT_MAX_DEG)
    parser.add_argument("--tilt-trickle", type=float, default=TILT_TRICKLE_DEG,
                        help="trickle-phase angle; at real scale 72 deg is a near-equilibrium dribble "
                             "(~300-400 particles/s vs ~2700/s at 86 deg - 2026-09-21 ablations), so the "
                             "main-pour angle must sit in the flowing band")
    parser.add_argument("--tilt-overfill", type=float, default=TILT_OVERFILL_DEG,
                        help="overfill pulse angle; formal default 112 (below ~100 deg the straight-walled "
                             "jug keeps a retention wedge - 2026-09-21 diagnosis)")
    parser.add_argument("--st-dist", action=argparse.BooleanOptionalAction, default=True,
                        help="ST one-sided distance constraint (ablation knob for the wall-tail/cling "
                             "diagnosis; --no-st disables the whole ST block including this)")
    parser.add_argument("--no-tension", action="store_true",
                        help="clamp the PBF density constraint at zero (tension-free liquid): kills the "
                             "numerical tensile cohesion that pulls free-surface particles toward "
                             "neighbors/ball walls — structural fix #2 of the 2026-09-21 diagnosis; "
                             "the outflow insensitivity to a 30x viscosity cut points at it")
    parser.add_argument("--point-size", type=float, default=5.0)
    parser.add_argument("--point-size-cup", type=float, default=10.0)
    args = parser.parse_args()

    ps = PS
    csv_path = os.path.join(VIDEOS_DIR, f"mf18_pbd{args.tag}_metrics.csv")
    mp4_main = os.path.join(VIDEOS_DIR, f"mf18_pbd{args.tag}_main.mp4")
    mp4_closeup = os.path.join(VIDEOS_DIR, f"mf18_pbd{args.tag}_closeup.mp4")

    TILT_MAX_DEG = args.tilt_max
    DUR = args.presettle if args.presettle > 0.0 else (20.0 if args.smoke else args.dur)
    if args.smoke:
        T_LIFT0, T_LIFT1 = 2.0, 3.5
        T_TILT0, T_TILT1 = 3.5, 6.0
        T_TRICKLE, TRICKLE_RAMP = 8.0, 1.0
        T_DOME_STOP, STOP_RAMP = 11.0, 1.0
        T_OVERFILL, OVERFILL_RAMP = 14.25, 0.75
        T_BACK, T_PARK0, T_PARK1 = 17.5, 17.5, 19.0
        TILT_MAX_DEG, TILT_TRICKLE_DEG = 72.0, 78.0
        TILT_DOME_HOLD_DEG, TILT_OVERFILL_DEG = 65.0, 112.0
    else:
        TILT_OVERFILL_DEG = args.tilt_overfill
        TILT_TRICKLE_DEG = args.tilt_trickle

    # pitcher pose at t=0: the jug ball set's local frame origin = outer-bottom centre
    origin0, quat0, a0, _, _ = jug_pose(0.0)
    IDENTITY_QUAT = np.array([1.0, 0.0, 0.0, 0.0])

    CUP_NPZ = os.path.join(VIDEOS_DIR, "mf18_balls_cup_big.npz")
    JUG_NPZ = os.path.join(VIDEOS_DIR, "mf18_balls_cup_small.npz")
    for path in (CUP_NPZ, JUG_NPZ):
        if not os.path.exists(path):
            raise SystemExit(f"boundary ball asset missing: {path} - run mf18_balls.py first")

    st_on = (not args.no_st) and args.presettle == 0.0

    gs.init(backend=gs.cpu if args.cpu else gs.gpu, precision="32", seed=0)
    scene = gs.Scene(
        sim_options=gs.options.SimOptions(dt=args.dt, substeps=args.substeps, gravity=(0.0, 0.0, -9.81)),
        pbd_options=gs.options.PBDOptions(
            particle_size=ps,
            lower_bound=tuple(LOWER_BOUND),
            upper_bound=tuple(UPPER_BOUND),
            # Akinci ball walls (MF-17 formal pattern): the analytic clamps provide no
            # boundary density, and PBD's explicit density Jacobi geysers a fresh real-scale
            # sample at the ~30% wall density deficit regardless of solver knobs; IPBF's
            # implicit Newton tolerates it.  Set 0 = static mug (world frame, identity
            # pose), set 1 = kinematic jug (local frame at the outer-bottom centre).
            boundary_ball_sets=(((CUP_NPZ, False),) if os.environ.get("MF18_NO_JUG_BALLS")
                                else ((CUP_NPZ, False), (JUG_NPZ, True))),
            boundary_ball_initial_poses=(
                (((0.0, 0.0, 0.0), tuple(IDENTITY_QUAT)),) if os.environ.get("MF18_NO_JUG_BALLS")
                else (((0.0, 0.0, 0.0), tuple(IDENTITY_QUAT)),
                      (tuple(origin0), tuple(IDENTITY_QUAT)))
            ),
            boundary_ball_mass_weight_enabled=False,
            boundary_plane=(Z_TABLE,),
            max_density_solver_iterations=args.iters,
            max_viscosity_solver_iterations=1,
            density_lambda_epsilon=args.leps,
            density_clamp_negative=args.no_tension,
            diffusion_coeff=args.epsd,
            surface_tension_enabled=(not args.no_st) and args.presettle == 0.0,
            st_compliance=args.st_comp,
            st_surface_density_factor=1.0,
            st_distance_enabled=st_on and args.st_dist,
            st_distance_compliance=40.0,
            st_max_surface_neighbors=256,
            # the build-time sampler-guard state stacks the milk column 2.5 ps above the coffee
            # top; gravity closes that gap below the ring radius on the first warm-up substep and
            # the thin-film side-join admits the opposing surface into the one-ring, doubling it
            # past the stock capacity of 64
            st_max_localmesh_neighbors=128,
            # settle-stage aid (MF-17 presettle precedent); 1.0 = off in the pour stage
            velocity_damping=0.99 if args.presettle > 0.0 else 1.0,
        ),
        # rigid-PBD coupling is disabled: the fluid's vessels/table are analytic clamps and
        # ball walls, the visual entities are non-colliding, and the collide kernel faults
        # against this scene's fixed table geom (async CUDA illegal address)
        coupler_options=gs.options.LegacyCouplerOptions(rigid_pbd=False),
        vis_options=gs.options.VisOptions(
            render_particle_as="points",
        ),
        show_viewer=False,
    )

    # real-scale visuals: simple translucent cylinders matching the clamp geometry (probe;
    # the MF-17 OBJ assets have a different aspect and cannot be reused at this scale)
    mug = scene.add_entity(
        morph=gs.morphs.Cylinder(
            radius=R_OUT, height=Z_RIM, pos=(0.0, 0.0, 0.5 * Z_RIM), fixed=True, collision=False,
        ),
        material=gs.materials.Rigid(),
        surface=gs.surfaces.Default(color=(0.85, 0.85, 0.9, 0.35), opacity=0.35),
    )
    jug = scene.add_entity(
        morph=gs.morphs.Cylinder(
            radius=R_JUG + T_JUG_WALL, height=Z_JUG_RIM,
            # morph reference = geometric centre; jug_pose's origin is the OUTER-BOTTOM centre,
            # so the centre rides one half-height up the (upright) axis
            pos=tuple(origin0 + np.array([0.0, 0.0, 0.5 * Z_JUG_RIM])), fixed=True, collision=False,
        ),
        material=gs.materials.Rigid(),
        surface=gs.surfaces.Default(color=(0.9, 0.92, 0.95, 0.45), opacity=0.45),
    )
    table = scene.add_entity(
        morph=gs.morphs.Box(size=(0.87, 0.53, 0.013), pos=(0.117, 0.0, Z_TABLE - 0.0067), fixed=True),
        material=gs.materials.Rigid(),
        surface=gs.surfaces.Default(color=(0.55, 0.55, 0.58, 1.0), opacity=1.0),
    )

    # sampler="regular" (MF-17 convention): PBD's explicit density Jacobi cannot absorb the
    # +-30-50% local density scatter of the random sampler at h=1/480 - the correction geysered
    # 90% of the coffee over the rim within 1 s. The uniform lattice starts at C~0 and settles
    # gently; the fresh-lattice ST-build issue is handled by the 3.5 cm sample gap + two-stage
    # presettle instead.
    coffee = scene.add_entity(
        material=gs.materials.PBD.Liquid(
            sampler="regular", rho=1000.0, c_init=1.0, boundary_group=0,
            density_relaxation=0.2, viscosity_relaxation=args.visc,
        ),
        morph=gs.morphs.Cylinder(
            radius=R_COFFEE,
            height=H_COFFEE,
            pos=(0.0, 0.0, Z_FLOOR + S0 + 0.5 * H_COFFEE),
        ),
    )
    # the primary boundary is the domain box (ball walls are the containers), so the milk
    # is sampled directly inside the upright jug cavity, MF-17 formal pattern
    milk_sample_pos = origin0 + np.array([0.0, 0.0, T_JUG_BOTTOM + S0 + 0.5 * H_MILK])
    milk = scene.add_entity(
        material=gs.materials.PBD.Liquid(
            sampler="regular", rho=1000.0, c_init=0.0, boundary_group=1,
            density_relaxation=0.2, viscosity_relaxation=args.visc,
        ),
        morph=gs.morphs.Cylinder(
            radius=R_MILK,
            height=H_MILK,
            pos=tuple(milk_sample_pos),
        ),
    )

    camera_res = (480, 640) if args.smoke else (960, 1280)
    cam = scene.add_camera(res=camera_res, pos=(0.093, -0.473, 0.210), lookat=(0.073, 0.0, 0.077), fov=42, GUI=False)
    cam_close = scene.add_camera(res=camera_res, pos=(0.147, -0.133, 0.143), lookat=(0.020, 0.0, 0.107), fov=32, GUI=False)
    try:
        scene.build()
    except gs.GenesisException:
        # build-time ST topology failure: dump the classifier/walk counters before dying
        solver_dbg = scene.sim.pbd_solver
        dbg = solver_dbg._dbg_st.to_numpy()
        on_surf = solver_dbg.on_surface.to_numpy()[:coffee.n_particles + milk.n_particles, 0]
        pos_dbg = solver_dbg.particles_reordered.pos.to_numpy()[:coffee.n_particles + milk.n_particles, 0, :]
        n_c = coffee.n_particles
        z_split = 0.5 * (pos_dbg[:n_c, 2].max() + pos_dbg[n_c:, 2].min())
        print(f"[dbg-st] max candidates={int(dbg[0])}, max ring={int(dbg[1])}, valid meshes={int(dbg[3])}")
        print(f"[dbg-st] on_surface: total={int(on_surf.sum())} / {on_surf.size}, "
              f"coffee={int(on_surf[:n_c].sum())} / {n_c}, milk={int(on_surf[n_c:].sum())} / {on_surf.size - n_c}")
        np.savez(os.path.join(VIDEOS_DIR, "mf18_pbd_stfail_state.npz"),
                 pos=pos_dbg, on_surface=on_surf, n_coffee=n_c, ps=ps)
        print("[dbg-st] state dumped to videos/mf18_pbd_stfail_state.npz")
        raise
    print(f"mug geoms: {mug.n_geoms}, jug geoms: {jug.n_geoms}, coffee: {coffee.n_particles}, "
          f"milk: {milk.n_particles}")
    print(f"REAL SCALE PBD: R_IN={R_IN} rim={Z_RIM} R_JUG={R_JUG} ps={ps} ({R_IN / ps:.1f} particles/radius) "
          f"dt={args.dt:.5f} substeps={args.substeps} iters={args.iters} visc={args.visc:g} "
          f"st={not args.no_st} st_comp={args.st_comp:g} st_dist={args.st_dist} "
          f"tension_clamp={args.no_tension} overfill={TILT_OVERFILL_DEG:g}deg dur={DUR:g} tag='{args.tag}'")

    scene.visualizer.rasterizer._camera_targets[cam.uid].point_size = args.point_size
    scene.visualizer.rasterizer._camera_targets[cam_close.uid].point_size = args.point_size_cup

    solver = scene.sim.pbd_solver
    assert type(solver.boundary).__name__ == "CubeBoundary", f"unexpected boundary: {type(solver.boundary)}"
    assert solver.boundary2 is None
    assert type(solver.boundary3).__name__ == "PlaneBoundary", f"unexpected boundary3: {type(solver.boundary3)}"
    assert solver.n_boundary_balls == 15154 + 11678, "unexpected ball count"
    n_fluid = coffee.n_particles + milk.n_particles
    n_coffee = coffee.n_particles
    n_milk = milk.n_particles
    assert solver._n_particles == n_fluid + solver.n_boundary_balls, "unexpected particle count"

    os.makedirs(VIDEOS_DIR, exist_ok=True)

    # ---- post-build sanity: milk sampled in the upright jug cavity ------------------------
    O_jug0 = origin0 + T_JUG_BOTTOM * a0
    got = milk.get_particles_pos().cpu().numpy()
    rel_chk = got - O_jug0
    s_chk = rel_chk[:, 2]
    r_chk = np.linalg.norm(rel_chk[:, :2], axis=1)
    print(f"milk in jug: s in [{s_chk.min():.4f}, {s_chk.max():.4f}] (L={L_JUG}), "
          f"r in [{r_chk.min():.4f}, {r_chk.max():.4f}] (R={R_JUG})")
    assert r_chk.max() < R_JUG and s_chk.min() > 0.0 and s_chk.max() < L_JUG

    # ---- settled-state load (stage 2; MF-17 pour_overflow pattern) ------------------------
    # A fresh sample with ST on cannot pass build at this scale, so the pour run starts from
    # the presettle npz. The same deterministic sampler/seed guarantees matching counts.
    if args.presettle == 0.0 and not args.fresh:
        with np.load(args.settled_npz) as dat:
            settled_pos = np.asarray(dat["pos"], dtype=np.float32)
            settled_vel = np.asarray(dat["vel"], dtype=np.float32)
            settled_c = np.asarray(dat["c"], dtype=np.float32)
            assert int(dat["n_coffee"]) == n_coffee and int(dat["n_milk"]) == n_milk
            assert abs(float(dat["ps"]) - ps) < 1e-12
        assert settled_pos.shape == settled_vel.shape == (n_fluid, 1, 3)
        assert settled_c.shape == (n_fluid, 1)
        # high-energy settled states must not enter the pour run silently (2026-09-21
        # diagnosis): the load restores velocities verbatim, so a non-settled npz IS the
        # t=0 state of the run
        speed_st = np.linalg.norm(settled_vel[:, 0, :], axis=1)
        ke_st = 0.5 * float((settled_vel.astype(np.float64) ** 2).sum())
        edge = ((np.abs(settled_pos[:, 0, :] - LOWER_BOUND[None, :]) < 1e-4)
                | (np.abs(settled_pos[:, 0, :] - UPPER_BOUND[None, :]) < 1e-4)).any(axis=1)
        print(f"settled load check: KE={ke_st:.1f}, speed median={np.median(speed_st):.4f} "
              f"p99={np.percentile(speed_st, 99):.4f} max={speed_st.max():.4f} m/s, "
              f"domain-edge particles={int(edge.sum())}")
        if speed_st.max() > 0.5:
            raise SystemExit(
                f"{args.settled_npz} is a high-energy state (speed max {speed_st.max():.2f} m/s, "
                f"KE={ke_st:.0f}); it was saved by a buggy presettle - re-run the --presettle "
                "stage to regenerate it")
        coffee.set_particles_pos(settled_pos[:n_coffee, 0])
        milk.set_particles_pos(settled_pos[n_coffee:, 0])
        coffee.set_particles_vel(settled_vel[:n_coffee, 0])
        milk.set_particles_vel(settled_vel[n_coffee:, 0])
        c_full = solver.particles.c.to_numpy()
        c_full[:n_fluid] = settled_c
        solver.particles.c.from_numpy(c_full)
        bg2 = solver.particles_ng.boundary_group.to_numpy()
        bg2[:n_coffee, :] = 0
        bg2[n_coffee:n_fluid, :] = 1
        solver.particles_ng.boundary_group.from_numpy(bg2)
        print(f"settled state loaded: {args.settled_npz}")

    if args.presettle > 0.0:
        np.savez(os.path.join(VIDEOS_DIR, "mf18_pbd_settle_init.npz"),
                 pos=solver.particles.pos.to_numpy()[:n_fluid],
                 vel=solver.particles.vel.to_numpy()[:n_fluid])
        print("initial settle state dumped")

    n_frames = int(round(DUR / args.dt))
    rows = []
    wall0 = time.time()
    if not args.no_video:
        cam.start_recording(save_to_filename=mp4_main, fps=args.fps)
        cam_close.start_recording(save_to_filename=mp4_closeup, fps=args.fps)
    print_every = int(round(1.0 / args.dt))

    for i in range(n_frames + 1):
        t = i * args.dt
        # settle stage keeps the jug frozen at its rest pose (the milk settles inside it)
        origin, quat, axis, th, _ = jug_pose(0.0 if args.presettle > 0.0 else t)
        solver.set_boundary_ball_pose(1, tuple(origin), tuple(quat))
        # visual centre = outer-bottom origin + half-height along the CURRENT axis (rotating
        # the centre-fixed morph about its own centre lands the body exactly on the pose)
        jug.set_pos(origin + 0.5 * Z_JUG_RIM * axis, relative=True, zero_velocity=True)
        jug.set_quat(quat, relative=True, zero_velocity=True)

        frame_t0 = time.time()
        if i > 0:
            scene.step()

        phase = phase_of(t)
        pos_all = solver.particles.pos.to_numpy()[:n_fluid, 0, :]
        vel = solver.particles.vel.to_numpy()[:n_fluid, 0, :]
        c = solver.particles.c.to_numpy()[:n_fluid, 0]
        nan_count = int((~np.isfinite(pos_all)).sum() + (~np.isfinite(vel)).sum() + (~np.isfinite(c)).sum())
        safe = np.nan_to_num(pos_all, nan=0.0, posinf=0.0, neginf=0.0)
        safe_v = np.nan_to_num(vel, nan=0.0, posinf=0.0, neginf=0.0)
        safe_c = np.nan_to_num(c, nan=0.0, posinf=0.0, neginf=0.0)
        r_all = np.linalg.norm(safe[:, :2], axis=1)
        z_all = safe[:, 2]
        sum_c = float(safe_c.sum())
        std_c = float(safe_c.std())
        ke = float(0.5 * np.nansum((safe_v ** 2).sum(axis=1)))
        z_min = float(z_all.min())

        O_p = origin + T_JUG_BOTTOM * axis
        rel_j = safe - O_p
        s_j = rel_j @ axis
        r_j = np.linalg.norm(rel_j - s_j[:, None] * axis[None, :], axis=1)
        n_milk_jug = int(((s_j[n_coffee:] > -ps) & (s_j[n_coffee:] < L_JUG + ps)
                          & (r_j[n_coffee:] <= R_JUG + ps)).sum())
        in_jug_fp = (s_j > Z_FLOOR - 3.0 * ps) & (s_j < Z_RIM + 3.0 * ps) \
            & (r_j <= R_JUG + T_JUG_WALL + 3.0 * ps)
        not_jug = np.ones(n_fluid, dtype=bool)
        not_jug[n_coffee:] = ~in_jug_fp[n_coffee:]
        in_mug = (r_all <= R_IN + ps) & (z_all >= Z_FLOOR - ps) & (z_all <= Z_RIM + ps)
        n_coffee_mug = int((in_mug[:n_coffee]).sum())
        n_milk_mug = int((in_mug & not_jug)[n_coffee:].sum())
        bulk_surface = in_mug & not_jug
        z_surf, n_dome = coherent_mug_surface(safe, safe_v, bulk_surface, ps)
        n_over = int((not_jug[n_coffee:] & (z_all[n_coffee:] > Z_RIM + 0.5 * ps)
                      & (r_all[n_coffee:] > R_IN + ps)).sum())
        n_table = int((not_jug[n_coffee:] & (z_all[n_coffee:] <= 2.5 * ps)
                       & (r_all[n_coffee:] > R_OUT + 3.0 * ps)).sum())
        frame_ms = (time.time() - frame_t0) * 1000.0
        rows.append((i, t, phase, float(np.rad2deg(th)), sum_c, std_c, ke, nan_count,
                     n_coffee_mug, n_milk_jug, n_milk_mug, z_surf, n_dome, n_over, n_table,
                     z_min, frame_ms))
        if i % print_every == 0 or i == n_frames:
            wall = time.time() - wall0
            print(f"t={t:6.2f}s  ph={phase}  th={np.rad2deg(th):5.1f}  jug={n_milk_jug:6d}  "
                  f"mugM={n_milk_mug:5d}  z_surf={z_surf:6.4f}  dome={n_dome:5d}  over={n_over:4d}  "
                  f"table={n_table:5d}  coffeeM={n_coffee_mug:6d}  KE={ke:.3e}  nan={nan_count}  "
                  f"z_min={z_min:+.4f}  ({wall / max(i, 1) * 1000:.0f} ms/frame avg)")

    if not args.no_video:
        cam.stop_recording()
        cam_close.stop_recording()

    if args.presettle > 0.0:
        vel_end = solver.particles.vel.to_numpy()[:n_fluid, 0, :]
        speed_end = np.linalg.norm(vel_end, axis=1)
        print(f"presettle end: KE={0.5 * float((vel_end.astype(np.float64) ** 2).sum()):.1f}, "
              f"speed median={np.median(speed_end):.4f} p99={np.percentile(speed_end, 99):.4f} "
              f"max={speed_end.max():.4f} m/s")
        # Save the settled state with ZERO velocity: the pour run restores these arrays
        # verbatim, so a settled npz that kept its residual velocities loads as a
        # high-energy state at t=0 (2026-09-21 diagnosis: KE=11365, speed max 18.63 m/s,
        # 4127 particles already pinned at the domain edge).
        np.savez(args.settled_npz,
                 pos=solver.particles.pos.to_numpy()[:n_fluid],
                 vel=np.zeros((n_fluid, 1, 3), dtype=np.float32),
                 c=solver.particles.c.to_numpy()[:n_fluid],
                 n_coffee=n_coffee, n_milk=n_milk, ps=ps)
        print(f"presettle state saved (velocity zeroed): {args.settled_npz}")
        print(f"csv: {csv_path}")
        if not args.no_video:
            print(f"mp4: {mp4_main}")
        return

    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["frame", "t", "phase", "theta_deg", "sum_c", "std_c", "ke", "nan",
                    "n_coffee_mug", "n_milk_jug", "n_milk_mug", "z_surf_coherent_p75", "n_dome",
                    "n_over_rim", "n_table", "z_min", "frame_ms"])
        w.writerows(rows)

    # ---- probe summary ---------------------------------------------------------------------
    cols = ["frame", "t", "phase", "theta", "sum_c", "std_c", "ke", "nan", "n_coffee_mug",
            "n_milk_jug", "n_milk_mug", "z_surf", "n_dome", "n_over", "n_table", "z_min", "frame_ms"]
    arr = {k: np.array([r_[j] for r_ in rows], dtype=float) for j, k in enumerate(cols)}
    t_end = arr["t"][-1]
    sum_c0 = arr["sum_c"][0]
    drift = float(np.max(np.abs(arr["sum_c"] - sum_c0)) / sum_c0) if sum_c0 > 0 else float("nan")
    print("=" * 78)
    p1 = bool(arr["nan"].max() == 0)
    print(f"[1] nan max = {int(arr['nan'].max())}                                              -> {'PASS' if p1 else 'FAIL'}")
    p2 = bool(arr["z_min"].min() >= -ps - 1e-6)
    print(f"[2] z_min min = {arr['z_min'].min():+.5f}  (table {Z_TABLE:.3f}, limit {-ps:.4f})     -> {'PASS' if p2 else 'FAIL'}")
    p3 = bool(drift < 0.01)
    print(f"[3] sum_c drift = {drift:.3e}  (limit 1e-2, sum_c0={sum_c0:.2f})        -> {'PASS' if p3 else 'FAIL'}")
    mask_a = (arr["t"] >= 1.0) & (arr["t"] <= min(T_LIFT0 - 0.5, t_end))
    p4 = True
    if mask_a.any():
        n0 = arr["n_milk_jug"][mask_a][0]
        leak = float(np.max(np.abs(arr["n_milk_jug"][mask_a] - n0)) / max(n0, 1))
        p4 = bool(leak < 0.01)
        print(f"[4] phase-A milk leak = {leak:.4%} of {int(n0)} (limit 1%)       -> {'PASS' if p4 else 'FAIL'}")
    p5 = p6 = p7 = p8 = True
    if t_end >= T_BACK:
        drain = float(arr["n_milk_jug"][-1] / max(arr["n_milk_jug"][0], 1))
        p5 = bool(drain <= 0.5)
        print(f"[5] jug drain: {int(arr['n_milk_jug'][0])} -> {int(arr['n_milk_jug'][-1])} / {n_milk} "
              f"(need <=50% left) -> {'PASS' if p5 else 'FAIL'}")
    if t_end >= T_TRICKLE:
        m2m = float(arr["n_milk_mug"].max()) / n_milk
        p6 = bool(m2m >= 0.25)
        print(f"[6] milk reached mug: max n_milk_mug = {int(arr['n_milk_mug'].max())} "
              f"({m2m:.1%} of milk, need >=25%) -> {'PASS' if p6 else 'FAIL'}")
    if t_end >= T_OVERFILL:
        hold = (arr["t"] >= T_DOME_STOP + STOP_RAMP) & (arr["t"] < T_OVERFILL)
        if np.count_nonzero(hold) >= 2:
            hold_above = hold & (arr["z_surf"] >= Z_RIM + 0.5 * ps) & (arr["n_dome"] > 0)
            hold_run = float(longest_true_run(hold_above)) * args.dt
            print(f"[7] dome hold (INFORMATIONAL at real scale: capillary length ~2.7 mm makes a "
                  f"physical above-rim dome impossible): longest={hold_run:.2f}s")
        n_tab_end = int(arr["n_table"][-1])
        n_ov_max = int(arr["n_over"].max())
        p8 = bool(n_tab_end > 0)
        print(f"[8] spill: n_table end={n_tab_end}, n_over max={n_ov_max} "
              f"-> {'PASS' if p8 else 'FAIL'}")
    ms_p95 = float(np.percentile(arr["frame_ms"], 95))
    print(f"[9] frame_ms p95 = {ms_p95:.0f} (diagnostic)")
    mandatory = [p1, p2, p3, p4, p5, p6]
    if not all(mandatory):
        print("MF18 REAL-SCALE PBD PROBE FAIL")
        raise SystemExit(1)
    print("MF18 REAL-SCALE PBD PROBE CORE PASS")

    print(f"csv: {csv_path}")
    if not args.no_video:
        print(f"mp4: {mp4_main}")
        print(f"mp4: {mp4_closeup}")


if __name__ == "__main__":
    main()
